### ISSUE TITLE
Need to press yupico twice

### ISSUE THREAD

**Issue by CordlessWool** [bitwarden/browser#736] opened 2018-09-23 14:54 UTC
I activated the yupikey otp in my account and for mobile it works fine, but on the web view and the browser plugin I have to insert the key always twice. First time it always run into an error. 

For this I insert the key the first time by tipping on my yupico and than I select the input and press the yupico again, after this I am logged in. On the website of yupico it works fine.

**Comment by kspearrin** [comment] 2018-09-27 15:20
I've noticed this too. Not sure what is causing it yet.

**Comment by kspearrin** [comment] 2018-09-27 15:28
Or nevermind, I noticed something similar on FIDO U2F with my Yubikey. Regular Yubikey seems to work fine. I can't reproduce it.

**Comment by pahakalle** [comment] 2018-09-27 17:01
what browser do you use/experience this on?

**Comment by CordlessWool** [comment] 2018-10-12 12:07
I am using firefox, I retry it and right now I am not able to login via webinterface

**Comment by rvanlieshout** [comment] 2019-12-10 14:11
I'm having the same issue in both Chrome and Safari

If I press it once I'll get a:

```
2019-12-10 14:10:40.515 +00:00 [Error] The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at YubicoDotNetClient.YubicoClient..ctor(String clientId, String apiKey)
```

If I press it again it shows me the key is invalid (which makes sense since it's a concatenation of two keys)

**Comment by karrth** [comment] 2020-04-02 12:39
In my case, I was able to resolve the "input is not a valid Base-64 string" error when adding a new yubikey by exposing port 80 for the bitwarden-nginx container on the docker host.  I had previously neglected to expose it, guessing I would not try to browse there.

**Comment by djsmith85** [comment] 2022-03-24 19:46
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2022-03-24 19:46 UTC
