### ISSUE TITLE
Removing the separator in the passphrase generator makes it insert spaces

### ISSUE THREAD

**Issue by Atemu** [bitwarden/browser#1097] opened 2020-01-04 01:11 UTC
When I delete the separator in the separator field it becomes empty (as expected) but the generator inserts spaces between the words.  
I think it'd be more intuitive if leaving the separator empty generated passwords with no separators instead. If you wanted ` ` as a separator, you could still enter a ` ` character into the separator field.

**Comment by kspearrin** [comment] 2020-01-05 14:11
At the moment, a separator is required, which is why it defaults to ` ` when you empty the field.

**Comment by eliykat** [comment] 2021-05-27 04:54
As this is intended behaviour, I'm closing this issue.

If anyone wants this change, it would be considered a feature request. Please  [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

**Closed by eliykat** 2021-05-27 04:54 UTC
