### ISSUE TITLE
Extension does not load in Firefox Private Mode

### ISSUE THREAD

**Issue by liberty1tech** [bitwarden/browser#1050] opened 2019-11-04 00:08 UTC
https://github.com/bitwarden/browser/issues/136 needs to be re-opened. If Lastpass, 1Password, etc. can work in Private Mode, for Bitwarden to blame Mozilla is disingenuous and lazy.

**Comment by sahilister** [comment] 2019-11-05 12:05
It works fine for me on Firefox 70.0 on Ubuntu.

**Comment by sahilister** [comment] 2019-11-05 12:16
![IMG_20191105_173743](https://user-images.githubusercontent.com/52946452/68206916-deb43a80-fff3-11e9-9386-f59e22f71c48.jpg)
Works fine for me. Firefox 70.0 (64-bit) on Ubuntu.

**Comment by djsmentya** [comment] 2019-11-26 11:06
Check add-on settings and enable for private windows
![Screenshot 2019-11-26 at 13 04 26](https://user-images.githubusercontent.com/852690/69624488-746c4400-104d-11ea-831f-416636cc4012.png)

I think this issue can be closed

**Comment by DanielValahul** [comment] 2019-11-26 12:42
> Works fine for me. Firefox 70.0 (64-bit) on Ubuntu.

Did you change anything in settings? I'm using Firefox 70.0.1 on windows 10 and all i get in incognito is a pop-up saying that the window is not available in incognito on this navigator

**Comment by djsmentya** [comment] 2019-11-26 13:10
Hmm. looks like you right and it is not work ;(( I thought This permission allows extension to work in Private mode

**Comment by sahilister** [comment] 2019-11-27 08:17
> > Works fine for me. Firefox 70.0 (64-bit) on Ubuntu.

> Did you change anything in settings? I'm using Firefox 70.0.1 on windows 10 and all i get in incognito is a pop-up saying that the window is not available in incognito on this navigator

Other than always on Private Mode, i haven't changed anything. Maybe it's a due to different OSs (I'm on Ubuntu).

**Comment by kspearrin** [comment] 2019-12-02 16:58
Bitwarden relies on background page communication from the popup to function. In Firefox private mode, `getBackgroundPage` always returns empty. This is documented here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/extension/getBackgroundPage and https://bugzilla.mozilla.org/show_bug.cgi?id=1329304

**Comment by liberty1tech** [comment] 2019-12-03 06:05
> Bitwarden relies on background page communication from the popup to function. In Firefox private mode, `getBackgroundPage` always returns empty. This is documented here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/extension/getBackgroundPage and https://bugzilla.mozilla.org/show_bug.cgi?id=1329304

So Bitwarden is content to be subpar? 1Password and Lastpass make it work. At least be honest and admit that this is a *won’t fix* and stop implying it’s a *can’t fix/we blame Mozilla*.

>

**Comment by PinkDev1** [comment] 2019-12-29 03:59
@liberty1tech _if you want this feature so badly_, then **work on it yourself**. That's like, one of the most important aspects of Open Source software.

Also, what system are you running on? I just tested **Bitwarden 1.41.0 on Firefox 71.0 (64-bit) on a Windows 10 Version 1909** and everything works just _fine_.

This is how I have my privacy settings regarding History on Firefox: ( _about:preferences#privacy_ )
![Custom privacy settings](https://user-images.githubusercontent.com/46269721/71552154-ccdc8b80-29d5-11ea-8a41-5f3a8db885a4.png)

And also, when installing Bitwarden, I ticked this checkbox this:
![Run in private windows](https://user-images.githubusercontent.com/46269721/71552157-ebdb1d80-29d5-11ea-8845-22954c0269d8.png)

If you're not sure whether you did or not, go to _about:addons_ -> Extensions -> Bitwarden
and then scroll down to the "Run in Private Windows" section and click "allow"  (as depicted in [Djsmentya's comment](https://github.com/bitwarden/browser/issues/1050#issuecomment-558580018) )

**Comment by netsgnut** [comment] 2020-02-23 15:14
My workstation is running Linux with the latest stable version of Firefox (73.0 now, from official repo) and Bitwarden extension, with `privacy.firstparty.isolate` `false`. It did not work for me. And yes, I did allow it to run in private windows.

I also tried to read some code from other password managers like LastPass and 1Password. I have little experience in writing WebExtensions browser plugins, but I think a number of plugins did eventually have to undergo refactoring to remove the use of `chrome.extensions.getBackgroundPage` because of that. The resolution of [the Bugzilla 1329304 case](https://bugzilla.mozilla.org/show_bug.cgi?id=1329304) eventually also resulted in [Privacy Badger getting some parts of it by replacing `chrome.extensions.getBackgroundPage` with `chrome.runtime.sendMessage`](https://github.com/EFForg/privacybadger/pull/1899/files).

**Comment by ContentPersonality2** [comment] 2020-05-02 00:30
> > Bitwarden relies on background page communication from the popup to function. In Firefox private mode, `getBackgroundPage` always returns empty. This is documented here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/extension/getBackgroundPage and https://bugzilla.mozilla.org/show_bug.cgi?id=1329304
> 
> So Bitwarden is content to be subpar? 1Password and Lastpass make it work. At least be honest and admit that this is a _won’t fix_ and stop implying it’s a _can’t fix/we blame Mozilla_.
> 
> >

Other than how bluntly you've put this I don't know why anyone would disagree. From everything I've read it seems the Bitwarden developers have shifted the blame off to Mozilla and have neglected the functionality of Bitwarden in Firefox private mode.

Yes Firefox has made a decision that effects Bitwarden; however to just turn around and say there is nothing you can do is a lie. You developed the app for that platform. It's literally your job to develop your apps to work on the platforms they're supported.

The Bitwarden developers have just taken the easy route at the sacrifice of its Firefox users. It's easier for them to shift the blame to Mozilla and inconvenience Firefox users than it is to hunker down and rewrite parts of the app. It's really a shame considering Firefox is the most popular privacy focused browser backed by a non-profit company. It's also the second largest non-Chromium based browser.

As it stands Bitwarden only truly supports two browsers, Chromium based browsers and Safari. Firefox is what I would call partially supported at the most.

As it stands I'm unable to use Bitwarden at my workplace because we're forced to use Firefox. I would use Firefox at home because I do like the Firefox browser and feel better using it as it's backed by a non-profit company made for privacy however I'm just unwilling to put up with the tedious process of having to open a non-private window just to login to Bitwarden so I can use the context menu auto-fill in the private window I was originally in. I spend most my time browsing the web in a private window and I'm sure I'm not the only one.

I've also had a look at the Bitwarden community and it seems literally hundreds of people have voted to have this issue fixed [[1]](https://community.bitwarden.com/t/fix-bitwarden-in-firefox-private-mode/7872) [[2]](https://community.bitwarden.com/t/does-bitwarden-have-any-plans-to-make-a-workaround-for-the-firefox-private-mode-issue/6468).

**Comment by paudley** [comment] 2020-05-02 00:35
@ContentPersonality2 - you are free to work on it yourself if you feel it's a simple fix.  That's the beauty of open source.

**Comment by ContentPersonality2** [comment] 2020-05-02 00:41
> @ContentPersonality2 - you are free to work on it yourself if you feel it's a simple fix. That's the beauty of open source.

If I could I would however this is besides the point. I never said it was a simple fix, I simple stated that Bitwarden should be striving to fully support the platforms they add the app to.

I'm not a free user, I pay for Bitwarden, I know this doesn't give me a chair at the decision table however it gives me the opportunity to voice my opinion as a paying user. I support Bitwarden so I don't have to develop my own apps.

**Comment by liberty1tech** [comment] 2020-05-02 00:43
> you are free to work on it yourself if you feel it's a simple fix. That's the beauty of open source.

That's an flawed argument to deflect from the fact that Bitwarden has paying customers (like myself) who want to see this fixed, but the lead developer/CEO refuses to even accept responsibility and disingenuously blames Mozilla, while all other leading password managers have addressed the issue.

**Comment by paudley** [comment] 2020-05-02 00:59
> That's an flawed argument to deflect from the fact that Bitwarden has paying customers (like myself) who want to see this fixed, but the lead developer/CEO refuses to even accept responsibility and disingenuously blames Mozilla, while all other leading password managers have addressed the issue.

That's a false argument by assuming that other paying users, like myself, want the devs to work on weird edge cases.   You are talking about something that applies to a very, very small percentage of the userbase.   It's not really worth arguing about - with the amount of effort you put into this thread, you could have researched the issue yourself and been a contributor to a solution.

**Comment by ContentPersonality2** [comment] 2020-05-02 01:48
> > That's an flawed argument to deflect from the fact that Bitwarden has paying customers (like myself) who want to see this fixed, but the lead developer/CEO refuses to even accept responsibility and disingenuously blames Mozilla, while all other leading password managers have addressed the issue.
> 
> That's a false argument by assuming that other paying users, like myself, want the devs to work on weird edge cases. You are talking about something that applies to a very, very small percentage of the userbase. It's not really worth arguing about - with the amount of effort you put into this thread, you could have researched the issue yourself and been a contributor to a solution.

I wouldn't call this a weird case, it's been an issue for years and effects usability dramatically, Bitwarden only partially supports Firefox in my opinion. Also I'd just like to point out again how many people voted for that suggestion on the Bitwarden community forums for this issue to be fixed.

![](https://i.imgur.com/4ux7b6e.png)
![](https://i.imgur.com/DkBK2Dz.png)

**Comment by tomdavidson** [comment] 2020-05-02 02:04
Ill pitch in on a bounty to fund a community contrib - what do you say about putting the energy into that direction?

**Comment by AustynCohen** [comment] 2020-05-10 13:53
I'm a small business owner and I recommend Bitwarden to my clients. I use it myself and offer to setup self hosting for clients that require internal hosting. One client recently asked me if I could swap to another password manager because Bitwarden wouldn't work on Firefox private windows which is what they use primarily at their business. This issue doesn't bother me as I use Google Chrome at home, however, it is something I will take into account when offering Bitwarden to my Firefox using clients.

**Comment by walkafwalka** [comment] 2020-05-22 15:25
I am not upset that the feature is not implemented. I love Bitwarden and I understand that either the lack of demand (which I believe there is demand) or the cost to refactor can be blocking factors.

However, I am disappointed that Bitwarden developers have not acknowledged that this is an issue with their extension, not the Firefox browser. It dissuades the community from contributing because it is being defined as a non-bug despite other extensions working properly. If it is not considered a bug by the developers, would they even consider a bugfix PR?

**Comment by liberty1tech** [comment] 2020-05-27 05:49
> I am disappointed that Bitwarden developers have not acknowledged that this is an issue with their extension, not the Firefox browser.

I agree in this regard. It was enough to stop my migration from 1Password and not renew my paid BitWarden plan. 1Password is getting bloated and it's 5x the cost, but BitWarden's developer turned me off completely with his repeated disingenuous attempts to say "this is an unworkable Firefox issue," when it's absolutely not.

**Comment by UnpilotedRebuilt1** [comment] 2020-09-25 05:55
It's really disappointing as someone who wants to make the leap to Firefox to see that my favourite password manager isn't supporting Firefox as much as they could be. I've been wanting to make the jump over to Firefox for around a year now however I've held off in the hopes that Bitwarden would fix their issue with Firefox private browsing however I can see now that this has been an issue for years. I'm either going to have to scrap my plan to switch to Firefox or switch password manager entirely (the latter being more likely, which is unfortunate because I really do love Bitwarden!).

**Comment by devurandom** [comment] 2020-12-02 08:37
This appears to be a duplicate of #911 with another duplicate in #1444.

**Comment by cromefire** [comment] 2020-12-16 11:13
This is the second most voted issue in the repo right now btw

**Comment by bizxta** [comment] 2020-12-28 01:17
It is absolutely ridiculous that Bitwarden is refusing to fix this. The original issue opened over three years, and _still_ no fix for this. I've been paying for Bitwarden for over 2 years now, and _still_ no fix for this. Someone has even implemented a fix in #1225, which doesn't seem to be good enough for @kspearrin, and you _still_ refuse to assign an engineer to finalise the PR, but y'know "it's Mozilla's problem". For a company that provides security tooling, I'd expect you to be in agreement with security decisions made by the platform that you run on. Every other password manager is able to do it, but still it's Mozilla's problem. The level of big headedness from whoever is coming up with such a weak excuse for not fixing such a big part of this system astonishes me.

**Comment by ullebe1** [comment] 2020-12-28 17:16
Using `getBackgroundPage()` not only isn't compatible with Firefox in private mode, but [will also stop working in Google Chrome when they begin enforcing Manifest V3](https://developer.chrome.com/docs/extensions/mv3/mv3-migration-checklist/). Manifest V3 will be available from Chrome 88 (which is currently in Beta, expected stable on Jan 19th) and from then it is only a matter of time before either a new solution is found or the feature will be broken in both Firefox and Chrome.

**Comment by cscharf** [comment] 2020-12-28 20:56
Re-opening #136 and closing this as a duplicate. Will add link/reference with additional info.

**Closed by cscharf** 2020-12-28 20:56 UTC

**Comment by cortadojay** [comment] 2022-02-24 09:50
I just also wanted to add I moved to Bitwarden as the mobile experience was much better than Lastpass, but have been waiting for years to see if the issue of private windows and Bitwarden would be fixed. I am looking forward to more information on this issue. Thank you for a great product so far, As a web designer password managers are an invaluable tool.

**Comment by eliykat** [comment] 2022-02-28 05:33
@cortadojay, there will be support for Private Mode in the next release, see [here](https://github.com/bitwarden/browser/issues/136#issuecomment-1040855514) for details.
