### ISSUE TITLE
Does not save passwords at registration

### ISSUE THREAD

**Issue by esvnjc** [bitwarden/browser#1358] opened 2020-08-14 08:35 UTC
Bitwarden does not save username and passwords when signing up in a website It only saves when credentials are entered at login page of a website.Because of this credentials are needed to be saved manually every time when registering on a new website 

## Environment

- Operating system: Windows 10,
- Browser: Firefox 79
- Build Version 1.45.0

**Comment by Greenderella** [comment] 2020-08-14 08:51
The update password or new login banner, may not work on every single website you visit. A certain logic is used to detect these events. If the website is developed outside that logic or using un-popular conventions, Bitwarden can not detect these events.

**Comment by cscharf** [comment] 2020-08-14 13:57
Hi @esvnjc , thank you for reporting this, however this appears to be a duplicate of https://github.com/bitwarden/browser/issues/320, please feel free to note the site(s) you are or have experienced these issues on. I will close this issue.

**Closed by cscharf** 2020-08-14 13:57 UTC
Labels: duplicate

**Comment by esvnjc** [comment] 2020-08-17 11:20
@csharf bitwarden does not save passwords on **any** website at registration page but it does prompt to save password on the same website at login page

**Comment by esvnjc** [comment] 2020-08-20 18:12
@cscharf  I don't think this issue is a duplicate of #320 he is having problem at login page of some websites but the issue here is that bitwarden does not save credentials at the registering page of any website.
