### ISSUE TITLE
Using Chrome extension to fill passwords causes Dragon Nat. Speaking to display plaintext password in a correction box popup

### ISSUE THREAD

**Issue by brianpierce** [bitwarden/browser#640] opened 2018-06-08 10:38 UTC
However, filling password with Bitwarden from the right click menu does not trigger Dragon popup with the password showing in plain text.

**Comment by kspearrin** [comment] 2018-06-08 12:49
All we do is simply inject text into an password input box. I am not sure how we could change how another application such as Dragon processes that.

**Comment by brianpierce** [comment] 2018-06-08 15:03
Both Bitwarden from the right click menu and LastPass' Chrome extension can inject passwords on Chrome in Win10 without triggering this problem so I wouldn't assume you need to change how Dragon processes anything.

I'd be happy to tweak my settings or run trials if that would help.  I'm impressed with Bitwarden and Duo Security thus far.  I can work with Dragon running as long as I remember to use the right click menu but eventually another Bitwarden user will also have Dragon open and run into this issue.

**Comment by kspearrin** [comment] 2018-06-08 15:08
I honestly have no idea where to start with troubleshooting this since I am not familiar with how Dragon works. Any suggestions on what could be the problem would be appreciated.

**Comment by eliykat** [comment] 2021-02-17 01:05
Hi @brianpierce, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by eliykat** 2021-02-17 01:05 UTC
