### ISSUE TITLE
Sharing a login with an organization/collection yields "Resource not found".

### ISSUE THREAD

**Issue by alopecoid** [bitwarden/browser#1534] opened 2021-01-15 17:28 UTC
From the Bitwarden Chrome extension, sharing a login with an organization/collection yields the following error message:

```
An error has occurred
Resource not found
```

This was similarly described in [Bitwarden Server Issue #88](https://github.com/bitwarden/server/issues/88), which currently has a closed status. The work-around described in that issue did not work for me. I also manually sync'ed the vault several times, but that did not fix the issue. However, I was able to work-around the issue by sharing logins through the Web Vault instead of the Chrome extension.

- Operating system: macOS High Sierra 10.13.6 (17G14042)
- Browser: Google Chrome 87.0.4280.141 (Official Build) (x86_64)
- Build Version: Bitwarden Chrome Extension 1.47.1

**Comment by alopecoid** [comment] 2021-01-16 15:32
Note that this issue eventually did seem to resolve itself, but I can't attribute the change in behavior to anything in particular.

**Comment by clayadams5226** [comment] 2021-01-22 04:29
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by clayadams5226** 2021-01-22 04:29 UTC

**Comment by brianbiggs** [comment] 2021-05-22 18:24
Same issue with a newly created organization. Well, the organization has been around for a few weeks, but added my first family member today. Trying to share a Bitwarden entry with a Collection in the family organization gives me the "Resource not found" error above.

**Comment by MitchellXen** [comment] 2021-11-17 02:10
Also experienced the exact same issue as above. Any update on this?

**Comment by eliykat** [comment] 2021-11-24 03:59
No update, however this is a duplicate of https://github.com/bitwarden/server/issues/88, I recommend you post in that thread instead.
