### ISSUE TITLE
Using URLs "Never" is not available

### ISSUE THREAD

**Issue by kanjianjiuhao** [bitwarden/browser#1978] opened 2021-07-30 12:58 UTC
I want a password record to act on 【qq.com   /   v.qq.com   /  mail.qq.com 】, But exclude 【 mp.weixin.qq.com】.

I use URL1 （Base domain : qq.com）and URL2 （Never : mp.weixin.qq.com）.

The result is still all can be used . URL1  + URL2 is  “ OR " logic ，it's not  " AND " logic ??

Ask how to use the " Never", Thx  Guys ( Do not use Regular expression pleasse )

**Comment by kanjianjiuhao** [comment] 2021-07-30 14:56
#1610 
#761 

I found the answer, it turned out to be " OR " logic
But also look forward to future updates " AND " logic

Thanks to those who shared for Regular expression
Thanks to the developers for their hard work

**Comment by eliykat** [comment] 2021-08-02 03:36
Good to hear you figured it out. I'll close this as a duplicate of the other threads you linked.

**Closed by eliykat** 2021-08-02 03:36 UTC
