### ISSUE TITLE
Focus is not on Master Password field when opening popup

### ISSUE THREAD

**Issue by SylwesterZarebski** [bitwarden/browser#261] opened 2017-09-29 14:15 UTC
Version: 1.17.1
Browser: Firefox 56

In recent version when i click on icon or use <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>Y</kbd> to open popup, Master Password field is not in focus and has to click on it or press 3x <kbd>TAB</kbd>.
In previous versions Master Password field was in focus automatically.

**Comment by kspearrin** [comment] 2017-09-29 16:33
Looks to be a bug in Firefox 56+. We didn't change anything here and I just tested in Firefox ECR (52) and it focuses just fine.

**Comment by kspearrin** [comment] 2017-09-29 16:48
Opened bug report here: https://bugzilla.mozilla.org/show_bug.cgi?id=1404411

**Comment by kspearrin** [comment] 2017-09-29 17:59
Looks like it was confirmed. Closing since it's not our issue.

**Closed by kspearrin** 2017-09-29 17:59 UTC

**Comment by SylwesterZarebski** [comment] 2017-09-30 14:43
Thanks a lot for creating bug report to bugzilla, i did not expect this is some kind of regression bug in Firefox.
