### ISSUE TITLE
Bitwarden process don't exit after unlocking Bitwarden edge/chrome extension by Windows Hello PIN

### ISSUE THREAD

**Issue by tqjason** [bitwarden/browser#2003] opened 2021-08-11 14:07 UTC
Bitwarden process don't exit after Unlock Bitwarden edge/chrome extension by windows Hello PIN

## Describe the Bug

Bitwarden process that is spawned when unlock Bitwarden edge/chrome extension by Windows Hello PIN don't exit after edge/chrome closed.
And parent edge/chrome process in the same process tree don't exit either.

They should be exit I think.

## Steps To Reproduce

1. Click on Bitwarden edge/chrome extension icon
2. Click on 'Unlock with biometrics'
3. Type PIN in windows hello dialog to unlock Bitwarden extension
4. then close edge/chrome browser
5. find the remaining Bitwarden process in taskmgr

## Screenshots or Videos

![processtree](https://user-images.githubusercontent.com/37337136/128819064-13d4746d-8500-4bb1-b075-262265114f8d.jpg)

## Environment

- Win10 20H2
- Bitwarden v1.27.1
- Bitwarden edge/chrome extension v1.51.1

**Comment by Hinton** [comment] 2021-08-16 10:11
Closing as a duplicate of https://github.com/bitwarden/desktop/issues/1016

**Closed by Hinton** 2021-08-16 10:11 UTC
