### ISSUE TITLE
Performance issues when adding/editing URI entries

### ISSUE THREAD

**Issue by Morgon** [bitwarden/browser#1209] opened 2020-04-16 20:29 UTC
Using the Chrome extension, I generally don't have any performance issues with Bitwarden, except for editing the matched URI; especially when using a different match detection. 

I do notice that if I toggle the Gear icon, my text changes are immediately reflected. So I'm wondering if this is simply a display issue.

Recreation Steps:
1. Edit an item with a Website element.
2. Type in the Username field, note how fluid it is
3. Click somewhere in the URI and start backspacing. Changes are not immediately reflected; they either show up after a few seconds, or I can click another element to nudge it back to life.

**Comment by denbue** [comment] 2020-06-09 09:30
I'm having the same issue for a while. Currently on Version 1.44.3

**Comment by jmeridth** [comment] 2021-02-23 19:20
Same issue with notes field on secure notes in Chrome extension

**Comment by bgallagher** [comment] 2021-03-18 11:24
I have the same problem in Chrome (Version 89.0.4389.82) on a Mac (10.15.7).

**Comment by eliykat** [comment] 2021-06-28 21:43
I'm closing this as a duplicate of #1854, which seems to be the more general version of this particular issue.

**Closed by eliykat** 2021-06-28 21:43 UTC
