### ISSUE TITLE
Edge extension is (very) slow compared to the others

### ISSUE THREAD

**Issue by Mart124** [bitwarden/browser#648] opened 2018-06-13 20:30 UTC
Hi,

Edge extension is extremely slow, compared to the other extensions or desktop applications.
Searching for items is very slow, as well as for example going through the menus of the extension.
The whole Edge extension is slow, it takes time to answer.

We reproduced this on 2 different computers, with 2 different users :
- sharing 260 items through 37 collections (not in folders, just organized thanks to the collections) ;
- one having 30 personal additional passwords (in 1 folder) ;
- the other having 280 additional passwords (in 5 folders).

Items in vault are like this : https://pastebin.com/raw/skBitr9b
where you have the number of passwords and notes in database, and the length of the `data` field (for example we have 108 passwords having `len(data)==483`)
Not so many items, and only a few "big" notes.

We tested with a vault containing only 3 or 4 passwords, Edge extension then runs a little bit faster, but is still slower than the other extensions & apps.

Is there any known performance issue with the Edge extension ?

Many thanks 👍

**Comment by kspearrin** [comment] 2018-06-13 20:57
Yes, this is a known problem. Edge has big performance issues with extensions in general. There are lots of conditional checks in places to try to make things better, but in the end it's still going to be a problem. The problem will get worse with the more items that are in your vault listing.

It is likely related to https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/16906063/

**Comment by Mart124** [comment] 2018-06-16 13:19
Thank you very much @kspearrin for your answer 👍
So sounds like Microsoft has some bugs to deal with !

However I also wonder, I'm not sure how the search index is built locally, but do we really need to decrypt all data to search through the items ?
What about a lightweight list, containing only searchable data (login names & URIs, note names...) ?
Then, requested data (login username & password, note content...) would be decrypted on the fly.
Perhaps it could help having less data in memory ?

**Comment by kspearrin** [comment] 2018-06-16 18:22
I don't believe the problem is with decryption. That only happens once during unlock and is cached. The problem is iterating rows of data in the vault listing (`ngFor`).

**Comment by Mart124** [comment] 2018-06-16 18:30
Yes I was speaking more generally, for all extensions, as you said, and of course, "_the problem will get worse with the more items that are in your vault listing_.
I then thought that thinking about a way to make index lighter would perhaps globally help.
Anyway, even if the vault has 1000 items, each item let's say 1000 bytes (which is I think a quite big value), there would be less than 1 MB of data, which is rather tiny...

**Comment by djsmith85** [comment] 2021-11-24 20:50
Closing this as related to old Edge version (pre-Chrome).

**Closed by djsmith85** 2021-11-24 20:50 UTC
