### ISSUE TITLE
Captcha not loading on Vivaldi for Linux.

### ISSUE THREAD

**Issue by luvicsoura** [bitwarden/browser#2432] opened 2022-03-03 23:33 UTC
### Steps To Reproduce

1. Click on the extension icon
2. Fill in the email/username field
3. Fill in the password/field
5. Click "log in"

### Expected Result

hCaptcha should be loaded underneath the password field

### Actual Result

The iframe gets appended, but hCaptcha fails to load leaving a blank rectangle underneath the password field.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/12973202/156670572-3130d2db-e752-4613-9bdd-195bf6b64a2d.png)

### Additional Context

I get the following to errors logged to the console when inspecting the extension:

- No valid response from extension script.
- Unchecked runtime.lastError: The message port closed before a response was received.

I've tried to login with all other extensions and the built in ad/tracker blocker disabled to no avail.

### Operating System

Linux

### Operating System Version

Pop!_OS 21.10 (Gnome 40.4.0)

### Web Browser

Vivaldi

### Browser Version

5.1.2567.49 (Stable channel) stable (64-bit)

### Build Version

1.56.6

**Comment by luvicsoura** [comment] 2022-03-03 23:34
I understand this could be a duplicate of https://github.com/bitwarden/browser/issues/2426

**Comment by eliykat** [comment] 2022-03-04 00:46
Closing as a duplicate of #2426 as there is more discussion about it over there.

**Closed by eliykat** 2022-03-04 00:46 UTC
Labels: bug
