### ISSUE TITLE
Bitwarden keeps asking main password

### ISSUE THREAD

**Issue by Vinz87** [bitwarden/browser#1316] opened 2020-06-30 23:15 UTC
## Describe the Bug
Despite the Timeout Setting being "at browser restart" or "after 4 hours", Bitwarden keeps asking the main password to unlock after a few minutes.

## Environment

- Operating system: macOS High Sierra
- Browser: Safari 13.1.1
- Build Version (go to "Settings" → "About" in the app): 1.18.0

**Comment by cscharf** [comment] 2020-07-01 14:55
This is a duplicate of https://github.com/bitwarden/browser/issues/1021

**Closed by cscharf** 2020-07-01 14:55 UTC
