### ISSUE TITLE
Logged out vault doesn't always ask for two-factor code

### ISSUE THREAD

**Issue by qfyra** [bitwarden/browser#2100] opened 2021-10-05 12:56 UTC
### Steps To Reproduce

Primarily using FireFox for Windows 10. Once my vault is logged out it doesn't always ask for my two-factor authentication code, sometimes it's enough to just enter my master password. I want the former, i.e. always ask for code once the vault is logged out, including when the browser closes. For instance, now when I needed my github password to log in to report this, I open up a brand new FireFox window, and when I logged in I only had to supply my master password. I havent been logged in to the Bitwarden browser extension for several days on this particular compter, so it _should_ ask for a two factor code given that I have my settings set to 30 minute timeout and "log out" as the timeout action. I've verified this setting in my online vault as well.

### Expected Result

When my timeout setting is e.g. 30 minutes and my timeout action is to log out, and I have two factor authentication enabled, I expect to have to supply a two factor code after entering my master password if the vault is logged out either by myself manually or by the timer, or by closing the browser.

### Actual Result

Actual result is that sometimes I only have to put in my master password and no code.  I havent been able to figure out when this happens. All I can say it happens "sometimes". 

### Operating System

Windows

### Operating System Version

Win 10 Pro (20H2) v19042.1237

### Web Browser

Firefox

### Browser Version

92.0.1 (64 bit)

### Build Version

1.53.0

**Comment by kendratodd** [comment] 2021-11-10 16:54
Hi @qfyra, since there seem to be a few viable suggestions/a resolution for the issue you're experiencing, I'm going to close this issue for now. Please let us know if you're still experiencing this!

**Closed by kendratodd** 2021-11-10 16:54 UTC
Labels: bug

**Comment by eliykat** [comment] 2022-03-21 10:27
Hi @qfyra, can you please contact our Customer Success team here: https://bitwarden.com/contact/. They'll help you debug the issue, if they can reproduce it then I can reopen the thread here with that extra information. You can include a link to this thread in your message.
