### ISSUE TITLE
Registering on a site with a generated password: Unsaved entry is gone after closing the popup

### ISSUE THREAD

**Issue by janopae** [bitwarden/browser#2291] opened 2022-01-25 17:41 UTC
### Steps To Reproduce

1. Open any register form for any website you like
2. Open the Bitwarden extension to add an entry
3. Fill in any data you like
4. Click on the page with the form again (e. g. to paste a password you generated in Bitwarden)
5. Re-open the extension
6. Everything you typed in is gone

### Expected Result

Unfinished entries shouldn't be gone when opening the extension again. Opening the extension should bring it up in the same state where it has been left.

### Actual Result

Bitwarden shows the default "Tab" page. Adding a new entry will give you an empty form.

### Operating System

Linux

### Web Browser

Firefox

### Build Version

1.55.0

**Comment by eliykat** [comment] 2022-01-27 05:01
Duplicate of #1798, please see [my comment](https://github.com/bitwarden/browser/issues/1798#issuecomment-831574003) closing that issue.

There are some workarounds suggested in that comment, however how I usually handle it is to save the entry in Bitwarden, then autofill it into the registration form.

**Closed by eliykat** 2022-01-27 05:01 UTC
Labels: bug
