### ISSUE TITLE
Unable to use TOTP feature on 1.56.0 (Chrome)

### ISSUE THREAD

**Issue by 81Denton** [bitwarden/browser#2348] opened 2022-02-11 08:06 UTC
### Steps To Reproduce

1. Install Bitwarden 1.56.0 extension on Chrome
2. Log into your Bitwarden account
3. Use the browser extension to open an entry with existing TOTP credentials

### Expected Result

1. User should be able to copy the TOTP code via the "Copy Verifiction Code" icon next to an entry preview.
2. User should be able to view the TOTP code when opening an entry via the "View" icon.

### Actual Result

1. The "Copy Verifiction Code" icon is greyed out and non functional for all entries, regardless of whether they have existing TOTP keys or not.
2. TOTP keys and their generated codes are entirely missing from entries, unlike in previous versions of the browser extension. TOTP keys are still visible and functional in the Bitwarden web vault (vault.bitwarden.com) and Windows desktop app.

### Screenshots or Videos

Entry 1 has a registered TOTP key, Entry 2 doesn't - "Copy Verifiction Code" icon greyed out and non functional on either.

![image](https://user-images.githubusercontent.com/32391752/153555956-9ebc599d-8483-4cdc-8947-9ef032f089cd.png)

Entry has a registered TOTP key, but this is not visible in the browser extension.

![image](https://user-images.githubusercontent.com/32391752/153556220-b85afddb-e4e4-4bae-8274-5d0b42623f09.png)

### Additional Context

TOTP keys are still visible and work as usual in the Bitwarden web vault (vault.bitwarden.com) and Windows desktop app.

### Operating System

Windows

### Operating System Version

Windows 10 Pro 64 Bit 19044.1526

### Web Browser

Chrome

### Browser Version

98.0.4758.82 (Official Build) (64-bit)

### Build Version

1.56.0

**Comment by StefAtMentech** [comment] 2022-02-11 08:08
You just beat me to it. It's not working for me as well.

**Comment by davidmz** [comment] 2022-02-11 08:39
Had the same problem. TOTP worked after uninstalling/reinstalling the extension.

**Comment by StefAtMentech** [comment] 2022-02-11 08:42
> Had the same problem. TOTP worked after uninstalling/reinstalling the extension.

Thanks! This worked for me.

**Comment by sander732** [comment] 2022-02-11 09:56
> Same issue for me, totp and some autocomplete does not work.

Have you try to reinstalling the extension?

**Comment by carcuevas** [comment] 2022-02-11 10:11
Also happening for me, using Brave and Arch Linux...

**Comment by RafaelMoreira1180778** [comment] 2022-02-11 10:54
> @sander732 thank you! I removed the extension on chrome and reinstall did the magic!

+1 for me, reinstalling fixed it

**Comment by cscharf** [comment] 2022-02-11 13:53
Thanks for the report. A fix for this will be released shortly. Closing this as a duplicate of #2330.

**Closed by cscharf** 2022-02-11 13:53 UTC
Labels: bug, duplicate
