### ISSUE TITLE
[Firefox Nightly] Crash when trying to overwrite password

### ISSUE THREAD

**Issue by SinBirb** [bitwarden/browser#172] opened 2017-06-02 13:27 UTC
I want to generate a password for an existing entry where there is already a password.

When it asks me if I want to overwrite the old password, I click on yes, the browser hangs, then I get asked if I want to debug, stop or wait the script (Message: "Script: moz-extension://9cc854d4-ec6a-…7dc8e72a5/lib/jquery/jquery.js:3598"). I click on debug, but the only thing that happens is that the extension window disappears. Once the browser completely crashed.

Here is the related log from browser console:

> Error: Script terminated by timeout at:
access@moz-extension://9cc854d4-ec6a-4ea4-a446-b697dc8e72a5/lib/jquery/jquery.js:3598:3
css@moz-extension://9cc854d4-ec6a-4ea4-a446-b697dc8e72a5/lib/jquery/jquery.js:6298:10
setDimension@moz-extension://9cc854d4-ec6a-4ea4-a446-b697dc8e72a5/lib/angularjs-slider/rzslider.js:1482:9
updateSelectionBar@moz-extension://9cc854d4-ec6a-4ea4-a446-b697dc8e72a5/lib/angularjs-slider/rzslider.js:1282:9
initHandles@moz-extension://9cc854d4-ec6a-4ea4-a446-b697dc8e72a5/lib/angularjs-slider/rzslider.js:796:9
calcViewDimensions@moz-extension://9cc854d4-ec6a-4ea4-a446-b697dc8e72a5/lib/angularjs-slider/rzslider.js:961:11
calcDimFn@moz-extension://9cc854d4-ec6a-4ea4-a446-b697dc8e72a5/lib/angularjs-slider/rzslider.js:354:11
dispatch@moz-extension://9cc854d4-ec6a-4ea4-a446-b697dc8e72a5/lib/jquery/jquery.js:4736:16
add/elemData.handle@moz-extension://9cc854d4-ec6a-4ea4-a446-b697dc8e72a5/lib/jquery/jquery.js:4549:6
  jquery.js:3598:3
TypeError: can't access dead object[Learn More]  vertical-tabbrowser.xml:375:1
TypeError: can't access dead object[Learn More]  CustomizableUI.jsm:4120:1
TypeError: can't access dead object[Learn More]  tabbrowser.xml:7853:1
NS_ERROR_NOT_AVAILABLE:   ext-browser-content.js:261
TypeError: content is null[Learn More]  ext-browser-content.js:233:9
OpenGL compositor Initialized Succesfully.
Version: 3.0 Mesa 17.1.0
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
FBO Texture Target: TEXTURE_2D

**Comment by kspearrin** [comment] 2017-06-02 14:58
Looks like the length slider is crashing. Can you try this demo website to see if it has issues as well?

http://angular-slider.github.io/angularjs-slider/

**Comment by SinBirb** [comment] 2017-06-02 15:05
No problems on this website- I was just randomly dragging everything...

**Comment by kspearrin** [comment] 2017-06-02 15:19
Interesting. Does it happen if you go to the password generator like normal or only when you do the override?

**Comment by SinBirb** [comment] 2017-06-02 16:49
Only when I want to generate a new random password when there exists already one.

Interestingly, this does not happen in the following scenario:
I close the popup, I open it again, I add a new account with random password. Now I'm able to generate a new random password for all accounts, the crash does **not** happen.

When I close the popup again and open it and directly go to edit an account, generate new random password, and click on yes, it freezes again (haven't gotten a browser crash anymore) and I need to stop it with the firefox message "A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.".

**Comment by kspearrin** [comment] 2017-06-02 17:00
Weird. I am unable to reproduce it on Firefox production myself. I'll continue to try.

**Comment by kspearrin** [comment] 2017-06-14 12:42
I can now reproduce this on Firefox.

**Comment by kspearrin** [comment] 2017-06-14 13:06
I can only reproduce this when running the extension in `about:debugging` mode. If I install it directly from the addon store it works fine. Are you seeing the same?

**Comment by SinBirb** [comment] 2017-06-14 15:07
I installed the addon from http://addons.mozilla.org/ , the issue occurs whether or not I have the checkbox enabled for extension debuggig in about:debugging (not sure what this checkbox actually does).

**Comment by kspearrin** [comment] 2017-06-14 15:25
Ok, I can reproduce from the addons store now too. It's very weird because it doesn't always crash. Only for certain logins.

**Comment by kspearrin** [comment] 2017-06-14 20:43
Resolved in 1.13.5. I removed the third party range picker for a the native `input type="range"`

**Closed by kspearrin** 2017-06-14 20:43 UTC
