### ISSUE TITLE
Lock options timeout doesn't seem to work in Vivaldi 3.0

### ISSUE THREAD

**Issue by theCroh** [bitwarden/browser#1237] opened 2020-05-20 06:50 UTC
Lock options: 4 hours never seems to lock the extension in Vivaldi 3.0. I can reproduce this on both Windows 10 and Kubuntu 20.04. The extension is locked only after restarting the browser even when lock options is set to 4 hours. I havent tested other settings.

**Comment by envake** [comment] 2020-06-17 16:58
Can confirm Windows 10 Education 64bit and Arch Linux 64bit kernel 5.6.15-arch1-1 with Vivaldi v3.1.1929.34 on both systems. Bitwarden only locks when restarting the browser. The timeout options and the instant lock option don't work.

**Comment by Alphaprot** [comment] 2020-07-22 09:31
This is a bug in Vivaldi (cross-platform; e.g. the error appears on Windows machines as well), as you can read here:
https://github.com/bitwarden/browser/issues/1037#issuecomment-569672167

**Comment by BloodyIron** [comment] 2021-04-16 17:31
So this is still a thing then? 2 YEARS later?

**Comment by sso-bitwarden** [comment] 2021-12-01 23:58
I think we can close this, @eliykat . The issue is fixed. Vetted.

**Closed** 2021-12-02 01:25 UTC
