### ISSUE TITLE
Button menu is slow to pop up

### ISSUE THREAD

**Issue by jjdelc** [bitwarden/browser#142] opened 2017-04-28 23:19 UTC
Triggering the UI from the toolbar extension button takes close to 1s to pop over and get drawn.

**Comment by kspearrin** [comment] 2017-04-29 17:40
What OS and browser? I have not experienced this.

**Comment by jjdelc** [comment] 2017-04-29 19:05
Sorry, forgot to mention this is Firefox Nightly on Ubuntu 16.04.

**Comment by kspearrin** [comment] 2017-04-30 01:23
Interesting. I am on Firefox Windows and macOS and it is almost instant.

**Comment by jjdelc** [comment] 2017-04-30 04:20
I am seeing a very similar behavior on the containers extension, it uses a similar menu and toolbar button to launch its UI and is also slow to launch/draw. https://github.com/mozilla/testpilot-containers/issues/315

**Comment by kspearrin** [comment] 2017-04-30 19:16
If you are seeing the same problem in other extensions, it sounds like it may be an issue with Firefox.

**Comment by jjdelc** [comment] 2017-05-07 03:43
I reported the bug with Firefox, they said it was a per extension issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=1362638

**Comment by kspearrin** [comment] 2017-05-07 03:55
@jjdelc 

bitwarden does not load remote content when you open the popup (as suggested by the Firefox dev).

However, the popup itself is an AngularJS application, so surely there is probably some overhead due to that getting bootstrapped each time you open it. Maybe it is manifesting itself differently to users with lower-end machines. What are the specs on the machine you are using? Is it older? I have tested this on a desktop, 2011 macbook, and 2011 low-end laptop and the delay is hardly noticeable. We will absolutely never be as fast as the native Firefox menus though, since those are not web extensions.

**Comment by kspearrin** [comment] 2017-05-07 03:59
Also additional overhead is probably happening due to things that happen when you open the popup like rendering a full list of your decrypted logins. These are all things that have much more cost than printing a simple HTML menu with little to no logic like many extensions you may be comparing to.

**Comment by jjdelc** [comment] 2017-05-07 08:10
I experience it on my laptop (Thinkpad X1 carbon 2016) and desktop (17 3.6Ghs) both with 16Gb of ram, both running Nightly on Ubuntu 16.04.

I can't quite tell but is it possible that there is a sliding down animation on the menu as it shows? It is not super slow, but short of a second between clicking and final repaint. I can see the 4 stages, a fraction of second between click and anything showing up (maybe there's a slide down animation here that doesn't quite happen because sluggishness? I can't tell ), then another fraction the panel is all gray with a spinner, then I see the panel's top blue bar and finally my entries. And clicking it on and off shows the same process each time. 

The symptom is obvious when you put the extension button next to Firefox's burger menu, clicking several times (at a rate of on click every 0.5s) on the browser menu shows a level of responsiveness that does not happen on the extension, it will behave as if it is missing clicks or not even responding by the time the next click shows up. 

Once loaded, everything works smoothly inside. What you mention could be that the full UI is bootstrapping Angular each time the menu is triggered, in addition to what you mention that extensions cannot compare to native browser's speed.

**Comment by ple103** [comment] 2017-05-07 09:54
I swear it has something to do with Firefox and Linux ... The extension is fine for me on Windows 10 + Firefox, slow on my current Arch Linux + Firefox setup.

**Comment by kspearrin** [comment] 2017-05-08 17:49
@jjdelc There is no slide down animation that we have added to the menu.

**Comment by bellinom** [comment] 2017-05-09 14:54
I have this issue on Kali Linux with Firefox 53, it happened on all releases of 52 as well. I do not have it on Chrome on the same machine, or on Firefox on Mac OS.

**Comment by kspearrin** [comment] 2017-05-09 14:55
Sounds like this is isolated to Linux. I'll see if I can set up a VM to test.

**Comment by bellinom** [comment] 2017-05-22 21:42
As an update/correction, on Mac with Firefox it can be a little slow. Nowhere near as bad as on Linux though, which sometimes take 10 seconds+.

**Comment by SylwesterZarebski** [comment] 2017-05-25 08:56
I'm seeing some slowness when opening menu on Windows 7 x64. "Some" is between 0.5-1 second.
Hardware is Intel i7-6700, 16GB RAM and other one AMD FX-8320, 16GB RAM.

Other extensions has opening menus quicker, but also there are some differences. Fastest are simple menus (plain rectangle , eg. in Stylish extension), "new style" menus (with triangle pointing to icon) are fraction of second slower (eg. in uBlock Origin).

**Comment by SylwesterZarebski** [comment] 2017-05-25 10:00
Every icon click to open menu i'm noticing very heavy usage of isElementVisible, isElementViewable, getPageDetails in autofill.js. Could it be source of slowness?

**Comment by kspearrin** [comment] 2017-05-25 12:52
@SylwesterZarebski The autofill script is only for examining the content of the page you are viewing. It does not apply to opening the popup menu,

**Comment by SylwesterZarebski** [comment] 2017-05-25 12:56
Ok, thanks, can i somehow help to find cause?

**Comment by bellinom** [comment] 2017-05-25 13:17
I'm also willing to help out if there's something I can do.

**Comment by SylwesterZarebski** [comment] 2017-05-29 19:34
I'm also observing slight delay at opening popup on Vivaldi (Chromium engine) comparing to other extensions like uMatrix or HTTPS Everywhere - delay about 1/3 second (slight delay) compared to 1/10 second (almost instant).

**Comment by kspearrin** [comment] 2017-09-29 02:04
We made several improvements in recent versions. Can anyone provide an update using 1.17.x +?

**Comment by SylwesterZarebski** [comment] 2017-09-29 06:19
Just upgraded, do not see any difference. Will try again after browser restart.

**Comment by jjdelc** [comment] 2017-09-29 07:40
Just tried in Firefox beta in Linux and the situation is the same. I'll try another machine and try to get a video of it.

**Comment by jjdelc** [comment] 2017-09-29 20:35
Showing 1.17.1 in Firefox beta on Linux
https://vid.me/bLwQd

**Comment by ple103** [comment] 2017-09-29 22:21
It's pretty snappy for me now. Cheers!

**Comment by ple103** [comment] 2017-09-29 22:27
I've just tested with Firefox 55.0.3 (Stable) on Linux. While the bitwarden popup isn't as snappy as the rest of the UI, it does popup a lot quicker for me now. The popup time used to be ~3 seconds. Now it's half that time.

**Comment by SylwesterZarebski** [comment] 2017-09-30 18:43
I'm confirming behaviour spotted by @jjdelc.
Sometimes extension looks like it is loading long time to show rest of UI.

**Comment by reinob** [comment] 2017-10-03 18:12
I recently "converted" from LP to BitWarden. I've also noticed that it takes about 1 second to show the pop-up. This is with Chrome 61 under Linux. Core i3 (Sandy Bridge!) laptop, which is not really fast but should be fast enough.

**Comment by kspearrin** [comment] 2017-10-05 21:34
all:

I've spent the better part of today making various optimizations in hope that they may have some impact on this issue. If you get a moment, here is a custom dev build with these changes. I would appreciate if any of you that are experiencing this issue to give it a try and let me know if you notice any improvement.

Firefox
======

[dist-firefox.zip](https://github.com/bitwarden/browser/files/1360917/dist-firefox.zip)

- Uninstall existing bitwarden installation (if you have it installed)
- Extract the above zip somewhere
- Go to `about:debugging`
- Load temporary addon and navigate to the manifest.json file from the extracted build directory

Chrome
=====

[dist-other.zip](https://github.com/bitwarden/browser/files/1360919/dist-other.zip)

- Uninstall existing bitwarden installation (if you have it installed)
- Extract the above zip somewhere
- Go to `chome://extensions` and check the developer mode checkbox
- Load unpacked extension and navigate to the extracted directory

**Comment by reinob** [comment] 2017-10-06 19:30
Chrome gives an error saying "Failed to load extension from: ~/software/Bitwarden
Localisation used, but default_locale wasn't specified in the manifest."
If I look in the manifest file there is a  "default_locale": "en" line so I don't know why Chrome complains.
I will reinstall the standard extension. Maybe if I have time later in the weekend I'll try to figure out what the problem is (though Chrome is something I only know at the (l)user level..)
Thanks anyway, and I hope others can give some useful feedback!

**Comment by kspearrin** [comment] 2017-10-11 17:12
v1.19.0 just went live with these fixes. Please let me know if it has helped.

**Comment by reinob** [comment] 2017-10-11 18:03
Thanks!
The pop-up comes out a bit faster (not quite "instant" but it's an improvement).
Just for the record: I find it OK if there's some delay displaying the pop-up (better like this as with some error-prone lazy/async loading). I just reported here to note that it also affected Chrome.
Thanks again!

**Comment by SylwesterZarebski** [comment] 2017-10-11 19:33
Thanks, but i do not see any change (better or worse) in Firefox 55 (i had to go back to 55 because of other bugs which will be only fixed in 57 which is a no-no for me).

**Comment by kspearrin** [comment] 2018-04-18 19:02
Can you see if this is now resolved in version 1.26? There were significant improvements made throughout regarding performance.

**Comment by Jacalz** [comment] 2018-04-18 19:37
I must say that for me the extension poped up immediately before 1.26.0 but now it takes 1 second to load just like this issue when using the latest version 😕

That is when using Firefox on Solus (Gnu/Linux) but I will see if that same issue can be reproduced with Brave and Chrome 😅

**Comment by SylwesterZarebski** [comment] 2018-04-18 20:08
Negative, it is partly similar (1) and slower (2) than before.
1. Wait about 0.5s before opening popup - this is similar as before,
2. Sometimes it shows 1s and longer spinner (not always) - this was not observable before.

Firefox 55 on Windows 7.

**Comment by jjdelc** [comment] 2018-04-18 20:26
I was just looking at this in 1.25 and I was thinking "hey it's quite alright now", just updated to 1.26 (using Nightly on Linux 61a1 20180418) and it the popup takes longer than the version before :-/

**Comment by kspearrin** [comment] 2018-04-18 20:30
I still can't seem to reproduce the problem. I have an Ubuntu 16 VM running with 4gb of RAM, Firefox 59.0.2, and a vault with ~500 items in it. Clicking the popup is nearly instant. 😕

**Comment by SylwesterZarebski** [comment] 2018-04-19 07:59
See below wideo which shows clicks and reaction:
![ezgif-4-26c221bd6e](https://user-images.githubusercontent.com/1755531/38978663-9089fa70-43a7-11e8-80c4-edc37451060b.gif)

**Comment by thunfischbrot** [comment] 2018-07-11 08:55
This is about the same speed as I am getting on latest Firefox 61.0 (64-Bit) on Windows 7.

**Comment by kspearrin** [comment] 2018-07-27 14:20
v1.28 any better?

**Comment by SylwesterZarebski** [comment] 2018-08-04 14:05
Looks like wait spinner shows way less often and when occur it lasts shorter. Thanks!

**Closed** 2018-08-04 14:11 UTC
