### ISSUE TITLE
Please reopen Issue #982

### ISSUE THREAD

**Issue by mathsen** [bitwarden/browser#1068] opened 2019-11-25 08:38 UTC
[Issue #982](https://github.com/bitwarden/browser/issues/982#issuecomment-558046159) still affects many bitwarden users, including me (see comments in the linked issue).
Please reopen it.

**Comment by kspearrin** [comment] 2019-11-25 13:22
The issue is resolved in an upcoming release. There is no more dev work to be completed or discussed. The fix just needs to be released.

**Closed by kspearrin** 2019-11-25 13:22 UTC
