### ISSUE TITLE
Vivalidi, Linux Mint - Automatic Lock doesn't appear to work

### ISSUE THREAD

**Issue by Zeustopher** [bitwarden/browser#1037] opened 2019-10-11 20:52 UTC
OS: `Linux Mint 19.2 Cinnamon`
Browser: `Vivaldi 2.7.1628.30`
Plugin Version: `1.41.0`

Installed plugin from https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb linked on the official Bitwarden site: https://bitwarden.com/#download

----------------

I have tried several different sets of settings for Bitwarden's Auto-lock settings and none of them appear to work properly on `Vivaldi`.

First I tried setting Settings --> Lock Options to `On System Lock` but when I would lock my screen and later come back and unlock it, the vault would still be unlocked.

I then switched to using `15 Minutes` but it never locked. Same with `1 Minute`. Not even `Immediately` locks automatically. As a sanity check I can do the `Lock Now` option and it does lock the vault.

--------------

On the same machine I installed the Firefox plugin and it will lock automatically in all of the above mentioned scenarios (except for `On System Lock` as that isn't an option in Firefox) so this appears to be related only to Vivaldi.

**Comment by m0ll3art** [comment] 2019-10-18 11:48
same here with Firefox Dev 71b1 (plugin(1.41.0) on os x Mojave 10.14.6 timed Locking seems not to work, independently of the timer being set.  On windows 10 all on latest versions seems to work fine

**Comment by Zeustopher** [comment] 2019-11-26 15:38
Is there anything else I can provide that can help this start moving towards a fix? I've been trying to get in the habit of locking the vault manually once I'm done using it, but I just had an instance where I forgot and it was unlocked for several hours before I caught it. Even though my computer was locked, it still makes me uncomfortable.

**Comment by Zeustopher** [comment] 2019-11-26 16:41
This may be related to https://github.com/bitwarden/browser/issues/854 since it seems to follow what other users have reported in the past.

**Comment by ralhei** [comment] 2019-12-13 11:28
I've just confirmend this on #854, auto-locking also fails for me on Mac OS with Firefox 71.0 and Bitwarden 1.41.0

**Comment by PinkDev1** [comment] 2019-12-29 04:20
Honestly, I blame it on Vivaldi. It's overall a very abandoned browser, with a small user base. And so far it has brought mostly just problems to the Bitwarden project (see https://github.com/bitwarden/browser/issues?utf8=%E2%9C%93&q=is:issue+vivaldi)
If you can, I strongly suggest you ditch vivaldi and switch to Firefox, Brave or Chrome.

**Comment by Zeustopher** [comment] 2019-12-29 04:33
> It's overall a very abandoned browser, with a small user base.

Why do you say that it is abandoned? I see relatively frequent updates, including even work on releasing a version for Android. I won't argue about it being a small-ish userbase because that's probably true.

--------

> And so far it has brought mostly just problems to the Bitwarden project (see https://github.com/bitwarden/browser/issues?utf8=%E2%9C%93&q=is:issue+vivaldi)

That's not really a fair way to look at it because if I do the same search for "Firefox" instead of "Vivaldi" https://github.com/bitwarden/browser/issues?utf8=%E2%9C%93&q=is:issue+firefox I get 15 pages of issues instead of the 2 pages your search returns.

-------

Based on other replies in this thread which are on different platforms and different browsers it is not an isolated incident and isn't fair to just "blame it on Vivaldi". There is something going on here with Bitwarden somewhere.

**Comment by GabrielDuarteM** [comment] 2019-12-29 23:02
I'm also having this problem, is there any solution yet? As someone who leaves all passwords there, I usually leave it to auto-lock after 1 minute to avoid unwanted people looking into my passwords, and I see this not working as a quite high severity bug, as it leaves the vault unlocked for anyone to check, even though it is configured not to do that. Can we get some sort of prioritization here? 

I also have a premium membership, not sure if that makes any difference regarding the prioritization.
 
OS: MacOS 10.15.2 (19C57)
Browser: Vivaldi 2.10.1745.23
Plugin Version: 1.41.0

**Comment by GabrielDuarteM** [comment] 2019-12-30 00:04
After some quick debugging, it looks like [this line](https://github.com/bitwarden/jslib/blob/98c7dc162628129d0bddbf20359d389dacb661d3/src/services/lock.service.ts#L46) is the culprit. Looks like `checkLock` is called periodically, and when it is called, it calls for [isViewOpen](https://github.com/bitwarden/browser/blob/master/src/services/browserPlatformUtils.service.ts#L93), then [isPopupOpen](https://github.com/bitwarden/browser/blob/594ff3d6ec88abad24bb6570b721736ae80dce53/src/browser/browserApi.ts#L118), then, the `if (BrowserApi.isChromeApi)` returns `true`, so it goes inside it, and then `chrome.extension.getViews({ type: 'popup' })` returns one item, regardless if the popup is open or not (it returns apparently the same thing). Because of that, the promise is resolved to true, and `isPopupOpen` is then always returning true, reason why the auto-locker thinks that the popup is open and then ends up not doing anything.

Now I'm not sure why the `getViews` would always return, but anyway, I hope this helps!

**Comment by kspearrin** [comment] 2019-12-30 13:00
@GabrielDuarteM Thanks for the debug. I confirmed the same thing. This is a bug in Vivaldi. `chrome.extension.getViews({ type: 'popup' })` is suppose to return an empty array if the popup window is not open. I have submitted a bug report to them.

Closing this since it is an upsteam issue.

**Closed** 2019-12-30 13:00 UTC
Labels: bug

**Comment by joeynguyen** [comment] 2019-12-30 16:43
@kspearrin, can you link the bug ticket you submitted to the Vivaldi team?  I think some of us would like to follow it to get updates and know when it's fixed. Thanks!

**Comment by kspearrin** [comment] 2019-12-30 16:52
@joeynguyen It isn't public. I just submitted this form. https://vivaldi.com/bugreport/

**Comment by rybick** [comment] 2021-07-02 08:20
Hi @kspearrin do you know if Vivaldi team addressed your reported issue in any way?

**Comment by cschoenle** [comment] 2021-08-23 14:53
@rybick 

I think it will be fixed in one of the upcoming updates of Vivaldi, it is already (supposedly) fixed in the latest snapshot:
https://vivaldi.com/blog/desktop/translate-selected-text-vivaldi-browser-snapshot-2392-3/

"
[Extensions] chrome.extension.getViews({ type: ‘popup’ }) is suppose to return an empty array if the popup window is not open (VB-81714)
"
