### ISSUE TITLE
Password Autofill Doesn't Work on 

### ISSUE THREAD

**Issue by hmenorjr** [bitwarden/browser#1383] opened 2020-09-11 05:31 UTC
## Describe the Bug

When clicking the username and password saved for _myjobstreet.jobstreet.com.ph_ it throws the following error:

> We're sorry, either the Login ID or Password was incorrect. Please try again.
If you have forgotten your Login ID or Password, retrieve it here.

But when I delete the password and copy+paste the password from the browser extension. It worked.

## Steps To Reproduce

1. Go to [myjobstreet.jobstreet.com.ph](https://myjobstreet.jobstreet.com.ph/home/login.php?site=&language_code=3)
2. Click on the `Bitwarden` icon on Safari
3. Scroll down to _Jobstreet_ entry
4. Click on `Login` button

## Expected Result

The dashboard for my profile will display

## Actual Result

Error message:
> We're sorry, either the Login ID or Password was incorrect. Please try again.
If you have forgotten your Login ID or Password, retrieve it here.

## Screenshots or Videos

<img width="1370" alt="Screen Shot 2020-09-11 at 1 26 09 PM" src="https://user-images.githubusercontent.com/15950561/92866698-6ea3eb80-f432-11ea-80fe-cc72bf1a0881.png">

## Environment

- Operating system: Mac OS Catalina 10.15.6
- Browser: Safari v13.1.2
- Build Version (go to "Settings" → "About" in the app): 1.45.0

**Comment by Greenderella** [comment] 2020-09-11 10:24
I'm unable to reproduce this issue with the same setup (Catalina 10.15.6 and Safari v13.1.2), login it's successful with both autofill on page load and shortcut autofill (https://drive.google.com/file/d/1XQ-J-n4odbQBwXFoXoFQ7XvIOIgVSLdf/view?usp=sharing).

Will you first try uninstalling the extension, removing any leftover data, resetting your device and re-installing? Does this issue still persist?
Removal of the leftover data is important. New installation may hold on to old installation files and cause the same issues.
Guide to the leftover data: https://help.bitwarden.com/article/where-is-data-stored-computer/

**Comment by addisonbeck** [comment] 2020-09-30 15:54
I'm going to close this one for now, @hmenorjr , but feel free to reopen if the issue is persisting after trying the above fix.

**Closed by addisonbeck** 2020-09-30 15:54 UTC
