### ISSUE TITLE
Base Domain matching not respecting TLD differences

### ISSUE THREAD

**Issue by klogg416** [bitwarden/browser#2490] opened 2022-04-03 15:12 UTC
### Steps To Reproduce

1. Create separate accounts for `amazon.com` and `amazon.ca`.
2. Set `amazon.com` URI to `https://www.amazon.com/`, and match type to Base Domain.
3. Set `amazon.ca` URI to `https://www.amazon.ca/`, and match type to Base Domain.
4. Visit either domain and the browser plugin offers both accounts as a match instead of the appropriate TLD.

### Expected Result

Browser plugin should differentiate between TLDs and offer the correct account only for autofill.

As described here (https://bitwarden.com/help/uri-match-detection/):
> Selecting Base domain will prompt Bitwarden to offer auto-fill when the top-level domain and second-level domain of the URI match the detected resource.

<img width="807" alt="image" src="https://user-images.githubusercontent.com/7346736/161434319-40ee1739-bd61-47cf-9ad4-a97a3f5317da.png">

### Actual Result

Visit either domain and the browser plugin offers **both** accounts as a match instead of the appropriate TLD.

Switching to Host or Starts With match type works, but by design fails when there are subdomains, etc.

### Screenshots or Videos

`.ca` match detection.
<img width="366" alt="image" src="https://user-images.githubusercontent.com/7346736/161434431-c81c23e6-c02f-4834-a654-22adc51c3573.png">

![image](https://user-images.githubusercontent.com/7346736/161434589-b5c6785a-52d5-4018-a883-5a8dd1629b2a.png)

### Operating System

macOS

### Operating System Version

12.3.1

### Web Browser

Safari, Firefox

### Browser Version

Firefox 98.0.2, Safari 15.4

### Build Version

1.57.0

**Comment by djsmith85** [comment] 2022-04-04 09:14
Hi @klogg416 thank you for your report. 

In the example you have given (Amazon) this is expected behavior. If I have an account on `amazon.com` I can also log into `amazon.ca` with the same set of credentials. 

We call these [equivalent domains](https://github.com/selfisekai/server/blob/a964dfd774c7134da3889fc636675f75dcf32cba/src/Core/Utilities/StaticStore.cs#L35). As one account can be used to log-in to several sites operated by the same provider.

If you'd like differentiate between `amazon.com` and `amazon.ca`, because you have two separate accounts (different email) then you can change the match detection to exact on both entries. Then you'll only get a match for the exact site.

If you have other sites, that are not considered equivalent domains, but show the behavior you described initially then that is likely a bug. 

I'm closing this for now, but feel free to re-open if you have other examples.

**Closed by djsmith85** 2022-04-04 09:14 UTC
Labels: bug

**Comment by klogg416** [comment] 2022-04-04 13:25
Thanks for explaining why it wasn't working as described in the documentation, makes sense.
