### ISSUE TITLE
[Bug] Bitwarden browser addon keeps resizing

### ISSUE THREAD

**Issue by t3dium** [bitwarden/browser#2418] opened 2022-02-27 17:00 UTC
### Steps To Reproduce

Clicking on the browser addon

### Expected Result

For the popup to open in its normal size

### Actual Result

When first clicking the browser addon it opens in a smaller state: https://imgur.com/a/Dyy1DjB
Then pressing it again a couple times opens it like this: https://imgur.com/a/mdxpAlW

### Additional Context

This issue only occurred after updating the addon

### Operating System

Windows, Linux

### Web Browser

Firefox

### Browser Version

latest

### Build Version

latest

**Comment by Snaddyvitch-Dispenser** [comment] 2022-02-27 18:23
Also experiencing

**Comment by EmSixTeen** [comment] 2022-02-28 19:55
Even if this is a bug where the window gets sized randomly, there should still be a user preferences setting for the height of this box.

**Comment by user2852** [comment] 2022-02-28 20:30
I also have this happening, changing the theme "fixes" it temporarily for the current tab:

![Screenshot 2022-02-23 185529](https://user-images.githubusercontent.com/77663133/156053417-41843747-f527-4f3b-900e-82aada432ea8.jpg)

After changing the theme, it returns to the previous normal size, but if you open a new tab it is small again:

![Screenshot 2022-02-23 185628](https://user-images.githubusercontent.com/77663133/156053502-70dae9e3-7cb6-4d00-b08e-3c865d126ee9.jpg)

**Comment by my-gitusr** [comment] 2022-03-01 05:27
Same issue, but mine never returns to normal size until I close and reopen my browser, which doesn't always work. (I'm on Windows 11 with Firefox 97.0.1)

**Comment by Xathros1** [comment] 2022-03-01 23:59
got the same issue in firefox 
not on chromium

**Comment by t3dium** [comment] 2022-03-07 08:56
issue still exists

**Comment by djsmith85** [comment] 2022-03-07 10:24
As this seems to only be affecting Firefox, I'm closing this as a duplicate of https://github.com/bitwarden/browser/issues/1451.

One of our users commented there, that it likely has to do with the `resistFingerprinting` setting which intentionally changes the reported screen size.

**Closed by djsmith85** 2022-03-07 10:24 UTC
Labels: bug

**Comment by user2852** [comment] 2022-03-07 10:47
Can confirm. I just reset `resistfingerprinting` to false and it opens normally. That is unfortunate, guess I'll have to get used to the smaller size.
