### ISSUE TITLE
Unable to add attachments (Firefox)

### ISSUE THREAD

**Issue by neoxk** [bitwarden/browser#1679] opened 2021-03-10 10:28 UTC
## Describe the Bug

When trying to add attachments to an entry in bitwarden browser extension it opens up a prompt to select a file, which is expected. But the problem is that the browser extension closes and therefore I cannot add an attachment through the browser extension.

## Steps To Reproduce

1. Go to bitwarden extension
2. Click on the entry in your vault
3. Click 'edit'
3. Click 'attachments'
4. Click on 'browse'

## Expected Result

After clicking 'browse', the browser extension should open the file explorer prompt and wait for me to pick a file then add it to the entry.

## Actual Result

After clicking 'browse', the browser extension opens a file explorer prompt as expected, but right after the prompt opens, the browser extension closes itself, therefore quitting the 'edit' window.

## Environment

- Operating system: Windows 10
- Browser: Firefox 86.0
- Build Version 86.0

## Additional Context

I have recently switched over from Chrome to Firefox browser. On chrome I have been able to add attachments without problem. So it seems the problem appears only on Firefox and not on Chrome (I don't have experience with other browsers).

**Comment by cscharf** [comment] 2021-03-10 15:18
Hi there and thanks for submitting this. This is a known issue with Firefox where the file dialog doesn't keep the browser extension open and in-context, unfortunately we don't have any control over it, however there is an open issue with Mozilla for the issue (just not yet resolved). With that, this PR will be going out with our release (in < 1 week's time) that will pop out the extension for FF users so you don't lose context while attaching/uploading a file: https://github.com/bitwarden/browser/pull/1532.

Closing as a duplicate of #1354

**Closed by cscharf** 2021-03-10 15:18 UTC
Labels: duplicate
