### ISSUE TITLE
Says I'm not an active premium member when on a organisation's membership

### ISSUE THREAD

**Issue by joveice** [bitwarden/browser#1664] opened 2021-03-07 12:53 UTC
## Describe the Bug

The browser extension says "You are not currently a premium member." while in an organisation that has premium

## Steps To Reproduce

1. Go to Settings
2. Scroll down to Account
3. Click on the flashy blue button

## Expected Result

Gray membership button which does not steal focus
Information about my subscription

## Actual Result

A flashy blue ad like button
Sub page tells me I don't have an active subscription.

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/14098624/110240379-ee2af700-7f4b-11eb-88c9-9b61190f46af.png)
![image](https://user-images.githubusercontent.com/14098624/110240401-069b1180-7f4c-11eb-9578-2cbb9cee36c5.png)
![image](https://user-images.githubusercontent.com/14098624/110240415-187cb480-7f4c-11eb-935f-d5bd2d962ffa.png)

## Environment

- Operating system: Fedora 33
- Browser: Firefox 86
- Build Version (go to "Settings" → "About" in the app): 1.48.1

**Comment by kendratodd** [comment] 2021-06-04 21:21
Hi @joveice! Good news - this issue was fixed in https://github.com/bitwarden/browser/pull/1737 & https://github.com/bitwarden/jslib/pull/311. This update went out in the latest release (1.50.0) and should now be displaying correctly. 

I'm closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis. Thank you!

**Closed by kendratodd** 2021-06-04 21:21 UTC

**Comment by eliykat** [comment] 2022-02-14 01:24
@howar31 that issue should be fixed with 1.56.1. See the recent thread here: https://github.com/bitwarden/browser/issues/2330.

Please update your extension and try again.
