### ISSUE TITLE
Slow create/edit/view custom fields using chrome extension

### ISSUE THREAD

**Issue by chinkung** [bitwarden/browser#1327] opened 2020-07-12 05:14 UTC
## Describe the Bug
Create/View/Edit custom field in Login record lagging or hung sometime

## Steps To Reproduce

1. Go to 'LOGINS' record
2. Try to create/edit new custom fields
3. Try to view existing custom fields

## Expected Result
Custom field should be created/edited/viewed smoothly without any lag

## Actual Result
A log of lagging when create/edit/view

## Screenshots or Videos
[bitwarden_chrome_extension_custom_fields_lag.zip](https://github.com/bitwarden/browser/files/4908036/bitwarden_chrome_extension_custom_fields_lag.zip)

## Environment

- Operating system: Mac OS Mojave 10.14.6
- Browser: Brave Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
- Build Version (go to "Settings" → "About" in the app): 1.45.0

**Comment by clayadams5226** [comment] 2020-07-22 06:29
@chinkung if you go into your Chrome settings > Advanced and disable "Use hardware acceleration when available" does the issue persist? Does this happen all the time or after you've been using the browser for a while?

**Comment by t3h-n00b** [comment] 2020-07-29 07:46
I have a similar issue - only occurs on May (I am using Chrome, current version for everything).

I disabled HW Acceleration as per above, and it makes the problem worse (everything becomes laggy in the extension then). I've also removed/re-installed Chrome to no avail.

Noticeable for me on clicking 'view' on certain fields (such as Credit Card Security Number), editing certain fields (such as URL fields in existing entries).

**Comment by nperez0111** [comment] 2020-08-06 16:52
I've only been able to narrow it down to when the extension is open as part of chrome's extension bar (as opposed to docked separately).
When I try to profile it using the chrome devtools for some reason during profiling it works just fine but when the profiling stops it resumes being laggy. It seems like the view does not rerender when keypresses happen but if I click or even move my scrollbar to a certain position the cursor begins to blink again and it will type normally.

I hope this is helpful somehow.

**Comment by t3h-n00b** [comment] 2020-08-07 02:47
@nperez0111 Just tried disabling the extensions bar (chrome://flags/#extensions-toolbar-menu to Disabled and relaunching); doesn't seem to fix it.
Even removing the icon off the bar completely, then having to access it via the settings menu doesn't appear to speed things up.

**Comment by chinkung** [comment] 2020-09-11 12:39
@clayadams5226 Disable "Use hardware acceleration when available" does not help, do you have solution yet ?

**Comment by clayadams5226** [comment] 2020-12-17 04:53
@chinkung is this still an issue for you? Are you able to test it in a newer OS?

**Comment by clayadams5226** [comment] 2020-12-22 03:36
Hi @chinkung  it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by clayadams5226** 2020-12-22 03:36 UTC

**Comment by spronkey** [comment] 2021-01-13 23:03
I've also been experiencing similar issues. When I open extension from the extensions bar, everything is really laggy. Even just rendering the initial screen takes a while (something obscures the top 100px or so for several seconds), and entering text is unbearably slow in some fields such as CC number. 

Popping it out into a window solves these problems immedaitely and it's fast again. Currently running on Chrome (latest v) on MacOS 10.14.6 as well. Chrome on Win10 seems to be fine.

**Comment by pcullum** [comment] 2021-05-11 14:10
@clayadams5226  This isn't just a problem with custom fields. It also affects the notes field in secure notes.
@spronkey , you are right... this doesn't seem to be a problem when it is "popped out" to a window.

**Comment by garethbradley** [comment] 2021-05-28 08:21
+1 Same issue. Confirm popout is OK, but otherwise, painfully slow

**Comment by BTL-UG** [comment] 2021-07-12 19:38
For me the problem was caused by the chrome window being on a second screen (external screen connected to a macbook pro). Moving the window to the main screen instantly solved the issues. Obviously only a workaround, not a solution.

**Comment by eliykat** [comment] 2021-07-12 22:04
This is the same issue as #1854, please direct any discussion over there.
