### ISSUE TITLE
Lock icon displaying even when unlocked

### ISSUE THREAD

**Issue by henrytoone** [bitwarden/browser#1432] opened 2020-10-21 09:22 UTC
## Describe the Bug

When unlocking the Bitwarden chrome extension with a login page on the screen. The vault unlocks and it can be used normally but the red lock symbol remains on the Bitwarden icon.

## Steps To Reproduce

1. Go on a website that prompts a login page
2. Click on the locked Bitwarden extension
3. Type in master password to unlock it

## Expected Result

The number of logins for that page shows up on the Bitwarden extension icon

## Actual Result

The lock remains on the Bitwarden extension icon
The amount of logins for that page displays on top of the red lock icon but the lock icon is still visible. (third screenshot)

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/51138024/96699372-168fcb80-1386-11eb-94af-2e652909177b.png)

![image](https://user-images.githubusercontent.com/51138024/96699647-6bcbdd00-1386-11eb-987f-7a6c78dbfac3.png)

![image](https://user-images.githubusercontent.com/51138024/96699917-b9e0e080-1386-11eb-9a44-6cafacb911b7.png)

## Environment

- Operating system: Windows 10
- Browser: Chrome 86.0.4240.75
- Build Version: 1.46.2

## Additional Context

I'm using my laptop screen and an external monitor but I don't think that affects whether the issue occurs or not.

**Comment by Greenderella** [comment] 2020-10-21 15:53
Hi @henrytoone,

Will you first try uninstalling the extension, removing any leftover data, resetting your device and re-installing? Does this issue still persist?
Removal of the leftover data is important. New installation may hold on to old installation files and cause the same issues.
Guide to the leftover data: https://help.bitwarden.com/article/where-is-data-stored-computer/

Let us know if that solves the issue.

**Comment by clayadams5226** [comment] 2020-12-31 04:39
Hi @henrytoone , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by clayadams5226** 2020-12-31 04:39 UTC

**Comment by mmifsud** [comment] 2021-09-15 05:25
Hi,

I have this problem too, but after removing extension from browser (Edge (Chromium)), removed remaining files from AppData\Local\Microsoft\Edge\User Data, and re-installing app, now it won't log in. I enter username and password, hit enter, the login window closes, but Bitwarden remains logged out without any error or other notification.

**Comment by eliykat** [comment] 2021-09-15 05:40
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by oliveconstant** [comment] 2022-04-05 08:30
Happens to me on Firefox 98.0 (Fedora 35/GNOME). I noticed this after setting `Vault Timeout` to `Never`.

**Comment by b-trav** [comment] 2022-04-05 19:25
I still have this issue in 1.57.0 using Chrome in Ubuntu 20.04. @eliykat  why is this issue still closed? Can you please re-open this issue, or do I need to start a new issue?

**Comment by djsmith85** [comment] 2022-04-06 16:40
Hi @oliveconstant and @b-trav this issue was closed as the issue seemed resolved due to inactivity.

A more recent report is https://github.com/bitwarden/browser/issues/2323, please add any details there.

Attached to that is also a Pull Request which I'm hoping will also address the issue you are experiencing.
