### ISSUE TITLE
Bitwarden extension is locked but the vault is accessible via context menu: 

### ISSUE THREAD

**Issue by tharrisone** [bitwarden/browser#534] opened 2018-03-03 23:12 UTC
Browser: Chromium

When the vault is locked manually or by a timeout you can still autofill logins via the context menu. If you restart the browser and try to do that it says the vault is locked. In this picture the vault is locked:

![screenshot_2018-03-03_17-11-40](https://user-images.githubusercontent.com/5998467/36940297-f7fcc78a-1f05-11e8-9357-cd53cc4e78c1.png)

**Comment by kspearrin** [comment] 2018-03-03 23:15
But your vault isn't locked ... I'm looking at an unlocked icon in the top right....?

**Comment by tharrisone** [comment] 2018-03-03 23:17
When i open it, it asks for a master password.

**Comment by RixzZ** [comment] 2018-03-03 23:56
For me, when the vault is locked a red lock appears on the BW icon:
![vault locked](https://user-images.githubusercontent.com/1339272/36940616-b4708682-1f46-11e8-833b-6cca695bb700.png)

In that state, I can't fill entries using the right-click menu either. Maybe the problem is that your vault is not locking properly.

**Comment by kspearrin** [comment] 2018-03-04 03:53
Should be fixed for next version. Thanks.

**Closed by kspearrin** 2018-03-04 03:53 UTC
