### ISSUE TITLE
Banner flashing when prompting to remember a password

### ISSUE THREAD

**Issue by turkeyphant** [bitwarden/browser#1613] opened 2021-02-17 13:54 UTC
## Describe the Bug

After logging in with new information, the banner flashes on and off over and over.

## Steps To Reproduce

1. Enter unsaved credentials on a website.

## Expected Result

The banner should appear once and remain there.

## Actual Result

Flashes/flickers.

## Screenshots or Videos

https://user-images.githubusercontent.com/8129583/108213971-80976200-7127-11eb-83b0-3248aafbad6f.mp4

## Environment

- Operating system: Windows 10
- Browser: Chrome
- Build Version  88.0.4324.104 (has happened on all previous versions too.

**Comment by eliykat** [comment] 2021-02-17 20:14
Thanks @turkeyphant. I'm going to close this as a duplicate of #1243, but it would help if you could post some more information in that thread. What site(s) are you experiencing this issue on? Do you need to log in successfully for the bar to blink?

**Closed by eliykat** 2021-02-17 20:14 UTC
