### ISSUE TITLE
Other language (Malayalam) characters appear in some places when browser language is set to English (India) on MS Edge Chromium

### ISSUE THREAD

**Issue by rowschank** [bitwarden/browser#1440] opened 2020-10-25 15:17 UTC
## Describe the Bug

When the browser language is set to English (India) on MS Edge (Chromium) on Windows 10, some text is shown in another Indian language, Malayalam, even though that language is neither active on the browser nor system level. 

## Steps To Reproduce

1. Open MS Edge (Chromium)  
2. Set display language to English (India)
3. Open the Bitwarden Extension and browse through the settings and other areas to find random Malayalam words.   

## Expected Result

Everything should be in English has has been before. 

## Actual Result

Some words are in Malayalam instead of English

## Screenshots or Videos

1. [Tab page, when no password has been saved](https://i.imgur.com/lPCodIw.png)  
2. [Settings Page 1](https://i.imgur.com/W6Yk0jc.png)  
3. [Settings Page 2](https://i.imgur.com/h8n2Qe4.png)

## Environment

- Operating system: Windows 10 Pro 2004
- Browser: Microsoft Edge 86.0.622.51
- Build Version (go to "Settings" → "About" in the app): 1.46.2

## Additional Context

This issue is not present when the language of the browser is set to something else (e.g. German).

**Comment by Sourav-Rudra** [comment] 2021-01-07 07:27
I am also facing the same issue, i recently got Bitwarden and i have seen Malayalam sprinkled randomly here and there.

**Comment by tgreer-bw** [comment] 2021-01-07 14:26
There were a couple of strings that were accidentally translated - I've adjusted them and it should be fixed upon the next client release.

**Comment by djsmith85** [comment] 2021-08-15 14:34
Hi @rowschank closing this as it should be resolved in a release after your post, as @tgreer-bw mentioned. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2021-08-15 14:34 UTC

**Comment by rowschank** [comment] 2021-09-24 00:14
Yes, this is fixed, thanks. :-)
