### ISSUE TITLE
bitwarden not working in private windows on firefox

### ISSUE THREAD

**Issue by shawn-j** [bitwarden/browser#911] opened 2019-04-03 19:43 UTC
just got bitwarden a week ago.  it's working great, though a few days ago it stopped working in private windows on ff.  i right click, and all the login options are there.  but they dont' autofill. worked just fine a few days ago.  am i missing something?  thanks in advance

**Comment by kspearrin** [comment] 2019-04-03 19:49
If you create a new firefox user profile, does it work there?

**Comment by shawn-j** [comment] 2019-04-03 23:45
> 
> 
> If you create a new firefox user profile, does it work there?

just tried it- yes, but i have to do it twice.   so i right click, then click on bitwarden>acct, and it does nothing.  then i do that again, and it autofills like it should.

**Comment by devurandom** [comment] 2020-12-02 08:36
This seems to have duplicates in #1444 and #1050.

**Comment by cscharf** [comment] 2020-12-28 21:00
This is a duplicate of #136

**Closed by cscharf** 2020-12-28 21:00 UTC
Labels: duplicate
