### ISSUE TITLE
bitwarden doesn't ask me to save a new profile

### ISSUE THREAD

**Issue by Primokorn** [bitwarden/browser#186] opened 2017-07-07 06:27 UTC
Hi,
I've just created an account on https://www.wunderground.com
I didn't have the notification at the top of the screen to suggest me to save the credentials for this website so I have to do it manually.

This is not the first time that I have to deal with it.
Thank you.

**Comment by streetwolf** [comment] 2017-07-15 16:20
I've seen this also.  In fact I've created new logins in the past few weeks and haven't seen a message to save my login info.  I have seen it a few times in the past.

I have to manually set up a new login.  I'm on Fx56 Nightly btw.

**Comment by kspearrin** [comment] 2017-07-15 17:45
@streetwolf if you are seeing it happen that often that is probably because your vault is locked. We can't offer to save the login while your vault is locked.

**Comment by streetwolf** [comment] 2017-07-15 19:09
How do I tell if my vault is locked?  I have the lock option set to never lock.  Is that the option that controls locking the vault?

**Comment by kspearrin** [comment] 2017-07-17 01:31
If you are using never lock then the vault would not be locked. Maybe something with nightly causes it to break.

We are hoping to get our next version out in the next week or two.

**Comment by JourneyOver** [comment] 2017-08-03 17:19
This is happening on chrome as well so it's not only happening on firefox, just installed BW and have been having to manually setup new login information on every single site I use because nothing comes up to suggest saving login credentials at all.

**Comment by kspearrin** [comment] 2017-08-03 17:46
@JourneyOver It doesn't ever work or only on some sites?

**Comment by JourneyOver** [comment] 2017-08-03 21:35
it eventually worked for a small number of sites (google/reddit/twitter and a couple others) but for most I had to do manually, I eventually just gave up for the time being and went back to using lastpass since I've been using it for years without any trouble. Might try BW again at some point once things feel a bit more fleshed out and working since I do like the whole open source thing this has going on vs something like lastpass.

**Comment by jeroen7s** [comment] 2017-08-04 06:53
you could show a notification to unlock the db and then save the site when BW is locked, instead of showing nothing?

**Comment by kspearrin** [comment] 2017-08-04 12:18
@jeroen7s The problem is that when the vault is locked it cannot be read from either, which means we don't know if you already have the login stored or not. We would have to prompt you for every login, which would be annoying.

**Comment by jeroen7s** [comment] 2017-08-05 07:12
maybe you could prompt only when you're creating a new account? shouldn't be too hard since almost every form you fill in has 2 password fields, to confirm you have the correct password typed in. you could detect that and then ask to save even if your database is locked? 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jeroen7s** [comment] 2017-08-05 07:16
also i really don't think that asking to unlock bitwarden at every login is an issue, i would prefer to have that option available as a setting. rather than not having my password saved

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kspearrin** [comment] 2017-08-08 13:39
@Primokorn I just tested this on weather underground and it worked fine for me??

**Comment by Primokorn** [comment] 2017-08-08 13:48
It's working too. Could it be related to a recent update of the Firefox addon?
Anyway please keep this issue opened for now. I'm pretty sure I'll find other websites.

I don't know if it's a planned feature or a bug but I don't think that we have the notificaiton when changing our password from a website.
Example:
If I change my password in the Settings of Github website I shoud have a notification from bitwarden asking me to update the existing credentials of Github.

**Comment by kspearrin** [comment] 2017-08-08 13:49
@Primokorn Yes, that feature is not yet implemented.

**Comment by kspearrin** [comment] 2017-08-08 15:13
@Primokorn The most recent update didn't address any of these issues so I am not sure why it was not working for you before.

**Comment by jeroen7s** [comment] 2017-08-10 14:45
@kspearrin could you implement a checkbox so we can choose weather or not Bitwarden will prompt to unlock on login (to save the password in BW)

**Comment by kspearrin** [comment] 2017-08-12 17:11
@Primokorn I've made several enhancements to catch edge cases that were not accounted for before. This should hopefully improve things with detecting login/registration form submissions in the next release.

**Comment by kspearrin** [comment] 2017-08-12 17:12
Commit: https://github.com/bitwarden/browser/commit/e1512092618986b440950f44910e2c143f892e23

**Comment by Primokorn** [comment] 2017-08-14 13:31
@kspearrin Thanks. I didn't registrer in a new website but I keep this issue in mind.

**Comment by Primokorn** [comment] 2017-08-23 06:52
@kspearrin please try with this website. I have no notification on my end.
https://www.appbrain.com/signup?li_cont=https%3A%2F%2Fwww.appbrain.com%2F

**Comment by kspearrin** [comment] 2017-08-23 12:00
@Primokorn This is still one of the few cases I am unsure how to handle. The login form does not follow HTML standards by placing a submit button inside the actual form.

![image](https://user-images.githubusercontent.com/1190944/29614666-0d9cd9dc-87d9-11e7-9a3b-bea50b33ea3a.png)

Therefore I don't really know that the button being clicked is for that login form. Of course there may be some way for us to visually determine that, but a solution that works for all cases I am still unsure of.

**Comment by jeroen7s** [comment] 2017-08-23 12:14
wow that's incredibly weird behavior from the site, so the submit button on the form is hidden but they use a custom input button to trigger the submit button inside the form? like wtf?

**Comment by kspearrin** [comment] 2017-08-23 12:15
@jeroen7s Exactly...

**Comment by Primokorn** [comment] 2017-08-23 12:16
OK I understand. I'll report other websites to see if it's the same issue.

**Comment by kspearrin** [comment] 2017-08-23 12:18
@Primokorn One possible solution o get better detection would be to monitor network traffic with the [webRequest API](https://developer.chrome.com/extensions/webRequest). I could scan all forms on the page, get their action/method and look for that to occur in the network traffic. This is probably a lot more complex to handle but may subvert the need to monitor the DOM directly like we do today.

**Comment by jeroen7s** [comment] 2017-08-23 12:21
@kspearrin that will probably cause a lot of trouble for detection, especially with stuf like forms using angular where the url the form's being sent to is hidden somewhere in the javascript code

**Comment by kspearrin** [comment] 2017-08-23 12:25
@jeroen7s Indeed. Here is another website that does the same exact thing as the one @Primokorn shared. Form with a hidden submit button and then another button outside the form that submits the actual form. My proposed solution about the network traffic would not work since there is no action on the form:

https://store.steampowered.com//login/

![image](https://user-images.githubusercontent.com/1190944/29615638-ae890d86-87dc-11e7-90ed-bc8f9c022475.png)

**Comment by Primokorn** [comment] 2017-08-23 13:59
I guess it's the same behaviour with this website: https://www.generation-nt.com/
Unfortunately it seems that we have this issue on many websites.

![](https://framapic.org/rsImX2WWpNLc/fQpRY7YkEsd0.PNG)

**Comment by kspearrin** [comment] 2017-08-23 14:01
No, that website is fine and bitwarden worked correctly for me there???

**Comment by Primokorn** [comment] 2017-08-23 14:09
I don't have the notification when creating a new account.
Firefox portable 55.0.2 (32 bits)

**Comment by kspearrin** [comment] 2017-08-23 14:10
Hmm, not sure. It's working for me.

**Comment by kspearrin** [comment] 2017-08-23 14:12
@Primokorn Nevermind. Looks like it doesn't work on Firefox for some reason. I think the improvements I have made in the next version will work with it though.

**Comment by Primokorn** [comment] 2017-08-23 14:20
@kspearrin I don't know what to say.
Except the websites that don't respect HTML standards I normally get the notification with Firefox.

However I have many tweaks so I tried with Firefox Beta 56.x (no tweaks at all) and the notification worked too.

**Comment by kspearrin** [comment] 2017-08-23 14:23
By tweaks do you mean addons?

**Comment by Primokorn** [comment] 2017-08-23 14:25
Addons and a modded version of [Ghacks' user.js](https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js) to imrove security & privacy. Some stuff are broken sometimes :)

**Comment by kspearrin** [comment] 2017-09-02 04:31
@Primokorn v1.15.x has gone live with these improvements.

**Comment by kspearrin** [comment] 2017-09-02 04:32
Note that they are general improvements and do not fix the few other cases of bad HTML that we pointed out here.

**Comment by kspearrin** [comment] 2017-09-29 02:00
Closing this issue since the original reported issue was resolved. Feel free to open another issue if there are other things.

**Closed by kspearrin** 2017-09-29 02:00 UTC
