### ISSUE TITLE
Memory footprint increase upon extension open/close (possible memory leak)

### ISSUE THREAD

**Issue by ptoro** [bitwarden/browser#2375] opened 2022-02-13 20:27 UTC
### Steps To Reproduce

1. Ensure auto-fill on page load is checked.
2. Note the memory footprint
3. Click the extension icon to open
4. Click the extension icon again to close
5. Note the memory footprint again
6. Repeat steps 2-5 to continue to see the memory footprint increase.

### Expected Result

After opening and closing, the memory footprint should return to the level it was before the extension was opened.

### Actual Result

After opening and closing, the memory footprint increases to higher than before the extension was first opened.

### Additional Context

On 1.56.4, I'm seeing a potential memory leak.

Every time I open and close the extension, the memory footprint increases. It started at 71 MB, increased by about 20 MB each time I opened it and reduced by about 13 MB each time I closed it. After about 7 open/closes, the memory footprint is now at 125 MB and holding.

### Operating System

macOS

### Operating System Version

12.2

### Web Browser

Chrome

### Browser Version

Version 98.0.4758.80 (Official Build) (x86_64)

### Build Version

1.56.4

**Comment by kspearrin** [comment] 2022-02-14 15:38
@ptoro I am able to reproduce the issue on Windows, however, I am also able to reproduce the issue with other extensions that I also have installed that also have a popup window like ours. Can you test this? Will continue to investigate, but I am not sure what level of memory management capability we have here.

**Comment by MGibson1** [comment] 2022-02-14 15:40
@djsmith85, I believe you've looked into this in the past, can you provide some more insight here?

**Comment by djsmith85** [comment] 2022-02-14 16:18
Yes, I recently looked into this, due to reports on:
https://github.com/bitwarden/browser/issues/2249, https://github.com/bitwarden/browser/issues/2198 and https://github.com/bitwarden/browser/issues/1770

I was also able to reproduce this with the steps provided here and in https://github.com/bitwarden/browser/issues/2249.

I haven't been able to narrow down the cause or causes, yet. This will need further investigation. 

I'm closing this as duplicate of https://github.com/bitwarden/browser/issues/2249

**Closed by djsmith85** 2022-02-14 16:18 UTC
Labels: bug
