### ISSUE TITLE
Extension Closes and Loses All Entered Data

### ISSUE THREAD

**Issue by dustingraham** [bitwarden/browser#1859] opened 2021-05-23 19:28 UTC
## Describe the Bug

Bitwarden cancels and loses data entered into add site if clicking away from the bitwarden form for anything.

Potential to lose password and depending on the site, completely lose access to the account you created. (Severe example being a crypto wallet, where there are no recovery options. Most sites you can use forgot password. This is still very bad.)

## Steps To Reproduce

1. Click bitwarden extension.
2. Click on add item.
3. Paste password into password field.
4. Click over to site (Observe bitwarden closed!)
5. Copy email address, or other item you wanted to note.
6. Click on bitwarden extension again.
7. Observe site add item entry is missing.
8. Observe password is lost.

## Expected Result

When starting to add a new item, do not erase or lose information when clicking away.

At a minimum, prompt user to tell them they will lose their information without saving.

Slightly better, when clicking on bitwarden extension again, re-display existing state of adding a new site.

## Actual Result

Lose add site item without any user interaction or confirmation to cancel or save.

## Environment

- Operating system: Win 10
- Browser: Firefox 88.0.1
- Build Version: 1.50.0

## Additional Context

Another situation is I clicked add site, adjusted the name, set an email and a password, typed in a few things into notes, then I wanted to copy/paste one more thing over into notes, so I clicked over to copy something, and boom. Lost all entered data, wasting lots of time.

Even trying to get the build version, I clicked on about, I clicked back over to github issue to type in the version, and the window closed. I didn't memorize the version, so I had to re-open it and re-open settings and re-open about.

**Comment by eliykat** [comment] 2021-05-23 21:14
This is a duplicate of #1798, please see the discussion on that issue for more information.

**Closed by eliykat** 2021-05-23 21:14 UTC

**Comment by dustingraham** [comment] 2021-05-23 22:12
Thanks, I searched a few variations but was searching for open issues.

@eliykat can you re-open this and consider automatically saving the data, so that when the browser auto-closes the extension, the information isn't lost?

**Comment by eliykat** [comment] 2021-05-24 00:49
Hey @dustingraham, the best place to advocate for this is in [this thread on our forums](https://community.bitwarden.com/t/browser-extension-remembers-where-i-was/1369/). As I mentioned in my last comment in #1798, we use Github to track bugs & defects, and our forums for feature requests & product improvements (and I would classify this as a product improvement). Our forums are definitely monitored internally, even if there's no official response on that thread, so that's the best place to lend your voice.

**Comment by dustingraham** [comment] 2021-05-24 01:18
Thanks for your response.
