### ISSUE TITLE
[Firefox] Generated password not inherited when adding new login

### ISSUE THREAD

**Issue by Inrumpo** [bitwarden/browser#1943] opened 2021-07-08 11:17 UTC
## Describe the Bug

While creating a new login in the Firefox browser plugin, clicking "Select" after generating a password will not inherit the generated password. The result is the same as if "Cancel" was clicked.

## Steps To Reproduce

1. Go to a website where you'd like to create a new login.
2. Click on "add a login".
3. Generate a new password.
4. Click on "Select".

## Expected Result

I expect the generated and selected password to be filled into the "password" box.

## Actual Result

Pressing "Select" provides the same result as pressing "Cancel".

## Environment

- Operating system: Windows 10 64-bit
- Browser: Firefox 89.0.2 64-bit (Desktop)
- Build Version 1.51.0

**Comment by eliykat** [comment] 2021-07-08 23:33
Duplicate of #1927, fixed by #1935. This fix will be included in v1.51.1 which was released via Github yesterday, it should hopefully show up in the Firefox store in the next few days.

**Closed by eliykat** 2021-07-08 23:33 UTC
