### ISSUE TITLE
Filled values by Bitwarden are not recognize by website

### ISSUE THREAD

**Issue by szymon-wesolowski** [bitwarden/browser#1351] opened 2020-08-10 06:39 UTC
## Describe the Bug

Bitwarden fills edit box, it shows dot, but the website claims field is still empty.

## Steps To Reproduce

1. Go to https://www.pekao24.pl/logowanie
2. Input user name and go next
3. Use Bitwarden to fill passowrd boxes
4. Try to go next

## Expected Result

Correctly fill passowrd boxes

## Actual Result

Warning from website, please fill all boxes.

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/33084923/89757188-d6d67900-dae4-11ea-9ba0-4c5c169bf5b8.png)

## Environment

Operating system: Windows 10
Browser: Chrome 84.0.4147.105
Build Version 1.45.0

**Comment by szymon-wesolowski** [comment] 2020-08-10 18:09
coresponding issue #1350

**Comment by cscharf** [comment] 2021-01-05 14:39
Closing this as a duplicate of #1350 ; The banking website is asking for specific characters from the password. It appears this website maintains a function and DOM manipulation/interactivity through JavaScript which also expects user interaction, which our autofill framework currently cannot mimic or is using the Shadow DOM which our autofill framework currently doesn't manipulate (there is an active feature request for this already).

**Closed by cscharf** 2021-01-05 14:39 UTC
