### ISSUE TITLE
"Unable to autofill" when extension is opened while page is loading.

### ISSUE THREAD

**Issue by leifmetcalf** [bitwarden/browser#625] opened 2018-05-20 20:33 UTC
If I'm too fast and click the little gizmo before the login prompt renders, auto-fill fails. If I close and re-open the little gizmo auto-fill then works again.

It's not much of a problem, but it seems pretty easy to fix, just find the code that checks the page for a login input and make it run when the auto-fill tries to happen. I have no idea how JavaScript works though, sorry I can't try fix this myself :disappointed:

This is on Firefox 60.0.1 on Ubuntu 18.04

**Comment by eliykat** [comment] 2021-02-17 00:58
Duplicate of #488.

**Closed by eliykat** 2021-02-17 00:58 UTC
