### ISSUE TITLE
Chrome Extension Blurriness on Retina Displays using non-default resolution

### ISSUE THREAD

**Issue by eldridgea** [bitwarden/browser#697] opened 2018-08-16 17:42 UTC
This happens when using the Bitwarden Chrome extension on a Mac laptop, if the screen resolution is greater than the default ("more space" in Display Settings).

Clicking the extension icon and getting the UI is blurry, ony for the Bitwarden UI. Clicking the pop out button to open in a separate window works and has no blurriness issues.

**Comment by kspearrin** [comment] 2018-08-16 17:54
Sounds like an issue with the browser. We don't handle how the popup is displayed. That's something the browser does.

**Comment by djsmith85** [comment] 2021-08-15 12:44
Hi @eldridgea, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by djsmith85** 2021-08-15 12:44 UTC

**Comment by Firu115** [comment] 2025-02-28 12:53
I'm experiencing the same behaviour on MB Air M3. It is, however, not an issue with BitWarden, rather with Chrome itself. What I discovered is that it only happens when my FullHD external monitor is plugged in. 
(I think it won't be the case with QHD, since it is closer to the built-in Retina PPI.)

Firefox is ok. I hope this helps someone.
