### ISSUE TITLE
Firefox Add-on prompts that it cannot open in private window when opened in normal window

### ISSUE THREAD

**Issue by itsjaredbs** [bitwarden/browser#619] opened 2018-05-07 13:53 UTC
Firefox 59.0.3 64-bit win10-x64
Bitwarden Add-on 1.26.4

Upon logging in to the Bitwarden Firefox add-on, Bitwarden prompts "Unfortunately this window is not available in private mode for this browser." however the window is a normal window.

Within the same session/window, removing the 1.26.4 plug-in and reverting back to 1.26.3 resolves the issue.

**Comment by kspearrin** [comment] 2018-05-07 14:36
Hm. That doesn't seem related to our extension. Nothing new when opening/closing the popup window?

**Comment by itsjaredbs** [comment] 2018-05-07 14:56
Nothing else on the console. I went ahead and created a new profile to reproduce. 

100% clean Firefox 59.0.3 64-bit with no other extensions or preferences changed. I can still reproduce the issue.

1. Close all instances of Firefox.
2. Open `'C:\Program Files\Mozilla Firefox\firefox.exe' -p`
3. Create a new profile.
4. Launch Firefox with that new profile.
5. Navigate to https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/versions/.
6. Install Bitwarden Add-on 1.26.4 and wait for Sidebar to open with Bitwarden displayed.
7. Open a new tab to about:debugging
8. Enable debugging tools.
9. Click Debug for Bitwarden extension.
10. Click 'OK' to allow remote debugging to connect.
11. Back in the main window, in the Sidebar, click Log In for Bitwarden.
12. Enter email address.
13. Enter password.
14. Click login.
15. When prompted by Firefox to save password, click Not Now.

- Observe the Debug window close automatically. Console, before closing, did not display anything.
- Bitwarden sidebar is empty.

16. Go back to tab with https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/versions/ open.

- Observe Bitwarden sidebar is empty and Toolbar icon displays "Unfortunately this window is not available in private mode for this browser."

17. Click Login on https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/versions/, which forwards to https://accounts.firefox.com/oauth/signin?scope=profile&state=51964afac5408b300de61ba07ed9134ca0b7f9e4c3510350868c32823211cb02%3AL2VuLVVTL2ZpcmVmb3gvYWRkb24vYml0d2FyZGVuLXBhc3N3b3JkLW1hbmFnZXIvdmVyc2lvbnMv&redirect_url=https%3A%2F%2Faddons.mozilla.org%2Fapi%2Fv3%2Faccounts%2Fauthenticate%2F&client_id=a4907de5fa9d78fc.

- Observe Bitwarden sidebar is empty and Toolbar icon displays "Unfortunately this window is not available in private mode for this browser."

Opening the debug console again at this stage and observing the behavior for Step 16 and 17 does not result in anything appearing in the Console.

**Comment by kspearrin** [comment] 2018-05-07 17:39
@itsjaredbs I still can't reproduce it on my system unfortunately. Would you happen to have some time today to swing by the developer chatroom and test a few things live with me try to debug this further?

https://gitter.im/bitwarden/Lobby

**Comment by itsjaredbs** [comment] 2018-05-07 19:18
Just took lunch and played around with this. Sorry I didn't see it earlier. I won't be able to until later this evening (~4 hours from now)

I tested on another machine that is not corporately locked down and could not reproduce it, so I'm assuming it has to be something with the group policy or multiple security applications on this particular machine. This might just be a one off issue then.

During lunch, I was able to get responses in the Console now.

1. Remove all Firefox AppData via PowerShell `ri -Force -Recurse .\AppData\*\Mozilla*`
2. Reinstall Firefox 59.0.3
3. Steps to get bitwarden add-on installed, debugging enabled, etc.

I'm seeing this in the debug Console now.
![image](https://user-images.githubusercontent.com/5382149/39717817-61d330b6-5202-11e8-8c8a-c495a07a1586.png)

The warning items listed in the screenshot that have 22 errors trigger on mouseover of the toolbar icon for Bitwarden. The warning and errors listed trigger when I click on the toolbar icon.

The error text items are:
`14:16:51.094 downloadable font: kern: Too large subtable (font-family: "Open Sans" style:normal weight:normal stretch:normal src index:0) source: moz-extension://0cfd10e7-4491-4b27-98ae-9d1a1059ac48/popup/fonts/Open_Sans-normal-400.woff 1 unknown:49:11`

`14:16:51.094 downloadable font: Table discarded (font-family: "Open Sans" style:normal weight:normal stretch:normal src index:0) source: moz-extension://0cfd10e7-4491-4b27-98ae-9d1a1059ac48/popup/fonts/Open_Sans-normal-400.woff 1 unknown:49:11`

`14:16:51.097 downloadable font: kern: Too large subtable (font-family: "Open Sans" style:normal weight:bold stretch:normal src index:0) source: moz-extension://0cfd10e7-4491-4b27-98ae-9d1a1059ac48/popup/fonts/Open_Sans-normal-700.woff 1 unknown:65:11`

`14:16:51.097 downloadable font: Table discarded (font-family: "Open Sans" style:normal weight:bold stretch:normal src index:0) source: moz-extension://0cfd10e7-4491-4b27-98ae-9d1a1059ac48/popup/fonts/Open_Sans-normal-700.woff 1 unknown:65:11`

I checked in Nightly as well, and see this in the Console (`92339090-8a7b-4ef6-bae5-ab1412a25d73` is the Bitwarden UUID).
![image](https://user-images.githubusercontent.com/5382149/39718721-26c3dd38-5205-11e8-9e71-f2386f2b29df.png)

**Comment by kspearrin** [comment] 2018-05-07 19:38
Hmm. I am still not seeing anything there that would cause a problem with private mode. Mostly just CSS styling errors and a few others that would be expected. If you have some time later please let me know and I can try debugging this with you further.

**Comment by kspearrin** [comment] 2018-05-08 12:25
Can you try version 1.26.5 and see if the problem still remains?

**Comment by itsjaredbs** [comment] 2018-05-08 13:14
@kspearrin 1.26.5 is working properly now. Both Sidebar and Toolbar widget display and work correctly!

**Closed** 2018-05-08 13:15 UTC

**Comment by dhduvall** [comment] 2021-12-16 22:31
FWIW, I've seen this (well, it's logged in, but I get the message on trying to unlock the vault, even in a non-private window) a couple of times on more recent versions of Firefox and the addon. I didn't take stock of it previously, but this time it's Bitwarden 1.55.0 and Firefox 95.0.

I found that disabling it and re-enabling it from about:addons got it working again. I've no idea what gets it into this mode, and it happens pretty rarely.
