### ISSUE TITLE
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by Jerriy** [bitwarden/browser#1791] opened 2021-04-17 09:43 UTC
I see that Bitwarden error message all over my Firefox console. 

It happens whenever I go to every new site, or new tab - or even when I'm just clicking on an already existing and loaded other tab. 

Also happens when I use keyboard only (so it's not a mouse issue).

It even happens when the tab that just opened is not a website but a browser options or info or whatever other internal tabs that don't link to the internet.

Just to test I disabled every other addon and only left Bitwarden enabled - the error appears. The error goes away only if I disable Bitwarden addon.

It also doesn't make any difference whether the Bitwarden vault is logged in or out. The error displays links to a "background.js" page of the Bitwarden addon. But that's just a page with code text... curiously, going to this Bitwarden internal tab itself causes the error to be reproduced once more.  I can't find any tab related setting in Bitwarden options. The word "tab" does not even exist there. I also disabled the addon's availability in browser context menu but the problem did not go away. I alqs

So what on earth is it, and how do I stop it?

[https://user-images.githubusercontent.com/979729/97782159-51ec8000-1b66-11eb-811c-52d33ce73d7b.jpg](url)

**Comment by SergeantConfused** [comment] 2021-04-17 16:13
Hi there,

I use Firefox with the Bitwarden add-on and my Console is clean. Firefox 87.0, Bitwarden 1.49.1, on Windows 10 Pro. I'm also unable to open that screenshot, can you please re-upload it?
Did you try uninstalling Bitwarden and Firefox and reinstalling both from scratch?

Thank you in advance,

**Comment by cho-m** [comment] 2021-04-19 04:09
I've seen something similar running latest versions on macOS.
<img width="600" alt="firefox-console" src="https://user-images.githubusercontent.com/20700669/115179855-219f8c00-a089-11eb-8678-c62d9014a9b6.png">

One example scenario would be when clicking a different window:
1. User clicks different Firefox Window
2. Firefox fires an event (maybe [windows.onFocusChanged](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/onFocusChanged)?)
3. Bitwarden's background process detects this and tries to send a message to extension using [runtime.sendMessage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/sendMessage#return_value) API.
    https://github.com/bitwarden/browser/blob/b029ead5f613ff20291f0e2786c5478db26005f1/src/background/windows.background.ts#L15-L21

4. For some reason, background process can't connect to extension. From API documentation, this will result in error:
    >  If an error occurs while connecting to the extension, the promise will be rejected with an error message.
5. Bitwarden doesn't handle the error, which may result in it being sent to console.

---

In my case, the errors stop when I open the Bitwarden sidebar, which would keep Bitwarden foreground active and capable of receiving messages.

I will note that I do have a bunch of extra `about:config` settings, so there could be a setting blocking communication.

**Comment by barnabycollins** [comment] 2021-09-06 12:35
I'm having this same problem: the extenssion still has a copy of my vault that I have to sign in to access, but I don't think it's synchronised in quite some time as it's missing a number of accounts I would have added in June. It also fails to save new signins, so I have to visit the web vault and use that if I create a new account.

I've checked the [extension debugger](https://extensionworkshop.com/documentation/develop/debugging/) and I have hundreds of the error message in the post name - for example:

![image](https://user-images.githubusercontent.com/23247109/132217463-b560b16d-091b-49eb-9396-f376f6e827bd.png)

I'm guessing this is the root cause of the problem. I'm also seeing a number of other errors that may or may not be related:

![image](https://user-images.githubusercontent.com/23247109/132217735-768b3f7d-ee11-4f27-a550-02edfa305a6c.png)
![image](https://user-images.githubusercontent.com/23247109/132217816-8df95e7c-52a6-4a05-addc-fa3c0c3081ee.png)
![image](https://user-images.githubusercontent.com/23247109/132217877-0078f9c5-c2ea-4446-9e23-d5aa0814001c.png)
![image](https://user-images.githubusercontent.com/23247109/132217923-22392993-911c-4ef3-b318-ac8959316e76.png)
![image](https://user-images.githubusercontent.com/23247109/132217958-4c82b55e-1bd6-4821-99b9-1cc05ca0c156.png)
![image](https://user-images.githubusercontent.com/23247109/132218042-59cbb77d-d9cb-432b-a126-298b7ac4ca27.png)

This last one appears alongside the "Receiving end does not exist" error repeatedly, so I'm inclined to think that this could be part of it, but it could just be two separate messages that come out when the extension tries to sync.

![image](https://user-images.githubusercontent.com/23247109/132218167-05cad494-7547-4204-a9e6-2b8bf4076967.png)

I'm inclined to think that something may be corrupted in my database, but I'm not entirely sure how to rectify this and I believe I have the same issue across two separate devices. What would be the best way to go about this if it is indeed a problem with my client?

**Comment by setyb** [comment] 2021-11-08 05:53
I'm hoping this issue that was reported over a half-year ago can receive some love.

The bug is still present in Bitwarden 1.54.0 (latest release) when using the latest release of Firefox 94.x (currently 94.0.1).

The Firefox browser console is filled with hundreds (perhaps thousands) of the following error:
```
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  background.js:2455
```

According to the browser console, the error is coming from Bitwarden's `background.js` script.

Is anyone at Bitwarden looking into this?

**Comment by barnabycollins** [comment] 2021-11-08 13:35
For those still having this problem (@setyb) - I removed and re-added the Bitwarden add-on on all my devices and that seems to have resolved it! Really should have tried that before posting on here 😅 I guess it seems like a reasonably common problem though, so probably still relevant as an Issue that the developers should be aware of.

**Comment by eliykat** [comment] 2021-11-24 01:24
Closing as a duplicate of #1208. Please refer to that Issue for any updates or further discussion.

**Closed by eliykat** 2021-11-24 01:24 UTC
