### ISSUE TITLE
Bitwarden for Edge breaks on Windows Insider Build 17704

### ISSUE THREAD

**Issue by sirredbeard** [bitwarden/browser#661] opened 2018-06-30 17:22 UTC
Bitwarden 1.27.0
Windows 10 Pro Insider Preview Build 17704.1000 (current Insider Fast Ring build)
Microsoft Edge 43.17704.1000.0

Vault will not open.

Unlocking the vault in the app has no effect.

I have also tried uninstalling/re-installing.

![annotation2](https://user-images.githubusercontent.com/33820650/42127546-a878047a-7c68-11e8-9df4-048241ce1e1c.png)

**Comment by sirredbeard** [comment] 2018-06-30 17:39
Do not appear to be any. Am I looking in the right place? 
![annotation4](https://user-images.githubusercontent.com/33820650/42127671-f89ed346-7c6a-11e8-8665-2d7d420f0131.png)

**Comment by kspearrin** [comment] 2018-06-30 17:40
Right click in the actual popup window and inspect that.

**Comment by sirredbeard** [comment] 2018-06-30 17:51
That crashes Edge entirely. Screen video: https://imgur.com/RfQHMnZ

**Comment by kspearrin** [comment] 2018-06-30 17:54
Pretty typical in Edge. The dev tools are garbage. I'll have to try and install an insider build to look at it, though I am unfamiliar with insider builds on Windows. Can I install it on a VM or something?

**Comment by sirredbeard** [comment] 2018-06-30 18:09
How to create Insider environment:
Grab the [Windows 10 ISO](https://www.microsoft.com/en-us/software-download/windows10)
Install in any VM.
Settings->Update & Security->Windows Insider Program.
Enable and set to Fast Ring.
Restart and then Settings->Update & Security->Windows Update->Check for Updates.
It should start downloading 17704 within a few minutes to hours.
Reboot.

If you have a Visual Studio subscription you can also fire up Windows 10 images in Azure and update to Insider there for testing.

**Comment by kspearrin** [comment] 2018-07-02 13:08
I can re-create the problem, but since Edge crashes immediately when trying to debug the extension window there isn't a way for me to figure out why it is failing. I have sent a report through the feedback hub. I suggest you do the same.

**Comment by sirredbeard** [comment] 2018-07-02 13:11
I already reported it [here](https://aka.ms/AA1pr1o) can you upvote it? If you will post the link to your feedback, I will upvote it. I am also going to @ some Edge developers I know on Twitter.

**Comment by kspearrin** [comment] 2018-07-02 13:23
It says my account doesn't have access to your feedback link. I can't seem to figure out where you get a public link for my feedback report.

**Comment by sirredbeard** [comment] 2018-07-02 13:44
That is annoying.

You have to open the My Feedback app, go to My Feedback, open the feedback, and click the "Share" icon.
![capture2](https://user-images.githubusercontent.com/33820650/42167398-fef270c8-7ddb-11e8-8344-f0007cba05de.PNG)

A Edge PM on Twitter sent me [this](https://twitter.com/molant/status/1013777543294406656).

So I reported it [here](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18117681/).

**Comment by sirredbeard** [comment] 2018-07-05 16:21
FWIW, it has been marked as confirmed and assigned to someone on Edge team.

**Comment by kspearrin** [comment] 2018-07-05 16:41
Thanks for the update.

**Comment by michiil** [comment] 2018-08-17 17:07
Devtools do open for me. Here is a screenshot:
![image](https://user-images.githubusercontent.com/5451489/44279126-8d822480-a250-11e8-8e7d-fba1421e9808.png)

If you need something else just ask!

**Comment by kspearrin** [comment] 2018-08-17 17:15
Thanks @michiil . Looks like edge has some bug with fetching the background page from the popup. Not much we can do.

Closing since this is being tracked officially here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18117681/

Looks like they marked it as confirmed.

**Closed by kspearrin** 2018-08-17 17:15 UTC
