### ISSUE TITLE
Secure notes unable to view text while typing in Chrome extension

### ISSUE THREAD

**Issue by kaledev** [bitwarden/browser#2109] opened 2021-10-09 20:07 UTC
### Steps To Reproduce

1. Go to My Vault
2. Click on Secure Note
3. Click '+' to add a note, or click an existing note
4. Click 'Edit' if this is an existing note, otherwise skip to the next step
5. Scroll to Notes section
6. Click into the Notes section and type or edit text

### Expected Result

You should see the cursor and changes/additions should be visible as you type/edit.

### Actual Result

Currently, you cannot see the cursor and typing or deleting doesn't visually show in the notes section *until* you either save the note or you click on the lower right hand corner and expand the text box height. Doing this will immediately display all additions or changes. This forces a user to type and constantly adjust the height of the text box to see the result.

### Operating System

macOS

### Web Browser

Chrome

### Build Version

1.53.0

**Comment by eliykat** [comment] 2021-10-10 21:30
Hi @kaledev, thanks for the report! This looks like a duplicate of #1854, so I'll close this one. Please see the discussion in #1854, I also just posted a potential fix in there if you'd like to give that a try.

**Closed by eliykat** 2021-10-10 21:30 UTC
Labels: bug
