### ISSUE TITLE
[Firefox] Add Attachment -> Search... leads to closing bitwarden

### ISSUE THREAD

**Issue by AnonStar** [bitwarden/browser#1512] opened 2021-01-01 18:05 UTC
## Describe the Bug

When I open bitwarden (firefox addin), copy e.g. the username and click outside of the bitwarden-window (e.g. other application) it closes the bitwarden-window.
In chrome it doesn't do that. Usually I would open bitwarden again to copy the password now so it was an annoying behaviour but I could handle it.

But when I try to upload an attachment then bitwarden closes as the "Search..." explorer-window appears. When I select a file there and click okay nothing happens.

In Chrome it doesnt close the bitwarden window and I can click Save after selecting a file. So I think it's thjis auto-close which leads to the problem.

## Steps To Reproduce

1. Go to any entry -> edit -> attachement -> search...
2. Select any file
3. Click on 'okay'

## Expected Result

Dialog with selected file and Save-option

## Actual Result

bitwarden window already closed and nothing happens. no option to click "save"

## Screenshots or Videos

%

## Environment

- Operating system: Windows 10 2004
- Browser: Firefox 84.0.1 (64bit)
- Build Version (go to "Settings" → "About" in the app): 1.47.1

**Comment by SergeantConfused** [comment] 2021-01-02 15:56
Hi there,

Thank you for bringing this to our attention, we'll look into this.
I would you to please note that as a temporary work-around, you can decouple the Bitwarden extension and open it in a separate window in Firefox and perform these actions without it closing.

I hope this helps. Please let me know if you have any further questions.

Al

**Comment by eliykat** [comment] 2021-01-13 21:11
Thanks for reporting this bug. This is a duplicate of issue #1354 - please check that issue for future updates.

**Closed by eliykat** 2021-01-13 21:11 UTC
