### ISSUE TITLE
Bitwarden Extension Locks After Browser Restart, But Vault Timeout is 4 Hours.

### ISSUE THREAD

**Issue by Nihal247** [bitwarden/browser#1934] opened 2021-07-06 03:17 UTC
I am using Firefox, the Bitwarden extension, locks itself after every browser restart, but I have set the Vault Timeout to 4 hours. Therefore, it shall lock itself 4 hours after every browser restart, but this is not the case.
 
Versions:
Firefox - 89.0.2
Bitwarden extension - 1.51.0

![Screenshot (1035)_LI](https://user-images.githubusercontent.com/80682093/124536898-77890200-de36-11eb-9420-7e8a23231512.jpg)

![Screenshot (1036)](https://user-images.githubusercontent.com/80682093/124536980-a30bec80-de36-11eb-8153-b73c9679657d.png)

☝Locks after browser restart.

Thank you in advance.

**Comment by eliykat** [comment] 2021-07-06 04:02
Hi @Nihal247, this is expected behaviour. See the [Vault Timeout Options](https://bitwarden.com/help/article/vault-timeout/) documentation:

>Regardless of Vault Timeout settings, closing the Browser or Browser Tab will end your Web Vault or Browser Extension session, meaning you’ll be required to log in to access your Vault.
>
>If you’re using a Browser Extension, you can bypass this by enabling the Unlock with PIN option and unchecking the Lock with master password on browser restart checkbox.

This is because once the browser is closed, we lose control over the timeout feature (e.g. we can't count how much time has passed or lock the vault once the timeout expires). Therefore, the vault is locked when the browser is closed, to be safe.

The only exception to this is choosing "Never" as your vault timeout, because then your vault is just never locked, and we don't have to worry about monitoring the timeout after the browser is closed. However, that can obviously raise security concerns, so it may not be what you're after.

I'll close this issue because this is expected behaviour.

**Closed by eliykat** 2021-07-06 04:02 UTC

**Comment by Nihal247** [comment] 2021-07-06 04:13
Thanks @eliykat I didn't knew it.
