### ISSUE TITLE
Search field in Chrome extension repeats characters

### ISSUE THREAD

**Issue by Toontje** [bitwarden/browser#577] opened 2018-04-04 07:43 UTC
Check the attached video. [bw.mov.zip](https://github.com/bitwarden/browser/files/1874723/bw.mov.zip)

Chrome Version 66.0.3355.0 (Official Build) dev (64-bit) on OSX 10.12.6
Bitwarden 1.25.5

I click the three dots in Chrome to open the Bitwarden extension.
I type one character in the search box, in this case an h.
Character gets repeated.

**Comment by kspearrin** [comment] 2018-04-04 12:10
Weird. I am not sure. Does this happen every time?

**Comment by Toontje** [comment] 2018-04-04 17:31
Yes.

**Comment by djsmith85** [comment] 2021-05-13 01:06
@Toontje Thank you for opening this issue. I know this is really old and several new version have been released since then. Is this reproducible or was the issue resolved with one of the more recent version. If it's resolved could you please close this issue.

**Comment by Toontje** [comment] 2021-05-13 06:23
DISAPPEARED IN NEWER VERSIONS.

**Closed** 2021-05-13 06:23 UTC
