### ISSUE TITLE
Safari Popup blank after Biometric unlock

### ISSUE THREAD

**Issue by michiil** [bitwarden/browser#1960] opened 2021-07-17 09:10 UTC
## Steps To Reproduce

See video.

## Expected Result

Vault unlocks.

## Actual Result

Pupup stays blank and I have to restart Safari to log in.

## Screenshots or Videos

https://user-images.githubusercontent.com/5451489/126032165-b0e77288-425e-410b-aa71-49e1fe83222e.mov

## Environment

- Operating system: Mac Os 11.4 (Apple M1)
- Browser: Safari 14.1.1
- Build Version (go to "Settings" → "About" in the app): 1.27.1

**Comment by SergeantConfused** [comment] 2021-07-17 14:55
Hi @michiil,

I just tested this on an M1-based MacBook Air running macOS 11.4, Safari 14.1.1 and Bitwarden 1.27.1, and this worked as intended. Let's start with a fresh installation, please. Uninstall all your Bitwarden clients, remove all leftover data, reboot your machine, reinstall Bitwarden from the Apple App Store, and test that again. The procedure to enable the Safari browser extension and the locations of any leftover data are detailed in the following guides.
https://bitwarden.com/help/article/data-storage/
https://bitwarden.com/help/article/install-safari-app-extension/

If that does not help, please get in touch with us using this form: https://bitwarden.com/contact/ so we would continue assisting you.


All the best,

**Comment by michiil** [comment] 2021-07-17 16:01
Hi,
unfortunately reinstalling as you described did not fix the issue. I'll get in touch via the contact form as you suggested!
Best regards
Michael

**Comment by eliykat** [comment] 2021-07-18 21:55
I'm closing this as we're now handling this as a customer support issue. If it is a bug that can be reproduced by our CS team, I'll reopen this with any additional info they provide.

**Closed by eliykat** 2021-07-18 21:55 UTC
