### ISSUE TITLE
Wrong saved password when switching keyboard language

### ISSUE THREAD

**Issue by mystrdat** [bitwarden/browser#1972] opened 2021-07-26 09:33 UTC
## Describe the Bug

After I generated a password using the right click menu (Generate Password (copied)) and entered it to log in, the extension prompted to save the password. Instead of the actual password that was in clipboard, the extension saved garbage. Eg. SN2y6tbCBUxTuq was generated, +ěškměšěšřčěšě was saved. Possibly related to switching keyboard language between the steps.

## Steps To Reproduce

1. Generate a password in a field using right click menu
2. Use it to log in or register
3. ?? Switch keyboard language ??
3. Save the password when the extension prompts it

## Expected Result

The saved password should be the same one that was generated.

## Actual Result

The saved password is something else.

## Environment

- Operating system: Windows 10
- Browser: Vivaldi 4.0.2312.41
- Build Version: 1.51.1

**Comment by SergeantConfused** [comment] 2021-07-26 11:13
Hi @mystrdat,

I tested this on the same operating system and browser, and I am unable to reproduce this. Are you able to consistently reproduce this behaviour on your machine by following the steps you mentioned?

Thank you in advance,

**Comment by mystrdat** [comment] 2021-07-26 11:25
Hi @SergeantConfused,

Apparently not consistently, there may have been some more specific steps I took that caused the issue. I'll keep trying to see if I can figure out the exact scenario. Thanks for the quick reply.

**Comment by djsmith85** [comment] 2021-12-17 18:30
Hi @mystrdat, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by djsmith85** 2021-12-17 18:30 UTC
