### ISSUE TITLE
Firefox add-on looses user input when focus lost

### ISSUE THREAD

**Issue by MartyLake** [bitwarden/browser#2465] opened 2022-03-22 17:58 UTC
### Steps To Reproduce

1. click on bitwarden icon in the firefox toolbar
2. click on "add element", enter some values, for example website "example.com", user "user", password "pa$$"
3. alt-tab to another window, for example notepad.exe. the extension is closed
4. go back to firefox, click on bitwarden icon again. 

### Expected Result

I see the "add element" pannel, with website "example.com", user "user", password "pa$$", already filled in

### Actual Result

I see the default panel. If I click on "add element" again, it is a blank page.

All information entered is lost.

### Operating System

Windows

### Operating System Version

windows 10 professional

### Web Browser

Firefox

### Browser Version

98.0.1

### Build Version

 1.56.6

**Comment by eliykat** [comment] 2022-03-23 02:05
Hi, this is a duplicate of issue #1798. Please see my [response in that thread](https://github.com/bitwarden/browser/issues/1798#issuecomment-831574003) for more information. Thanks!

**Closed by eliykat** 2022-03-23 02:05 UTC
Labels: bug
