### ISSUE TITLE
Custom fields not being filled on demand

### ISSUE THREAD

**Issue by setyb** [bitwarden/browser#1930] opened 2021-07-04 07:05 UTC
## Describe the Bug

When using the browser extension to fill fields, custom fields are no longer getting filled.

## Steps To Reproduce

1. In BW, disabled all BW auto-fill options.
2. In BW, created a `rememberMe` boolean custom field for an Amazon login.
3. In Firefox, went to an Amazon login page that contains the "Keep me signed in" checkbox.
4. Opened BW's popup menu, and clicked on the login to fill all fields.
5. All fields get field in the login page, but the checkbox does not.

## Expected Result

Expect the "Keep me signed in" checkbox to get checked since `rememberMe` is defined as a boolean custom field and set appropriately.

## Actual Result

The "Keep me signed in" checkbox on Amazon's login page does not get filled.

## Environment

- Operating system: Windows
- Browser: Firefox 89
- Build Version: 1.51.0

## Additional Context

This worked fine until recently.  Two things changed:

1. New Firefox profile created (and BW installed in it).
2. BW updated to v1.51.0

Note: If you have a problem finding an Amazon login page with the "Keep me signed in checkbox" (their UI and UX are deplorable, so don't expect their site to be consistent!), try doing something like viewing the details of an order; if you get lucky, Amazon will present the correct login page.

**Comment by eliykat** [comment] 2021-07-05 00:28
I was able to recreate this on Amazon.com on Firefox, but not on Chrome, and not on any other site on Firefox either. Is this affecting other sites for you, or just Amazon?

**Comment by setyb** [comment] 2021-07-05 16:00
@eliykat I honestly have not tried this on other sites besides Amazon.  What's interesting is that it appears to be a regression because it worked until recently.

**Comment by eliykat** [comment] 2021-07-05 20:28
Can you please try to reproduce it on some other sites? To my knowledge, we haven't made any changes to this area of the code that would cause a regression here, but I could be wrong. I'd like to know whether it's a broader issue or just something to do with Amazon.

**Comment by setyb** [comment] 2021-07-11 02:53
> Can you please try to reproduce it on some other sites? To my knowledge, we haven't made any changes to this area of the code that would cause a regression here, but I could be wrong. I'd like to know whether it's a broader issue or just something to do with Amazon.

Per your request, I tried custom fields on another site, and they worked as expected.

I then tried custom fields again on the Amazon login page, and they still did not work.  I even took a couple extra steps and deleted the old custom field and created a new one, and it still didn't work.

According to the official Bitwarden blog, https://bitwarden.com/blog/post/custom-fields-released/, the `name` attribute is allowed as a specifier for custom fields.  In this case, it is `rememberMe`, but Bitwarden does not work when it is specified.  There is no `id` for the field, so that's not an available option.

This all worked until recently, and then it suddenly stopped working.

Since Amazon is, *for better or worse,* the 11th most popular website in the world ([according to, lol, Amazon](https://www.alexa.com/topsites/)), I think it is advisable to make it a priority to implement a fix for this issue.

Of course, Bitwarden also has known issues with the 12th most popular website in the world (which is Yahoo, according to Amazon's statistics), so that might be a worthy priority as well!

**Comment by eliykat** [comment] 2021-07-16 04:25
Thanks for checking that. I agree that it's an issue, I was just confirming that the problem is with certain sites (however popular) and not with the basic autofill functionality itself.

We are aware that autofill doesn't work on all sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. (This issue includes custom field autofill as well.)

I'm reviewing those reports presently, so if you can add your report there it'll help me include it in my roundup.

I'll now close this issue as we're centralizing all these reports in #1621. Thanks!

**Closed by eliykat** 2021-07-16 04:25 UTC
