### ISSUE TITLE
Edge (Chromium) Beta Channel, BitWarden does not lock upon 'Browser Restart'

### ISSUE THREAD

**Issue by DesignatedJM02** [bitwarden/browser#994] opened 2019-08-21 20:53 UTC
When using the Beta channel of Edge Insider Chromium version, BitWarden does not seem to lock itself when I close the browser and restart it even though the option is enabled. With Lock Settings set to "On System Lock", BitWarden does lock itself successfully when I lock my computer. 

Using the Canary version of Edge Insider Chromium, locking on Browser Restart does work as intended.

**Comment by kspearrin** [comment] 2019-08-22 00:43
Since Canary is newer than Beta, I guess we can assume this was a bug now fixed in Edge.

**Comment by OnlinePlayer865** [comment] 2019-08-22 16:08
Yes. I would think that when Beta get's it's next update in about 6 or so weeks that the issue will be fixed. Just wanted to make an issue just in case it wasn't. But I am leaning towards it being fixed down the road in Beta since it seems to work properly in Canary.

**Comment by Hinton** [comment] 2021-12-16 07:06
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by Hinton** 2021-12-16 07:06 UTC
