### ISSUE TITLE
Extremely frequent firefox errors

### ISSUE THREAD

**Issue by aminomancer** [bitwarden/browser#1536] opened 2021-01-16 09:52 UTC
Firefox privileged console is totally riddled with these error logs. They are repeated every time the tab changes, plus who knows how many other processes I haven't noticed yet.
```
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 6 background.js:1738
    send browserMessaging.service.ts:13
```

This is the offending code, specifically the runtime.sendMessage call. This method obviously works fine though, I use it all the time. Normally I'd assume the problem is with the parameter being sent, but the error seems to imply there is no listener, not that the arguments are invalid. Is the background script calling this method itself? But I have plenty of tabs open. There should be plenty of listeners in content scripts. Unfortunately the error log does not tell me the caller.
```
class BrowserMessagingService {
    send(subscriber, arg = {}) {
        const message = Object.assign({}, { command: subscriber }, arg);
        if (_browser_browserApi__WEBPACK_IMPORTED_MODULE_0__[/* BrowserApi */ "a"].isSafariApi) {
            _browser_safariApp__WEBPACK_IMPORTED_MODULE_1__[/* SafariApp */ "a"].sendMessageToApp(subscriber, arg);
            _browser_safariApp__WEBPACK_IMPORTED_MODULE_1__[/* SafariApp */ "a"].sendMessageToListeners(message, 'BrowserMessagingService', null);
        }
        else {
            chrome.runtime.sendMessage(message);
        }
    }
}
```
```
import { BrowserApi } from '../browser/browserApi';
import { SafariApp } from '../browser/safariApp';

import { MessagingService } from 'jslib/abstractions/messaging.service';

export default class BrowserMessagingService implements MessagingService {
    send(subscriber: string, arg: any = {}) {
        const message = Object.assign({}, { command: subscriber }, arg);
        if (BrowserApi.isSafariApi) {
            SafariApp.sendMessageToApp(subscriber, arg);
            SafariApp.sendMessageToListeners(message, 'BrowserMessagingService', null);
        } else {
            chrome.runtime.sendMessage(message);
        }
    }
}
```

STR: I imagine all you need to do is install the addon in Firefox 84 or higher to see this. I can't remember when I started noticing this but I don't think it was present a year ago.

Expected: handled errors

Actual: unhandled errors?

- Operating system: Windows 10, 1909
- Browser: Firefox 86.0a1
- Extension: 1.47.1

**Comment by OsakaWebbie** [comment] 2021-10-01 07:43
I see this also, on every (or nearly every) page load, sometimes multiples. In my case the line number is 3558:
```
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 background.js:3558
    send moz-extension://[long hex number in five parts with hyphens - redacted in case it's a key]/background.js:3558
```
Code where it was found:
```
class BrowserMessagingService {
    send(subscriber, arg = {}) {
        const message = Object.assign({}, { command: subscriber }, arg);
        **chrome.runtime.sendMessage(message);**
    }
}
```

**Comment by aminomancer** [comment] 2021-10-01 23:25
The hex number you mentioned is the extension's component ID (CID). It's an UUID randomly generated for the extension on your installation to ensure all its resources can have a unique moz-extension protocol URI. So the URI `moz-extension://{UUID}/background.js` leads to `jar:file:///C:/Users/user/AppData/Roaming/Mozilla/Firefox/Profiles/profile/extensions/%7B446900e4-71c2-419f-a6a7-df9c091e268b%7D.xpi!/background.js`. So it can be different for everyone and change if you reinstall it, but it doesn't represent any private information or anything like that.

You can find it by typing `WebExtensionPolicy.getByID("{446900e4-71c2-419f-a6a7-df9c091e268b}").extension.uuid` in the browser console. The parameter passed to that method, {446...} is the extension's actual ID rather than the CID. So it's the one named in applications.gecko.id in the extension's manifest

**Comment by OsakaWebbie** [comment] 2021-10-01 23:42
Thanks for the clarification, although it's unrelated to the main point.
As for that main point, are you still getting the errors in your case?

**Comment by aminomancer** [comment] 2021-10-02 23:28
Yeah, massive numbers of these
```
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 4 background.js:3558
    send moz-extension://c1ea5f85-7682-4d41-86cf-4946657a717e/background.js:3558
```

**Comment by OsakaWebbie** [comment] 2021-10-03 02:49
Hopefully a BitWarden developer will take notice here.

**Comment by eliykat** [comment] 2021-11-24 01:24
Closing as a duplicate of #1208. Please refer to that Issue for any updates or further discussion.

**Closed by eliykat** 2021-11-24 01:24 UTC
