### ISSUE TITLE
Firefox restyle has made the extension box tiny

### ISSUE THREAD

**Issue by EmSixTeen** [bitwarden/browser#2422] opened 2022-02-28 19:44 UTC
### Steps To Reproduce

1. Click on the extension icon in the Firefox toolbar
2. .. See how little screen real estate is used

### Expected Result

I expect to have better use of screen real estate like before.

I'd also expect to:

- have the option to resize the extension box using drag handles
- have an option in Settings for the height of the box

### Actual Result

The box is small.

### Screenshots or Videos

![bitwarden-20220228](https://user-images.githubusercontent.com/149746/156048154-0b0c5368-03a4-4966-a2a6-b2daf7a8e4ca.png)

Comparison of the extension box in Firefox and Edge.

### Operating System

Windows

### Operating System Version

Win 10 20H2

### Web Browser

Firefox

### Browser Version

98.0b9 (64-bit)

### Build Version

Version: 1.56.6

**Comment by djsmith85** [comment] 2022-02-28 19:49
Closing as a duplicate of https://github.com/bitwarden/browser/issues/2418

**Closed by djsmith85** 2022-02-28 19:49 UTC
Labels: bug
