### ISSUE TITLE
No items found when searching: error: cannot decrypt

### ISSUE THREAD

**Issue by JeremyMahieu** [bitwarden/browser#2372] opened 2022-02-12 18:14 UTC
### Steps To Reproduce

Don't know what triggers it, just start using it and fill in your master password.

### Expected Result

Expect items to be found.

### Actual Result

When searching something nothing will be found. Every item in the "My Vault" list says "error: cannot decryp".

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/23409814/153723043-edcb5255-cfea-4b78-818e-d3182eb3e2c0.png)

### Additional Context

After restarting the browser it's fixed. Started happening a few days ago when I also noticed a different color design.

### Operating System

Windows

### Operating System Version

Windows 10 Pro 21H1

### Web Browser

Chrome

### Browser Version

Version 98.0.4758.82 (Official Build) (64-bit)

### Build Version

1.56.1

**Comment by Hinton** [comment] 2022-02-12 21:03
Closed as duplicate of https://github.com/bitwarden/browser/issues/2366.

Please upgrade the extension to the latest version which should resolve this issue.

**Closed by Hinton** 2022-02-12 21:03 UTC
Labels: bug
