### ISSUE TITLE
Vault is getting locked automatically even though it is kept on `NEVER`

### ISSUE THREAD

**Issue by FahimFBA** [bitwarden/browser#2349] opened 2022-02-11 09:11 UTC
### Steps To Reproduce

1. Go to Bitwarden chrome extension
2. Install it
3. Log in to your account
4. Setup the Vault Timeout to **NEVER**
5. It would get locked automatically after some time again and again

### Expected Result

It should not get locked after setting the timeout to **NEVER**

### Actual Result

The vault is getting locked after some minutes automatically again and again.

### Operating System

Windows

### Operating System Version

Windows 11 VERSION 21H2

### Web Browser

Chrome

### Browser Version

Version 98.0.4758.82 (Official Build) (64-bit)

### Build Version

1.56.0

**Comment by sander732** [comment] 2022-02-11 10:03
have you tried to reinstall the extension?

**Comment by fengkaijia** [comment] 2022-02-11 10:16
I think this has been fixed with https://github.com/bitwarden/jslib/pull/667.

**Comment by Gijs735** [comment] 2022-02-11 10:18
I also have this problem every browser restart. Really annoying.

Windows 10 Pro, OS Build 19044.1466. Google Chrome Version 98.0.4758.82.

**Comment by FahimFBA** [comment] 2022-02-11 10:19
> have you tried to reinstall the extension?

Yes, I did. That didn't solve the issue at all.

**Comment by djprmf** [comment] 2022-02-11 10:38
Same issue,
Reinstall didn't work. Install the latest 1.56.2 also didn't work.
Tested in two different Chromium based browsers (Chrome and Brave). Same issue in both.

**Comment by dtantono** [comment] 2022-02-11 11:37
Yes, this problem happened on MS Edge for Linux.

**Comment by cscharf** [comment] 2022-02-11 13:57
Thank you for the report, this is a duplicate of https://github.com/bitwarden/browser/issues/2337 and will be resolved in an upcoming release. The development is working on getting additional fixes buttoned up for this issue.

**Closed by cscharf** 2022-02-11 13:57 UTC
Labels: bug, duplicate
