### ISSUE TITLE
URL with Never Match Detection doesn’t work

### ISSUE THREAD

**Issue by Heshmatkhah** [bitwarden/browser#1610] opened 2021-02-14 08:12 UTC
## Steps To Reproduce

1. In a website with multiple subdomains, I wrote a regex in order to use autofill for all subdomains (**Login1**).
    `https?://[\w\.]+\.mydomian\.com/`
2. some subdomains of that site don't use that login information so I add a `Never` URL Match Detection.
    `https://diff1.mydomian.com`
3. Then I add a login for that specific subdomain (**Login2**).
4. The Bitwarden Extension still suggesting **Login1** for the excluded subdomain in addition to the new login I added (**Login2**).

## Expected Result
The extension should not suggest **Login1** for the excluded subdomain.

## Actual Result

The Bitwarden Extension still suggesting **Login1** for the excluded subdomain in addition to the new login I added (**Login2**).

According to Documentation:

> Selecting Never will prompt Bitwarden to never offer auto-fill for the Login item.

## Environment

- Operating system: Windows 10, Mac OS BigSure
- Browser: Firefox 85.0, Chrome 88.0
- Build Version: 1.48.1

**Comment by gdw2** [comment] 2021-03-25 15:35
https://github.com/bitwarden/browser/issues/761

**Comment by adamluzsi** [comment] 2021-05-05 15:24
The "Never" URL matcher options feel like a solution to a different issue.

If I understand correctly, the current "never" URL matcher do the following:
When the user has multiple accounts for the same site,
the user can set the URL matching logic to "never" 
and hide them from the auto-fill search suggestion.

From UX's point of view, this misleads me a bit, as I would assume "never" would prevent matching a URL when other rules would accept it.
I can't think of a scenario, where the "never" option is not replaceable by simply removing the URL matcher line.

I would either suggest changing the behavior of "never" URL matcher.
e.g:
```
- match-1 
- match-2
- never-1
- match-3
- never-2

currently interpreted as 
match-1 OR match-2 OR match-3 OR never-1 OR never-2

expected interpretation:
(match-1 OR match-2 OR match-3) AND never-1 AND never-2
```

For example, to say bitwarden password is OK for `vault.bitwarden.com` but should never match `community.bitwarden.com`:

<img width="316" alt="image" src="https://user-images.githubusercontent.com/2897081/117152197-169f6800-adba-11eb-84dc-a6ba2e93d1ac.png">

Most end-user don't know regexp to understand that they need to exclude subdomains with them.

It is also possible to introduce "exclude" as a new feature, so the users can use the current matcher types, and there would be a "exclude" flag next to them, which makes them interpreted as opposite.

```
- match-1 
- match-2
- [exclude] match-3
- match-4
- [exclude] match-5

expected interpretation:
(match-1 OR match-2 OR match-4) AND NOT (match-3 OR match-5)
```

This way, backward compatibility is guaranteed with the "never" option, while people who want to exclude subdomains also have a regexp free option.
And maybe as a nice to have, the "never" option could receive a new public name, like "note" or something that express clearly its true goal.

Thanks for the hard work @kspearrin!

**Comment by eliykat** [comment] 2021-08-02 03:35
I'm closing this as a duplicate of #761 - refer to that issue for the explanation of the current logic. If you'd like to request a change in how the "Never" option works, please create a feature request on our Community Forums (see links below).

---

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

If you want to make a feature request, please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

**Closed by eliykat** 2021-08-02 03:35 UTC

**Comment by luckman212** [comment] 2022-01-11 19:07
@eliykat but #761 is also closed. Is there a current open issue / FR for the "never" match to work as an override as requested?

**Comment by eliykat** [comment] 2022-01-12 00:56
Hi @luckman212, there is no open issue, but if you'd like to request a change in this behaviour then you can lodge a feature request on our forums. See my [previous post](https://github.com/bitwarden/browser/issues/1610#issuecomment-890686785) for details on how to do this. I just did a quick search but couldn't find an open thread, so you may have to create one. You can post a link here for visibility.

**Comment by luckman212** [comment] 2022-01-12 15:54
@eliykat Ok, fair enough. I created a Feature Request:

[Adjust or supplement behavior of "Never URLs" matching algorithm - Bitwarden Community Forums](https://community.bitwarden.com/t/adjust-or-supplement-behavior-of-never-urls-matching-algorithm/36948)
