### ISSUE TITLE
Extension doesn't autofill the password field

### ISSUE THREAD

**Issue by mariandomanik** [bitwarden/browser#114] opened 2017-03-22 22:16 UTC
On this website
[https://ib.slsp.sk/main/main.do](https://ib.slsp.sk/main/main.do) (check English on the left if needed)

The Login field is filled correctly but the password field remains blank.

**Comment by mariandomanik** [comment] 2017-03-23 10:25
Tested on Firefox 53b5 and Chrome 57.0.2987.110, same results.

**Comment by Primokorn** [comment] 2017-03-23 10:50
I think it's a bad coded website. I already see this issue on different websites and I had the same issue with Lastpass.
Not sure if there's something to fix on our side.

**Comment by mariandomanik** [comment] 2017-03-23 10:54
Lastpass extension fills both fields correctly. However it's true that even Firefox password manager doesn't recognize these fields as login/password and doesn't offer to save the password and LastPass asked to save the password everytime I logged in. Bitwarden unfortunately doesn't even fill it.

**Comment by kspearrin** [comment] 2017-03-23 14:57
I just tested this and bitwarden appears to be filling the password field correctly, however, the website then somehow removes it. You can see a quick flash of the password field being populated and then it goes back blank.

**Comment by kspearrin** [comment] 2017-03-23 14:59
Another interesting discovery, if you highlight the password field first, enter a single character, then do the autofill it works correctly. There is something going on in this website that is trying to control the password field.

**Comment by jcreigh** [comment] 2017-03-24 09:52
Very odd. The website is definitely doing something to the password field. If you set the field to something via console, and then click on the field, or tab to it from the username, it gets cleared and spits out an error. Try it yourself, set the value and then click on the field:

```javascript
document.getElementById("pass").value = "foo";
```

The field has a bunch of event listeners pointing deep within a very heavily obfuscated javascript file, and removing the event listeners fixes it.

After much prodding, it seems to be caused by sending the `keydown` and then `keyup` events _after_ setting the value. It works as expected if you do `keydown`, and then set the value, and then do `keyup`. (Or if you don't do `keydown` or `keyup` and you just do `input`).

https://github.com/bitwarden/browser/blob/02dc3609b42d9875b747ee32161a3c6b98b45b85/src/content/autofill.js#L817

Works:

```javascript
var el = document.getElementById("pass");
el.dispatchEvent(new Event('keydown', {bubbles: true}));
el.value = "foo";
el.dispatchEvent(new Event('keyup', {bubbles: true}));
```

Doesn't work (replicates behavior):
```javascript
var el = document.getElementById("pass");
el.value = "foo";
el.dispatchEvent(new Event('keydown', {bubbles: true}));
el.dispatchEvent(new Event('keyup', {bubbles: true}));
```

But this is definitely a strange quirk of this specific website.

**Comment by mariandomanik** [comment] 2017-03-26 19:25
Is it possible this is meant to be a security feature, for example to prevent brute force?

**Comment by kspearrin** [comment] 2017-03-26 22:07
@mariandomanik No idea, but if it is, that is a pretty terrible solution.

**Comment by kspearrin** [comment] 2017-09-29 02:08
Nothing we can really do here. Closing.

**Closed by kspearrin** 2017-09-29 02:08 UTC
