### ISSUE TITLE
error: cannot decrypt on 1.56.0

### ISSUE THREAD

**Issue by mateuszkozakiewicz** [bitwarden/browser#2334] opened 2022-02-11 02:46 UTC
### Steps To Reproduce

1. Login inside the extenstion
2. Setup PIN with lock on browser restart
3. Restart the browser
4. Unlock with PIN
5. Go to My Vault -> Login and notice lots of error: cannot decrypt

### Expected Result

Decrypt was successful

### Actual Result

error: cannot decrypt

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/8735263/153529729-a1600b2f-02c9-4947-953f-fd6549bd273c.png)

### Additional Context

To fix the issue until next restart a manual sync is required inside the extension

### Operating System

Windows, Linux

### Operating System Version

Windows 11, Linux 5.16.8-arch1-1

### Web Browser

Vivaldi

### Browser Version

5.1.2567.39

### Build Version

1.56.0

**Comment by Tonux599** [comment] 2022-02-11 02:49
Can confirm this bug on Chrome 98.0.4758.80 on Linux and Chrome 97.0.4692.99 on Windows 10

**Comment by Clonkex** [comment] 2022-02-11 02:58
Confirmed on Chrome 97.0.4692.71 on Windows 10. A vault sync fixed it for me, although the new version is even slower than it used to be.

**Comment by lemonnuggets** [comment] 2022-02-11 03:02
Confirmed on Brave 1.35.101 Chromium: 98.0.4758.87 (Official Build) (64-bit) and Windows 11. Also can confirm that the vault sync fixes it and the new version is much slower than previous versions.

**Comment by nickuc** [comment] 2022-02-11 03:19
Confirmed on Brave 1.35.100 Chromium: 98.0.4758.87 (Versão oficial) 64 bits and Ubuntu 20.04.1

**Comment by tdharris** [comment] 2022-02-11 03:28
Confirmed on Brave `1.35.101` (Chromium `98.0.4758.87`) on Windows 10. Bitwarden Version `1.56.0`. It happened to me just logging in. I can also confirm the vault sync fixes it for this session so far.

**Comment by fengkaijia** [comment] 2022-02-11 03:28
+1 on Chrome 98.0.4758.80 (Official Build) (64-bit) on Ubuntu 20.04.  Disable and then enable the plugin (then login again) fixed for me.

**Comment by Roman52** [comment] 2022-02-11 05:37
+1 Version 98.0.4758.80 (Official Build) (x86_64) Mac OS Catalina

**Comment by dan-il** [comment] 2022-02-11 07:01
+1 Chrome Version 98.0.4758.82 on Windows 11, Bitwarden Version: 1.56.0

**Comment by dejwid** [comment] 2022-02-11 07:53
+ Chrome Version 98.0.4758.80 on MacOS Big Sur 11.6.2

**Comment by SchneiderSam** [comment] 2022-02-11 07:56
+1 Version 98.0.4758.82 (Offizieller Build) (64-Bit)

**Comment by brdtheo** [comment] 2022-02-11 08:06
+1 chrome version 98.0.4758.80 on ubuntu 20

**Comment by cscharf** [comment] 2022-02-11 08:11
We have been able to reproduce this, and then we're not able to. The team has been working on this one all night and while we have a decent idea of root cause, we're still shooting in the dark at the moment. We'll continue working on resolving this ASAP.

**Comment by kdaveid** [comment] 2022-02-11 08:11
+1 on Chromium: 98.0.4758.87 (official build) (64-Bit) BRAVE

**Comment by cscharf** [comment] 2022-02-11 08:20
Ways we were able to reproduce this:

whatever tab you’re on.

1. open popup
2. unlock
3. close popup
4. wait for it to lock (set vault timeout to immediate, action: lock)
5. refresh tab
6. open popup, unlock
7. observe decryption error

it’s only an error in the My Vault tab. once you click into an item, it has all the info there.

We've found that we get ourselves into a state where we can no longer reproduce it (bad for us, good for you) after doing some JavaScript debugging, it seems to be a race condition of some kind and when doing that it preventing us from being able to reproduce. We're trying to track down the source still but that may help some folks in the meantime.

Your vault is still being decrypted, it is just the My Vault component in this instance, as displayed in the list index that fails (with that error). You can still click to view those items if need be and other functions seem to be working.

**Comment by Clonkex** [comment] 2022-02-11 09:08
> Your vault is still being decrypted, it is just the My Vault component in this instance

Not sure if this is what you're talking about, but for me, it happened immediately upon clicking the extension icon. So I would click the extension icon, the popup would appear (selected on the Tab tab) and it would show exactly eight "cannot decrypt" entries, no matter whether the page I was viewing had eight saved passwords or not. I didn't have to go to the My Vault tab to see the issue. But the Tab tab is internally handled by the My Vault component?

Not sure if this affects anything but I do currently have 501 tabs open across two screens. I also saw the behaviour on both my home computer and my work computer within a few minutes of each other (presumably the extension was updated on both computers within a short timeframe). After updating it made me sign in with my master password (which surprised me since I have it set to only sign out upon browser close) and then I saw the "cannot decrypt" entries.

**Comment by DimitriDR** [comment] 2022-02-11 09:24
Same issue on macOS Monterey, Chrome 98.0.4758.80.

**Comment by dejwid** [comment] 2022-02-11 09:28
Locking and unlocking the vault solved the issue for me. 
Maybe it's just a one-time-thing after a chrome update..

**Comment by theMasix** [comment] 2022-02-11 09:32
Solved for me too! @dejwid

**Comment by mateuszkozakiewicz** [comment] 2022-02-11 09:53
> Locking and unlocking the vault solved the issue for me. Maybe it's just a one-time-thing after a chrome update..

For me this works only until browser restart which allows me to reproduce the issue 100% of the time. Locking & unlocking the has the same effect as triggering vault sync.

**Comment by fengkaijia** [comment] 2022-02-11 10:14
> You can still click to view those items if need be and other functions seem to be working.

In my case, the item was not clickable, there was an error in red at the bottom when clicking any item, and it stayed on the listing page.

Unfortunately, I cannot recall the text of that error message as mine is fine now after disabling/enabling the plugin and re-login.

**Comment by mateuszkozakiewicz** [comment] 2022-02-11 11:00
For me 100% sure way to have the issue occur is:
1. Close Vivaldi browser
2. Start it again
3. Enter PIN/master password
4. Issue is present - error: cannot decrypt

Clean install only change in extension settings is 
- autofill on page load enabled
- unlock with PIN with automatic lock on browser restart

**Comment by Hinton** [comment] 2022-02-11 11:05
@mateuszkozakiewicz Thanks for the instructions. It seems I needed to enable autofill on page load!

**Comment by Ksenofanex** [comment] 2022-02-11 11:34
Can also confirm on 1.56.0 with Brave 1.35.101 Chromium: 98.0.4758.87, syncing the vault temporarily fixes the problem. However, when I lock the vault and login again, the problem persists. Also, there's a significant performance issue while accessing the accounts and switching back and forth.

**Comment by Hinton** [comment] 2022-02-11 11:43
We've identified the problem, and will have QA take a look at it in a bit.

A temporary workaround is to turn off `autofill on page load`, while we work on getting a new release published.

**Comment by knoriy** [comment] 2022-02-11 12:15
+1 on pop-os! 20.04, Google Chrome v 97.0.4692.99

**Comment by knoriy** [comment] 2022-02-11 12:17
> Same Issue, Chrome 98.0.4758.80. Locking manually seems to have resolved issue, but haven't tried restarting chrome yet.

Can confirm that looking manually temporarily fixed the issue.

+1 on pop-os! 20.04, Google Chrome v 97.0.4692.99

**Closed** 2022-02-11 12:17 UTC
Labels: bug

**Comment by Goldenflamer** [comment] 2022-02-11 13:00
> > Same Issue, Chrome 98.0.4758.80. Locking manually seems to have resolved issue, but haven't tried restarting chrome yet.
> 
> Can confirm that locking manually temporarily fixed the issue.
> 
> +1 on pop-os! 20.04, Google Chrome v 97.0.4692.99

I also can confirm that

**Comment by gtmadev** [comment] 2022-02-11 17:58
Why is this issue and the duplicate both closed? I can confirm this issue STIL exists.

**Comment by mateuszkozakiewicz** [comment] 2022-02-11 18:01
Keep in mind the issue was fixed but release to Chrome Extenstion store takes at least several hours the version available is still only 1.56.1 
https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb?hl=en
From my understanding it is Google who must review the changes before they are made available

**Comment by petruccigp** [comment] 2022-02-11 21:06
After some initial panicking, this solved it for me as well. Thanks!

> Locking and unlocking the vault solved the issue for me. Maybe it's just a one-time-thing after a chrome update..

**Comment by Clonkex** [comment] 2022-02-13 03:21
Just got the update to 1.56.3 and can no longer replicate 👍 

Bet that was a stressful event for you guys!
