### ISSUE TITLE
Password History Bug

### ISSUE THREAD

**Issue by gui-milky** [bitwarden/browser#480] opened 2018-01-13 10:55 UTC
![image](https://user-images.githubusercontent.com/22163948/34905410-59a493ba-f886-11e7-8db6-ffbe972d9a86.png)

The History gone after pasting Password in website.
No matter how many time I generate the history is gone.
---
I just lost my school Password because of it so I hope another person won't suffer like me
Just my fault

**Comment by kspearrin** [comment] 2018-01-13 14:23
This was a bug in old versions of the extension, but should have been fixed with more recent version. What version are you using?

**Comment by gui-milky** [comment] 2018-01-14 01:48
1.23.0

**Comment by kspearrin** [comment] 2018-01-14 13:51
Hmm, I am not able to reproduce it. Does it happen every time?

**Comment by gui-milky** [comment] 2018-01-14 13:58
I can reproduce it by this way
Go to Website and use right-click > bitwarden > Auto-Fill "2" time
![image](https://user-images.githubusercontent.com/22163948/34916600-6caaf650-f969-11e7-8433-9735dd14f881.png)

**Comment by kspearrin** [comment] 2018-01-15 02:25
That does not seem to work for me. I can still always access my password history without issue.

**Comment by gui-milky** [comment] 2018-01-15 02:58
Try Intentional Wrong Login with Bitwarden
I can reproduce a lot.

**Comment by kspearrin** [comment] 2018-01-15 04:45
Ok, got it this time. Error:



Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: item in $ctrl.history | orderBy: 'date':true, Duplicate key: object:61, Duplicate value: {"password":"xxxxxxxxxxxxxxxx","date":yyyyyyyyyyyyy}

**Comment by kspearrin** [comment] 2018-01-16 02:05
Fixed for next version. Thanks.

**Closed by kspearrin** 2018-01-16 02:05 UTC
