### ISSUE TITLE
ctrl-u not working when entering passwords

### ISSUE THREAD

**Issue by nesqi** [bitwarden/browser#835] opened 2019-01-16 09:54 UTC
It is pretty much standard that you can completely clear your current input with the ctrl-u shortcut. This is not working when inputting passwords. Since you don't see what you have entered (normaly only dots are shown) it's very convenient with a way to clear the input and start over from scratch.

**Comment by kspearrin** [comment] 2019-01-16 13:10
I am testing Ctrl+U on my windows machine here and it does not clear input fields on any webpage. It just opens the HTML source of the page. What OS/browser is this expected to work this way on?

**Comment by nesqi** [comment] 2019-01-16 14:52
Not any input field, only password inputs.
After some research I think this might be more common on Linux/Unix.
I'm running Linux and Chromium.

**Comment by kleinfreund** [comment] 2019-03-22 18:12
FYI the origin of this feature is GNU Readline. `Ctrl-U` clears the line content and copies it to the clipboard. `Ctrl-Y` pastes it again.

It is by no means standard outside of the realm of Linux terminals.

**Comment by nesqi** [comment] 2019-05-15 13:21
I would be happy with ANY key combo for clearing the input field.

**Comment by nesqi** [comment] 2019-05-15 13:26
And then I found one!
Ctrl-z

**Comment by eliykat** [comment] 2021-02-17 01:37
I'm closing this issue as it appears the originally posted problem has been resolved. If this continues to be an issue, please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by eliykat** 2021-02-17 01:37 UTC
