### ISSUE TITLE
Safari Extension: crashes all browser

### ISSUE THREAD

**Issue by gleydsonsoares** [bitwarden/browser#1705] opened 2021-03-15 12:54 UTC
Apple debug log:

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Enabled Web Extensions:
com.bitwarden.desktop.safari (LTZ2PFU5D6) (Version: 1.49.0 - Display Version: 1.49.0) Bitwarden - Free Password Manager
 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '<cert(0x139be0ce0) s: dnsleaktest.com i: R3> does not conform to NSSecureCoding'
terminating with uncaught exception of type NSException
abort() called

How to reproduce:

Enable Bitwarden extension on Safari and open the site: https://dnsleaktest.com and start a "Standard test".

I have noticed it comes happening after update to latest 1.49.0

**Comment by cscharf** [comment] 2021-03-15 13:47
This you, this is a duplicate of #1694 , however the additional detail is helpful, much appreciated. Closing this now, please follow #1694 for updates/resolution, workarounds, etc. as they become available.

**Closed by cscharf** 2021-03-15 13:47 UTC
Labels: duplicate
