### ISSUE TITLE
Unlocking vault fails, but login works

### ISSUE THREAD

**Issue by zyphlar** [bitwarden/browser#1404] opened 2020-09-22 17:14 UTC
## Describe the Bug

Before about a week ago, unlocking my password vault worked normally. In the last week however (during which I invited my wife to an Organization with me and shared some of my passwords to that organization in the Default Collection) unlocking my vault has become almost impossible and every time I have to log out and re-log-in. I've confirmed that the password is the same each time, I'm not simply mistyping it.

## Steps To Reproduce

Video here: https://youtu.be/ndI-xeZf3dA note in this video I'm copy-pasting my password each time so there's zero chance of typos.

1. Get your vault to be locked, either by reopening the browser or by manually locking the vault via Settings > Lock Now.
2. Attempt to unlock with your master password
3. Notice it accuses you of typing the wrong password
4. Log out, and log back in with the same password
5. Notice it logs in just fine with the same password

## Expected Result

Unlocking your vault always works

## Actual Result

Unlocking my vault almost never works lately.

## Screenshots or Videos

https://youtu.be/ndI-xeZf3dA

## Environment

- Operating system: Ubuntu 20.04
- Browser: Firefox 80.0.1
- Build Version: 1.46.1

**Comment by jarredkenny** [comment] 2020-09-23 11:06
I am also experiencing the same behaviour, exactly as @zyphlar has described. 

OS: Fedora 32
Browser: Chrome 85.0.4183.121

**Comment by nbolten** [comment] 2020-09-24 20:04
Can confirm this behavior for both Firefox and the desktop client. Version info:

### Firefox browser extension
Version: 1.46.1
Firefox: 80.0.1
OS: Ubuntu 20.04.1

### Desktop client
Version: 1.22.1
OS: Ubuntu 20.04.1

**Comment by cscharf** [comment] 2020-09-28 17:12
Hi all, my team and I are unable to reproduce this at the moment testing with the given variables and information above. Some additional questions that should help in troubleshooting:

* Are you self-hosted or using Bitwarden Cloud?
* If self-hosting, what server version are you using?

Thanks in advance!

**Comment by Jenjen1324** [comment] 2020-10-02 10:59
We have the same issue across multiple platforms (Windows/Mac/Linux Firefox & Chrome). It is happening inconsistently.

We are using the official self-hosted Bitwarden server.

We have an access control list that returns 403 Forbidden for disallowed connections (outside VPN/Office) which might be relevant. We have a hunch that this response might trip up the extension. We are expecting that the vault should still be unlockable when the host is not accessible and not break in this strange fashion (Incorrect Masterpassword).

**Comment by cscharf** [comment] 2020-10-02 14:50
There are some known issues for the latest clients against that and older versions of the server... updating to the latest version of Bitwarden server _should_ (operative word here) resolve this behavior.

**Comment by Jenjen1324** [comment] 2020-10-02 15:00
> There are some known issues for the latest clients against that and older versions of the server... updating to the latest version of Bitwarden server _should_ (operative word here) resolve this behavior.

Funnily enough we just upgraded the server to 1.37.1 a few moments ago. So far, it's no longer reproducible but since it was so inconsistent I can't be sure if it's been resolved.

**Comment by cscharf** [comment] 2020-10-02 16:29
Thanks for the update @Jenjen1324 , for now I'm going to close this out, we had similar issues reported by several other folks who were self-hosted as well and updating resolved the issue. This was due to some of the authentication flow changes we needed to make overall to support SSO.

If it happens again please feel free to re-open this issue.

**Closed by cscharf** 2020-10-02 16:29 UTC

**Comment by zyphlar** [comment] 2020-10-14 00:37
Thanks all, I can confirm that upgrading my self-hosted bitwarden from 1.15.1~ynh2 to 1.16.3~ynh1 fixed the issue.

**Comment by houserockr** [comment] 2021-07-05 11:59
I'm having the exact same issue, even after updating the bitwarden image(s).

**Client**
- OS: MacOS Big Sur 11.4
- Browser: Chrome 91.0.4472.114 (Official Build) (arm64)
- Plugin Version: 1.51.0

**Server**
- OS: Debian 9.13
- Bitwarden Info
```
bitwarden.sh version 1.41.3
Docker version 19.03.15, build 99e3ed8919
docker-compose version 1.23.2, build 1110ad01
```
I just ran `bitwarden.sh updateself` and `bitwarden.sh update` and `bitwarden.sh restart`

Login works as expected, unlock fails.
My gut feeling tells me it has something to do with SSL. Is that possible?
Is there any way to see what's going on underneath? Like an increased log level or a console?
The only error I'm getting is "unlock failed".

**Comment by houserockr** [comment] 2021-07-05 12:43
Now that's interesting!
I just upgraded my debian from stretch to buster and now it works.
```
bitwarden.sh version 1.41.3
Docker version 20.10.7, build f0df350
docker-compose version 1.23.2, build 1110ad01
```
Everything else untouched.
