### ISSUE TITLE
Firefox developer is not syncing

### ISSUE THREAD

**Issue by frangiskos** [bitwarden/browser#1192] opened 2020-03-31 12:08 UTC
When you install bidwarden extension on firefox developer edition (OS: Windows 10), the vault is not syncing. Also tried the following without success:
- Try "Settings" --> "Sync" --> "Sync Vault now"
- Try uninstalling and reinstalling the extension 
On the standard firefox for windows syncing works without problems.

**Comment by lupa18** [comment] 2020-04-16 15:27
Same here with Firefox 75

**Comment by setyb** [comment] 2020-04-16 22:31
@lup18 Are you using Firefox 75 developer release or general release?

**Comment by frangiskos** [comment] 2020-04-17 03:56
I checked again today and is working now. I don't know if an update to firefox or to the extension has fixed the problem

**Comment by lupa18** [comment] 2020-04-17 11:51
@setyb Firefox general release 75.0 (64-bit) (Linux)

**Comment by setyb** [comment] 2020-04-18 01:23
@lupa18 Although I don't doubt it's broken for you, if Bitwarden sync was completely broken with the general release of Firefox, there would likely be hundreds of issues posted.

Are you syncing with the default Bitwarden cloud (Azure) or with your own cloud?

**Comment by lupa18** [comment] 2020-04-23 14:04
Sorry for the delay. I'm using Bitwarden as is, with default cloud.
 
Firefox version is 75.0 and BW plugin version is 1.43.4

I checked again, close and re login, and the problem persist.

I'm not sure how can I debug this.

**Comment by andryyy** [comment] 2020-05-06 14:07
Same here. Any way to debug this?

**Comment by cscharf** [comment] 2020-05-06 15:22
Just went through some tests on FF 76.0, Bitwarden plugin 1.43.4, and was unable to reproduce this, however if you would like to debug this can be done via Firefox's developer tools:

1. Go to about:debugging#/runtime/this-firefox
2. Next to the Bitwarden extension, click *Inspect* button
3. Use the Network tab to monitor network traffic when clicking "Sync Now" button, OR
4. Use the Console / Debugger tabs accordingly to see if there are script errors or other issues occurring

**Comment by andryyy** [comment] 2020-05-07 05:45
We installed 76.0 yesterday on client side (they bought a 11 client license for self hosting) and will keep an eye on it. :)

Happens occasionally, iirc, but a click on "Sync now" always works fine.

It _seems_ to be happening with collections shared within the organisation only.

**Comment by cscharf** [comment] 2020-05-07 12:38
Great, please let us know if it continues to be an issue... the bit regarding shared collections within the organisation is good to know as well regarding reproduction steps if necessary. Closing this issue for now.

**Closed by cscharf** 2020-05-07 12:38 UTC

**Comment by lupa18** [comment] 2020-05-07 13:16
In my case, this message is repeating all time:
```
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:802
    normalizeStorageError resource://gre/modules/ExtensionStorageIDB.jsm:802
    method chrome://extensions/content/child/ext-storage.js:273
    AsyncFunctionThrow self-hosted:699
Unchecked lastError value: Error: An unexpected error occurred background.js:20769
    get browserStorage.service.ts:25
```
Extra config detail is that I have 2FA enabled.

**Comment by cscharf** [comment] 2020-05-07 13:41
@lupa18 , there may be something in this similar bug report filed with Mozilla directly that can help you with that particular issue (seems many plug-ins have been affected): https://bugzilla.mozilla.org/show_bug.cgi?id=1624586
