### ISSUE TITLE
Bitwarden chrome extension hangs on adding anything to notes section/custom field for a "new password"

### ISSUE THREAD

**Issue by ashutoshsaboo** [bitwarden/browser#2189] opened 2021-11-20 06:57 UTC
### Steps To Reproduce

1. Go to any new site for which password is not already saved in bitwarden. 
2. Save password to bitwarden, as soon as it's saved - at the same time (this is important, not sure if this happens for existing saved passwords too but i observed this to be happening for new passwords as they are saved) edit the password and add something to notes section/add any new custom field. Extension hangs for some time and the updated text is reflected after some delay. This is happening for Brave browser. Been observing this behaviour since quite some time. 
2. If you pop out the extension, and then edit notes/add any new custom field then it doesn't seem to hang though. 

### Expected Result

Chrome extension on brave browser should not hang on adding anything to notes/adding a new custom field at the same time a new password is saved. 

### Actual Result

Chrome extension on brave browser hangs on adding anything to notes/adding a new custom field at the same time a new password is saved. 

### Operating System

macOS

### Operating System Version

MacOS Big Sur v11.6

### Web Browser

Brave

### Browser Version

1.31.88

### Build Version

1.54.0

**Comment by SergeantConfused** [comment] 2021-11-22 18:51
Hi @ashutoshsaboo,

I tested this on macOS 12.0.1, Bitwarden 1.54.0, and Brave 1.32.106, and I was unable to reproduce this behaviour. Can you please uninstall your Bitwarden browser extension and remove all leftover data (https://bitwarden.com/help/article/data-storage/), reboot, install it anew, and test this once more?

If you continue to experience the same behaviour, please get in touch with us using this form: https://bitwarden.com/contact/ and we'll proceed in assisting you with this.


Thank you in advance,

**Comment by ashutoshsaboo** [comment] 2021-11-22 18:56
I can try that, can you add dir to cleanup for Brave Browser for macOS under Browser Extensions here - https://bitwarden.com/help/article/data-storage/ which I should be cleaning up? Brave dir is only mentioned under browser extensions for windows not mac

**Comment by eliykat** [comment] 2021-11-24 04:46
Are you using Bitwarden on an external screen? If so, it could be this issue: https://github.com/bitwarden/browser/issues/1854. That issue should be fixed in the upcoming December release.

If you still need to clear your local data, it should be located at `~/Library/Application\ Support/BraveSoftware/Brave-Browser/Default/Local\ Extension\ Settings/oghppmjlkcigcnejlnkppmneoalkdeih/`. The name of that last folder may be different if your extension ID is different. You can check your extension ID by going to `brave://extensions`, then checking the "ID" in the Bitwarden section.

If you need any further help, please contact our team using the contact link that @sso-bitwarden provided. Thanks!

**Closed by eliykat** 2021-11-24 04:46 UTC
Labels: bug

**Comment by ashutoshsaboo** [comment] 2021-11-24 06:05
Gotcha, you spotted the right thing @eliykat! I just tested it works swiftly when i move the browser window to mac desktop (i.e, even when the external screen is connected) as expected. As soon as I move the browser window to my external screen desktop, it starts lagging in performance as I mentioned above. Thanks for the prompt response!
