### ISSUE TITLE
Bitwarden extension disappears from Safari

### ISSUE THREAD

**Issue by kapitainsky** [bitwarden/browser#1847] opened 2021-05-15 10:51 UTC
## Describe the Bug

Safari Bitwarden extension is no more - without any apparent reason it disappeared after computer restart. It is no longer available on extensions' list.

<img width="904" alt="Screenshot 2021-05-15 at 11 50 00" src="https://user-images.githubusercontent.com/15635386/118357791-be175a00-b573-11eb-854f-b62baf496d96.png">

I have tried AppCleaner to uninstall completely BW  app and reinstalled it from Apple Store - no change.

I have tried this command in terminal:

```
pluginkit -mAvvv -p com.apple.Safari.web-extension
  (no matches)
```

## Environment

- Operating system: Intel based laptop running macOS 11.3.1
- Browser: Safari Version 14.1 (16611.1.21.161.6)
- Build Version: Version 1.25.1 (518)

**Comment by kapitainsky** [comment] 2021-05-15 11:44
additional info - it is only happening on account with my normal user (non-admin), when I login to another account (admin) bitwarden is available in Safari there

**Comment by prandelicious** [comment] 2021-05-16 19:57
It's also missing on my M1 Macbook Air. I tried uninstalling it, rebooted the laptop, and re-installed via App Store. Still, no luck. The extension is available and working on Chrome and Firefox (both arm64 versions) though, on the same machine.

**Comment by kapitainsky** [comment] 2021-05-16 21:06
It works for me in Firefox. Looking on amount of issues reported here regarding Safari despite what BW guys claim its Safari support is at the moment rather experimental. Clearly they have not cracked yet how to write working extension on macOS browser.

Still BW is great - I hope they will finally make it work reliably with Safari.

**Comment by kapitainsky** [comment] 2021-05-22 12:06
I have experimented with it again and interestingly when I add new macOS non-admin user BW extension is available in Safari there. So it is only user I am using. 

BW guys - is there anything I can check why it is not available for my user? Or better to wait for next desktop client release?

**Comment by tgreer-bw** [comment] 2021-05-22 19:47
> I have experimented with it again and interestingly when I add new macOS non-admin user BW extension is available in Safari there. So it is only user I am using. 
> 
> 
> 
> BW guys - is there anything I can check why it is not available for my user? Or better to wait for next desktop client release?

We recently had someone use Onyx to clear system caches and it allowed the extension to be enabled once more. We don't have exact details on why, but it may be worth a try.

**Comment by kapitainsky** [comment] 2021-05-22 21:39
it might solve my issue and I will definitely try but there must be some fundamental reason why BW extension is so flaky - other extensions I use just work across all accounts etc.

**Comment by prandelicious** [comment] 2021-05-23 04:41
I can confirm that clearing the cache via Onyx works. I can now see the Bitwarden plugin in Safari! Thanks!

**Comment by kapitainsky** [comment] 2021-05-23 05:25
Indeed it works and after running Maintenance from Onyx BW Safari plugin is back. Thank you. 

Now I wonder which cache is responsible for it - so next time I do not have to clean everything.

> 
> We recently had someone use Onyx to clear system caches and it allowed the extension to be enabled once more. We don't have exact details on why, but it may be worth a try.

**Comment by tgreer-bw** [comment] 2021-05-23 12:40
The last update was a major change in architectures for the extension, hopefully, no issues with delta updates going forward 👍

**Comment by kapitainsky** [comment] 2021-05-23 12:43
I think I can close this issue as at least there is some workaround. Hopefully in time things will get only better.

**Comment by kapitainsky** [comment] 2021-06-28 10:28
BTW - it is gone again and this time running Onyx maintenance does not help.

**Comment by eliykat** [comment] 2021-07-05 01:13
Closing as a duplicate of https://github.com/bitwarden/browser/issues/1696. Please direct any discussion to that thread.

**Closed by eliykat** 2021-07-05 01:13 UTC
