### ISSUE TITLE
TOTP not copying after selecting login item.

### ISSUE THREAD

**Issue by pradhyumk** [bitwarden/browser#2053] opened 2021-09-04 16:38 UTC
## Describe the Bug
When using the Bitwarden extension from the Chrome Web Store, the extension does not automatically copy the TOTP after clicking on the appropriate login from the extension.

## Steps To Reproduce
1. Go to a website login page for which you have a TOTP stored in Bitwarden
2. Click on the Bitwarden extension and select the suggested login card
3. Paste the contents from your clipboard.

## Expected Result
The expected result is the TOTP should be copied to your clipboard after selecting the login item from the extension if the item has TOTP. Also, if a custom value for the "Clear Clipboard" option is chosen, then the extension should clear the clipboard after the specified time.

## Actual Result
The TOTP is never copied to the clipboard. As a result, the clipboard is also not cleared after the specified time.

## Environment
Device: MacBook Pro (13-inch, M1, 2020)
OS: macOS Big Sur 11.5.2 (20G95)
Browser: Google Chrome 93.0.4577.63 (Official Build) (arm64)
Extension Version: Bitwarden 1.52.1
Application Version: Bitwarden 1.27.1 (531)

## Additional Context
There are only two extensions installed, the other being uBlock Origin. The extension works as expected on Windows 10 Enterprise x64 on Google Chrome with the latest version of Bitwarden (application and extension).

**Comment by snietzsche** [comment] 2021-09-07 17:22
Also having the same issue, with the same behavior:

Device: MacBook Pro (16-Inch, Intel, 2019)
OS: macOS Big Sur 11.14 (20F71)
Browser: Google Chrome 93.0.4577.63 (Official Build) (x86_64)
Extension Version: Bitwarden 1.52.1
Application Version: Bitwarden 1.27.1 (531)

**Note:** TOTP-Copy behavior works fine in Vivaldi 4.1.2369.21 (Stable channel) (x86_64) on the same system, so perhaps it's chrome-specific rather than a downstream chromium issue.

**Comment by daniefdz** [comment] 2021-09-08 16:33
I am having this issue in Brave:

Device: MacBook Pro (16-inch, 2019)
OS: macOS Big Sure 11.5.2
Browser: Brave Version 1.29.77 Chromium: 93.0.4577.63 (Official Build) (x86_64)
Extension Version: 1.52.1  Bitwarden 1.27.1

**Comment by eliykat** [comment] 2021-09-09 01:56
I've been able to reproduce this. Adding a short (50ms) timeout to closing the popup fixes it, although I'm not sure why - it's all synchronous code, so the popup should not be closing before the copy operation is complete. It's possible that Chrome/Chromium changed something about their clipboard implementation.

Can someone please confirm that other methods of copying to clipboard (e.g. clicking the "copy totp" icon from the list of logins) is not affected by this bug? That would confirm my testing that it's caused by closing the popup prematurely.

**Comment by pradhyumk** [comment] 2021-09-09 01:59
> Can someone please confirm that other methods of copying to clipboard (e.g. clicking the "copy totp" icon from the list of logins) is not affected by this bug? That would confirm my testing that it's caused by closing the popup prematurely.

The copy TOTP icon works fine for me.

**Comment by esiqveland** [comment] 2021-09-14 18:50
> Can someone please confirm that other methods of copying to clipboard (e.g. clicking the "copy totp" icon from the list of logins) is not affected by this bug? That would confirm my testing that it's caused by closing the popup prematurely.

Same problem when logging in. The copy TOTP icon in the list works fine.

Perhaps worth noting I only have this issue on my mac (google chrome).

**Comment by waynehaffenden** [comment] 2021-09-20 22:40
Same issue here, was working fine before the latest Google Chrome update so chances are they've changed something. If it helps I'm also running MacOS.

**Comment by raccettura** [comment] 2021-09-21 04:06
I've also seen the same thing break.  Seems to work in Firefox, so guessing this is Chrome specific.  I can manually copy it. But the automatic functionality broke.

**Comment by chrisrueger** [comment] 2021-09-21 07:16
Same here. 
- Chrome Version 93.0.4577.82
- MacOS 11.6

It worked until like 2 weeks ago. 

This was great feature. Not it is pretty annoying to have the extra clicks on the "Copy TOTP icon".

Could somebody review PR https://github.com/bitwarden/browser/pull/2067 please?

**Closed** 2021-09-21 21:36 UTC

**Comment by eliykat** [comment] 2021-09-26 23:26
The fix for this has been merged and will be in the next release (scheduled for October).
