### ISSUE TITLE
Bitwarden version 1.25.1(518) from macOS App Store not installing Safari extension

### ISSUE THREAD

**Issue by WadeMasshardt** [bitwarden/browser#1733] opened 2021-03-23 12:51 UTC
## Describe the Bug

Bitwarden version 1.25.1(518) from macOS App Store does not install the Safari extension

## Steps To Reproduce

1. Install Bitwarden app from macOS App Store
2. Follow instructions on https://bitwarden.com/help/article/install-safari-app-extension/
3. Open Safari

## Expected Result

The Bitwarden extension should appear in the list of available extensions Safari->Preferences->Extensions

## Actual Result

The Bitwarden extension does not appear in the list of available extensions Safari->Preferences->Extensions

## Environment

- Operating system: macOS Big Sur 11.2.3 (20D91)
- Browser: Safari 14.0.3 (16610.4.3.1.7)
- Build Version 1.25.1 (518)

**Comment by nikallass** [comment] 2021-03-23 17:09
Can reproduce this issue. Also extension in Safari dismissed.
BigSur 11.1 (20C69)
Safari 14.0.2 (16610.3.7.1.9)
Bitwarden 1.25.1 (518)

**Comment by cho-m** [comment] 2021-03-23 20:41
Is this the same issue being discussed in https://github.com/bitwarden/browser/issues/1718

**Comment by nikallass** [comment] 2021-03-24 06:15
> Is this the same issue being discussed in #1718

I think it is the same.
After reading the thread fixed as follows:
1) Downloaded App Cleaner
2) Deleted Bitwarden and all dependencies with App Cleaner.
3) Installed Bitwarden with App Store.

**Comment by cscharf** [comment] 2021-03-24 14:12
Hi @WadeMasshardt , thank you for your report, closing this item as a duplicate of #1718, please follow that thread for any updates, etc.

**Closed by cscharf** 2021-03-24 14:12 UTC
Labels: duplicate
