### ISSUE TITLE
Blank BitWarden Dropdown in Firefox

### ISSUE THREAD

**Issue by trparky** [bitwarden/browser#882] opened 2019-03-05 16:31 UTC
I just downloaded the latest version of BitWarden, version 1.39, and it appears that this new version is buggy. After some time of leaving BitWarden alone I cannot pull up BitWarden, all I get is a blank dropdown when I click on the BitWarden icon next to the address bar. I can get BitWarden to appear for the first few minutes of Firefox being open but after about five minutes BitWarden is unresponsive.

**Comment by kspearrin** [comment] 2019-03-05 16:42
are you using locking or anything like that? what happens after 5 minutes that changes things?

**Comment by kspearrin** [comment] 2019-03-05 16:42
also, what operating system and version of firefox are you using?

**Comment by trparky** [comment] 2019-03-05 16:45
Yes, I'm locking the session with the new PIN code option after five minutes. However even if I don't have the session lock after five minutes the extension goes unresponsive. I'm running Firefox version 65.0.2 on Windows 10 1809 (Build 17763.348).

**Comment by kspearrin** [comment] 2019-03-05 17:07
What if you change locking to 1 minute. Does that make the issue occur sooner?

**Comment by trparky** [comment] 2019-03-05 17:08
Even if I don't enable session locking the UI goes unresponsive. The only way to get a working BitWarden extension is to go back to the previous version.

**Comment by kspearrin** [comment] 2019-03-05 17:09
Unfortunately I cannot reproduce the problem. Can you try debugging the extension under `about:debugging` and see if there are any errors listed in the console?

**Comment by trparky** [comment] 2019-03-05 17:30
ERROR Error: "Uncaught (in promise): TypeError: can't access dead object
step@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/background.js:14051:47
[636]/crypto_service_awaiter</<@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/background.js:14052:9
[636]/crypto_service_awaiter<@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/background.js:14048:12
getKey@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/background.js:14121:16
hasKey/<@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/background.js:14248:27
[636]/crypto_service_awaiter</<@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/background.js:14052:71
[636]/crypto_service_awaiter<@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/background.js:14048:12
hasKey@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/background.js:14247:16
isLocked/<@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/background.js:15212:34
[636]/lock_service_awaiter</<@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/background.js:15182:71
[636]/lock_service_awaiter<@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/background.js:15178:12
isLocked@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/background.js:15211:16
canActivate/<@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/main.js:11441:34
fulfilled@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/main.js:11411:48
ZoneDelegate.prototype.invoke@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:79800:17
onInvoke@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:17646:24
ZoneDelegate.prototype.invoke@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:79799:37
Zone.prototype.run@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:79559:24
scheduleResolveOrReject/<@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:80298:29
ZoneDelegate.prototype.invokeTask@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:79832:17
onInvokeTask@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:17637:24
ZoneDelegate.prototype.invokeTask@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:79831:41
Zone.prototype.runTask@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:79604:28
drainMicroTaskQueue@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:80010:25
run@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:77316:22
notify/<@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:77333:30
flush@moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:68234:9
"
	resolvePromise moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:80240
	resolvePromise moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:80197
	scheduleResolveOrReject moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:80301
	invokeTask moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:79832
	onInvokeTask moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:17637
	invokeTask moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:79831
	runTask moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:79604
	drainMicroTaskQueue moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:80010
	run moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:77316
	notify moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:77333
	flush moz-extension://c317db63-657a-462f-9d0b-44d671b8b22c/popup/vendor.js:68234
 vendor.js:16071:5

**Comment by trparky** [comment] 2019-03-05 17:32
Every time I try to pull up BitWarden and I get the blank UI for it that error shows up in the Debug Console for the BitWarden extension.

**Comment by kspearrin** [comment] 2019-03-05 17:39
That error stack trace is badly formatted. Can you attach a screenshot?

**Comment by trparky** [comment] 2019-03-05 17:43
![image](https://user-images.githubusercontent.com/32105035/53825414-3caff000-3f44-11e9-9562-5182274fc563.png)

**Comment by kspearrin** [comment] 2019-03-05 17:54
Can you try disabling popup autohide and then debug the popup window itself. You could also open it in the sidebar to make sure it stays open.

![image](https://user-images.githubusercontent.com/1190944/53826032-ab417d80-3f45-11e9-9961-163bc37cc5b5.png)

![image](https://user-images.githubusercontent.com/1190944/53826057-b98f9980-3f45-11e9-811a-3c4ebf3f4215.png)

Are there any different errors shown when debugging the popup window directly?

**Comment by trparky** [comment] 2019-03-05 18:07
No, there are no additional logs when I click on the popup item.

**Comment by kspearrin** [comment] 2019-03-05 18:45
Weird. I am not sure if this is something specific to you or is affecting others. We haven't heard from anyone else yet about this problem, but will continue to monitor.

As a test, could you try creating a new Firefox user profile and install Bitwarden there to see if the problem can be reproduced that way?

**Comment by kpedro88** [comment] 2019-03-05 19:04
I also experienced issues with 1.39 in Firefox today. I am using an old browser version (for other reasons) on Windows 7. In my case, the vault just doesn't load. No autofill for passwords, and searching the vault returns no results. I had downgraded back to 1.38, but tried 1.39 again with addon debugging enabled, and nothing of note came up in the console.

**Comment by kspearrin** [comment] 2019-03-05 19:09
@kpedro88 please open a separate issue if the parameters are different.

**Comment by kspearrin** [comment] 2019-03-05 19:36
@trparky I was able to reproduce the problem briefly. Still trying to figure out how to reliably reproduce it.

**Comment by choru** [comment] 2019-03-05 19:51
I also have blank popup or sidebar after enabling PIN lock. Unlocking with PIN after browser restart works, but after that everything is blank. Using Firefox 65.0.2 on Archlinux.

**Comment by kspearrin** [comment] 2019-03-05 20:32
@choru and @trparky I think I see the issue. Can either of you confirm that the issue goes away if you disable the new PIN lock feature?

**Comment by kspearrin** [comment] 2019-03-05 20:33
Also, when you disable PIN lock, restart your browser before testing again.

**Comment by lhorace** [comment] 2019-03-05 20:34
Hello there,

I like to note that I am not observing this behavior with ArchLinux using Firefox 65.0.2 with PIN lock enabled and lock timer set to 15 minutes.

Regards

**Comment by JackDinn** [comment] 2019-03-05 20:37
Hi, I just wanted to add that i have just updated and i am also getting the blank browser pop-up after trying out the "pin" login. I have disabled pin login now and seems ok.

Manjaro KDE, Firefox 65.0.2

**Comment by choru** [comment] 2019-03-05 21:00
@kspearrin with PIN lock feature disabled, everything works as usual. Also somehow PIN does not matter when I leave option to "Lock with master password on browser restart" checked in PIN creation window. It gets unlocked with any string but also shows error of invalid PIN.

**Comment by lhorace** [comment] 2019-03-05 21:04
> It gets unlocked with any string but also shows error of invalid PIN.

I'm seeing similar behavior here, though I'm not sure if a separate issue should be open for that.

**Comment by kspearrin** [comment] 2019-03-05 21:37
Both issues should be fixed in the 1.39.1 hotfix coming out soon.

**Closed by kspearrin** 2019-03-05 21:37 UTC

**Comment by kspearrin** [comment] 2019-03-05 22:30
v1.39.1 is now live with these fixes.

**Comment by kpedro88** [comment] 2019-03-05 22:32
For future reference, this also fixed the problems I was observing, even though the symptoms were somewhat different (and I didn't have pin lock enabled).

Thanks!

**Comment by kspearrin** [comment] 2019-03-05 22:35
@kpedro88 Your issue was unrelated, but I found it and included it in this update.
