### ISSUE TITLE
Send rejects long messages

### ISSUE THREAD

**Issue by anuj-modi** [bitwarden/browser#1814] opened 2021-05-03 03:44 UTC
## Describe the Bug
Send displays an error saying "The field Text has exceeded the maximum encrypted message length of 1000 Characters". However, the error seems to arise with a message longer than 687 characters even though the error states the limit is 1000.
## Steps To Reproduce

1. Create a message of length 687. I did this from the MacOS terminal using `python3 -c "print('A' * 687, end='')" | pbcopy`
2. Go to Send
3. Click on the + to make a new Send
4. Title the Send "Test"
5. Paste the message into the body
6. Save the message successfully
7. Add a single character to the body
8. Try to save again and see the error

## Expected Result
I would expect to be able to save a message up to 1000 characters based on the error message

## Actual Result
I get an error past 687 characters.

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/12874774/116839290-ce0c6280-ab9f-11eb-8ccc-87ecbb8000da.png)

## Environment

- Operating system: Mac OS Big Sur
- Browser: Brave 1.23.75
- Build Version (go to "Settings" → "About" in the app):  1.49.1

## Additional Context
I also saw this behavior on the MacOS desktop app version 1.25.1 (518)

**Comment by Greenderella** [comment] 2021-05-03 09:41
Hi @anuj-modi ,

The character count is increased due to encryption, meaning that an 687-character Send note will scale to 1000+ characters when it comes into contact with Bitwarden, triggering this error. As a rule of thumb, character counts will grow between 30-50% when encrypted.

**Comment by eliykat** [comment] 2021-05-03 21:55
I'm closing this issue because this is the expected behaviour. It's not ideal, but it's a consequence of checking the length server-side, and the server can only see the encrypted value.

If you'd like to request a change in this functionality, I've included information about lodging a feature request below. Thanks!

---

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

**Closed by eliykat** 2021-05-03 21:55 UTC
