### ISSUE TITLE
Extension does not show up in Safari

### ISSUE THREAD

**Issue by Nyarumi** [bitwarden/browser#2419] opened 2022-02-28 03:20 UTC
### Steps To Reproduce

1. Install Bitwarden via the App Store.

### Expected Result

Bitwarden should show as a Safari extension.

### Actual Result

Bitwarden does not show up in the extensions list.

### Additional Context

This happened to me seemingly randomly about five days ago. The update to the newer UI didn't cause it, as I was able to use that just fine until it disappeared. I have tried deleting and re-installing, as well as cleaning the app via CleanMyMac X, but neither have worked. The App Store page still says there should be an extension, so I'm not sure what's going on. The actual desktop app works just fine.

### Operating System

macOS

### Operating System Version

macOS Monterey 12.2.1 (21D62)

### Web Browser

Safari

### Browser Version

15.3 (17612.4.9.1.8)

### Build Version

1.31.3

**Comment by Hinton** [comment] 2022-03-01 22:05
Closed as duplicate of https://github.com/bitwarden/browser/issues/1696.

This is a known issue in macOS that affects some web extensions in Safari and not something we can fix on our end. https://github.com/bitwarden/browser/issues/1696#issuecomment-874122595 suggests three workarounds.

**Closed by Hinton** 2022-03-01 22:05 UTC
Labels: bug
