### ISSUE TITLE
Windows 10 blocking u2f (but not webauthn?)

### ISSUE THREAD

**Issue by chrisirwin** [bitwarden/browser#947] opened 2019-06-14 03:26 UTC
I'm unable to log into the extension or website on either Firefox or Chrome on Windows 10 1903 when using a Yubikey4 U2F token. I get the following error, with Windows saying the key doesn't look familiar:

![Yubikey-bitwarden](https://user-images.githubusercontent.com/6145931/59481509-81480300-8e32-11e9-8925-517baecbec80.PNG)

Interestingly, the [yubikey demo website](https://demo.yubico.com/webauthn-technical/registration) works correctly, although it uses webauthn instead of u2f.

If I disable `security.webauth.u2f` in Firefox, I don't get prompted for a token at all, but the yubikey demo site still works (webauthn still enabled).

Looks like Windows 10 1903 actively prevents u2f in both Firefox and Chrome, but webauthn seems to keep working?

**Comment by kspearrin** [comment] 2019-06-14 19:40
Is this also an issue with the web vault as well?

**Comment by chrisirwin** [comment] 2019-06-15 02:46
Yes, that screenshot may have actually been the web vault, and not the extension. Neither seems to work, however.

**Comment by abrewner** [comment] 2019-06-25 08:54
I have the same issue trying to log in to my bitwarden vault via the Firefox extension. 
Running Windows 10 1903 Build 18362.145 and Firefox 67.0.4. 
![image](https://user-images.githubusercontent.com/10756049/60084149-48afff80-9737-11e9-9558-88c7fe53bd5b.png)
After the prompt I touch the yubikey and nothing happens. I click on the extension icon and the login screen appears again. Interestingly, I can login to vault.bitwarden.com without any issues. 
Extension works fine in Chrome 75.0.3770.100.

**Comment by kspearrin** [comment] 2019-06-25 16:11
How do I get Windows 10 1903? My machine says I am up to date on 1809.

**Comment by Tobirexy** [comment] 2019-06-25 17:50
> How do I get Windows 10 1903? My machine says I am up to date on 1809.

If you don’t want to wait for an automatic update you can use the [Windows 10 Update Assistant](https://support.microsoft.com/en-us/help/3159635/windows-10-update-assistant).

**Comment by abrewner** [comment] 2019-06-26 06:50
> 
> 
> How do I get Windows 10 1903? My machine says I am up to date on 1809.
Microsoft is slowly rolling out the new update.

Source: https://blogs.windows.com/windowsexperience/2019/05/21/how-to-get-the-windows-10-may-2019-update/
"Once the update appears, you can select Download and install now. (Note: You may not see Download and install now on your device as we are slowly throttling up this availability, while we carefully monitor data and feedback"

**Comment by kspearrin** [comment] 2019-07-01 12:35
I was able to reproduce a problem on the Firefox extension when trying to log in with U2F, but this really seems like a problem with Firefox itself. When the U2F window appears, focus of the extension popup window is lost, causing it to close. A workaround is to use the sidebar, as @abrewner mentioned. I was not able to reproduce any issues in Chrome.

**Comment by kspearrin** [comment] 2019-07-01 12:42
I filed a bug report here: https://bugzilla.mozilla.org/show_bug.cgi?id=1562620

**Comment by chrisirwin** [comment] 2019-07-03 00:16
> I was able to reproduce a problem on the Firefox extension when trying to log in with U2F, but this really seems like a problem with Firefox itself. When the U2F window appears, focus of the extension popup window is lost, causing it to close. A workaround is to use the sidebar, as @abrewner mentioned. I was not able to reproduce any issues in Chrome.

Kyle, Just confirming abrewner's issue that you've reproduced is a separate issue, right?

I'm unable to use my yubikey4 u2f key in both Chrome and Firefox on Windows. Both the website and the extension (including the sidebar to avoid abrewner's popup issue).

**Comment by kspearrin** [comment] 2019-07-03 00:18
Yes, it seems to be a different problem. I have not been able to reproduce your issue yet.

**Comment by iamacarpet** [comment] 2019-07-31 10:38
Just come across this issue while researching the same problem as @chrisirwin , but for sign in to a Google account with U2F as a second factor.

After upgrading to 1903, every time Chrome requests U2F, Windows takes over and just says it doesn't recognize the security key, as per the screenshot in the opening post.

We do have something specific turned on via GPO, that requires credentials to be entered on the secure desktop, which also causes different prompts on elevation: see screenshot below.

Perhaps they could be related?

![screenshot 1564569373](https://user-images.githubusercontent.com/1333857/62205505-7831d780-b387-11e9-95aa-f1bdc3501e34.png)

Does this look familiar @chrisirwin , that might suggest you have the same setting configured?

**Comment by JeffersonDing** [comment] 2020-12-26 06:49
I got this issue when I was testing my own  api using U2F authentication. It worked for a while and I was even able to get the key registration and authentication work a couple of times in Firefox. But then, it just says "doesn't look familiar". I'm using a Yubikey 5 which has FIDO2, confused. I guess I might switch to webauthn if there is no solution.

**Comment by Hinton** [comment] 2022-02-01 09:23
Since we've migrated all u2f tokens to the newer WebAuthn tokens for more then a year ago. I'm going to close this issue. If anyone still encounters issues with WebAuthn feel free to open a new ticket.

**Closed by Hinton** 2022-02-01 09:23 UTC
