### ISSUE TITLE
Email address doesn't autofill in Epic Games Store

### ISSUE THREAD

**Issue by chelseaislan** [bitwarden/browser#1284] opened 2020-06-05 07:22 UTC
Using the latest version in both Firefox and Chrome, only my password that autofills. But my email address can autofill in my Android.

![Screenshot_2020-06-05 Sign in to Your Epic Games Account Epic Games](https://user-images.githubusercontent.com/30471081/83848123-96026280-a737-11ea-823c-2d6b5d3326de.png)

**Comment by WormChickenWizard** [comment] 2020-06-11 20:17
Also experiencing this issue. The two domains for the epic store login that I am experiencing this with is epicgames.com/id/login and unrealengine.com/id/login

**Comment by MattTheDev** [comment] 2020-07-16 20:35
I'm able to reproduce this. If I remove aria-label="email" from the input tag via source, it will insert the username.

**Comment by WormChickenWizard** [comment] 2020-07-17 03:17
> I'm able to reproduce this. If I remove aria-label="email" from the input tag via source, it will insert the username.

I can confirm it does successfully autofill by removing the `aria-label="email"`, but it is a bit deceiving. Before removing it, it inserts it then removes it immediately. After removing it, the username is only there until you click anywhere on the page. I guess by removing it, it breaks some javascript on the page that is clearing it out?

**Comment by MattTheDev** [comment] 2020-07-17 14:05
Yeah, I see that as well - I'm wondering if they are doing some sort of validation or something that is conflicting with our filling in the field.

Will keep looking for you :)

**Comment by siddharthbandhu** [comment] 2020-08-20 15:38
Issue still exists. Quite annoying 😅

Version: 1.45.0

**Comment by setyb** [comment] 2020-09-12 21:26
Issue confirmed  for v1.45.0.  What is causing this issue and what's an effective way to resolve it?

**Comment by WormChickenWizard** [comment] 2020-09-12 22:12
> Issue confirmed  for v1.45.0.  What is causing this issue and what's an effective way to resolve it?

My guess is due to the javascript in the webpage. No idea what the purpose is to automatically clear out anything auto filled. Probably the best thing to do in order to resolve this is test autofilling it with a few different password managers and identify if it's bitwarden's or epic's fault.

**Comment by setyb** [comment] 2020-09-13 00:47
@WormChickenWizard Thanks for your feedback.  Your comment makes me think: if it is determined that it's a script on the site causing the problem, that script could possibly be blocked with a tool like uBlock Origin.

Of course, if more sites have similar problems, a more global solution would be better.

**Comment by nshew** [comment] 2020-09-24 01:49
This seems to be a duplicate of https://github.com/bitwarden/browser/issues/1029.

**Comment by eliykat** [comment] 2021-02-03 02:58
I'm closing this as a duplicate, please refer to #1029 and #1571. Thanks all

**Closed by eliykat** 2021-02-03 02:58 UTC
