### ISSUE TITLE
Infinite loading in Firefox private mode

### ISSUE THREAD

**Issue by CamilleKaze** [bitwarden/browser#1892] opened 2021-06-12 14:08 UTC
## Describe the Bug

Infinite loading in Firefox private mode.

## Steps To Reproduce

1. Open Firefox
2. Go to private mode
3. Click on the bitwarden extension.

## Expected Result

Showing the same result as if it was normal mode (not private). Which is loading the "enter pin code" page in my case. Or the home page (tab, my vault, etc.) if already unlocked.

## Actual Result

A white page with the loading animation spinning indefinitely.

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/30692513/121778231-6251e800-cb96-11eb-8ca1-1d6200b71ae1.png)

## Environment

- Operating system: Windows 10
- Browser: Firefox 89.0 (64bits)
- Build Version: FIREFOX_89_0_BUILD2

## Additional Context

It happens litterally every time. There was not a single time where it worked in private mode. However, if the vault has already been unlocked in normal mode, then the autofill will still work in private mode, even if I still can't navigate through the extension because it's loading indefinitely.
Also, I use pin code, even when I restart the computer/browser.

**Comment by SergeantConfused** [comment] 2021-06-13 17:21
Hi @CamilleKaze,

This is a known issue as outlined here: https://bitwarden.com/help/article/extension-wont-load-in-private-mode/

Please do not hesitate to reply to this message if you have any further questions.

**Comment by eliykat** [comment] 2021-06-14 22:55
Please also see the existing issue thread here for more discussion: https://github.com/bitwarden/browser/issues/136

As this is a known issue and a duplicate of the above issue, I'll close this one.

**Closed by eliykat** 2021-06-14 22:55 UTC
