### ISSUE TITLE
Browser extensions not working properly on Firefox or Chrome

### ISSUE THREAD

**Issue by bobreidx** [bitwarden/browser#1410] opened 2020-09-26 23:27 UTC
When accessing the contextual menu in credential / login fields, the browser extension will report that the vault is locked, when it isn't.

When the contextual menu finally does populate, the first line in the menu states that the vault is locked, but then lists a number of non-matching entries below that, and then finally a matching entry at the bottom of the list.

This behavior is consistent across attempts, and for both Chrome and Firefox, on macOS, Ubuntu MATE, and Chrome OS.

All versions of aforementioned software are latest, respectively.

**Comment by clayadams5226** [comment] 2020-12-30 03:22
Hi @bobreidx , it looks like there is a viable workaround or resolution for the issue you're experiencing. Please let us know if this resolves the originally posted issue.

**Comment by clayadams5226** [comment] 2020-12-30 04:15
This actually looks like a duplicate of https://github.com/bitwarden/browser/issues/1291 Closing

**Closed by clayadams5226** 2020-12-30 04:15 UTC
