### ISSUE TITLE
background.js, line 2531: Error: No key

### ISSUE THREAD

**Issue by wellington1993** [bitwarden/browser#794] opened 2018-12-03 11:53 UTC
Problem reported on console:

```
JavaScript error: moz-extension://25cfd414-2db7-4314-aa24-6f53ee2f8b1e/background.js, line 2531: Error: No key.
JavaScript error: moz-extension://25cfd414-2db7-4314-aa24-6f53ee2f8b1e/background.js, line 2531: Error: No key.
```

and this above, I don't if this is related to the top error:
```
JavaScript error: undefined, line 0: Error: Missing host permission for the tab
console.error: PushService: 
  receivedPushMessage: Error notifying app
  Message: Error: No record for key ID 45a6839d-2576-4ee6-8c4a-13bbe1443de8
  Stack:
    _updateRecordAfterPush/<@resource://gre/modules/PushService.jsm:779:15
promise callback*_updateRecordAfterPush@resource://gre/modules/PushService.jsm:777:35
receivedPushMessage@resource://gre/modules/PushService.jsm:738:12
_handleDataUpdate@resource://gre/modules/PushServiceWebSocket.jsm:696:17
_handleNotificationReply@resource://gre/modules/PushServiceWebSocket.jsm:722:7
_wsOnMessageAvailable@resource://gre/modules/PushServiceWebSocket.jsm:1052:18
onMessageAvailable@resource://gre/modules/PushServiceWebSocket.jsm:97:5

Extension error: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.removeSheetUsingURIString]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 65"  data: no] undefined 65
[[Exception stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionCommon.jsm:65:12
cleanup@resource://gre/modules/ExtensionContent.jsm:355:11
close@resource://gre/modules/ExtensionContent.jsm:816:7
inner-window-destroyed@resource://gre/modules/ExtensionContent.jsm:891:11
observe@resource://gre/modules/ExtensionContent.jsm:907:5
Current stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionCommon.jsm:67:129
cleanup@resource://gre/modules/ExtensionContent.jsm:355:11
close@resource://gre/modules/ExtensionContent.jsm:816:7
inner-window-destroyed@resource://gre/modules/ExtensionContent.jsm:891:11
observe@resource://gre/modules/ExtensionContent.jsm:907:5
]]
```

Thanks..

**Comment by kspearrin** [comment] 2018-12-03 15:18
Looks like you have no key, which would just log you out (or lock the app) and require you to log back in (or unlock). Is there a specific problem this is causing?

**Comment by wellington1993** [comment] 2019-02-01 12:47
@kspearrin Strange because sometimes the error it's not observable. 
I have not identified a source of the problem.
Thanks!

**Comment by eliykat** [comment] 2021-02-17 01:34
Hi @wellington1993, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by eliykat** 2021-02-17 01:34 UTC
