### ISSUE TITLE
Extension drop-down menu blank in Firefox

### ISSUE THREAD

**Issue by caspiano** [bitwarden/browser#951] opened 2019-06-18 03:01 UTC
Extension drop-down menu is blank when clicked.
Can still access extension through sidebar.

<img width="126" alt="Screen Shot 2019-06-18 at 12 55 11 pm" src="https://user-images.githubusercontent.com/18466497/59650320-ebf99580-91c8-11e9-8046-0e4f7824eef4.png">

- Version: Bitwarden 1.39.3
- Browser: Firefox 67.0.2 (64-bit)
- Device: Macbook Pro (late 2018)
- OS: macOS 10.14.5

**Comment by kspearrin** [comment] 2019-06-18 12:46
I on using the same setup, macOS 10.14 and Firefox 67, but cannot reproduce the issue. As a test, can you try creating a new Firefox user profile and see if the issue persists?

**Comment by cjbruin** [comment] 2019-07-12 11:22
the macbook is not the only problem, i'm using Windows / Firefox 67 same problem here. But strange thing is, when i want to make a snapshot of the problem it's not possible and bitwarden is working fine.

**Comment by laurentS** [comment] 2019-08-05 19:12
I have the same issue on Debian Sid. First time I click the icon, it is blank as in the capture above, so I need to click the icon or elsewhere, then click the icon again to see the drop-down. This happens repeatedly, so I basically need 3 clicks to open the drop-down each time I want to use it. It must be some kind of regression, as it only started about a week or 2 ago, I think.

- bitwarden 1.41.0
- firefox 68

**Comment by kspearrin** [comment] 2019-08-05 23:12
@laurentS If you think it is a regression, you could try install an older version to see if the problem occurs there. https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/versions/

**Comment by laurentS** [comment] 2019-08-08 23:22
@kspearrin good idea. So I did. Uninstalled bitwarden, and installed version 1.40.1, and the bug was gone. Then updated to latest 1.41.0, and the bug is still gone. So I'm not sure what is happening there.
In case it helps, I noticed before uninstalling/reinstalling that the bug did not seem to occur in private mode.
In any case, keep up the great work, bitwarden is a neat piece of software!

**Comment by mathieugfortin** [comment] 2020-01-14 20:31
It just happened to me on 1.42.2, downgraded to 1.41.0 and I'm back to normal

**Comment by kspearrin** [comment] 2020-01-15 12:55
@mathieugfortin Try restarting your device after the upgrade. That fixed it for me for whatever reason.

**Comment by djsmith85** [comment] 2022-03-01 22:07
Hi @caspiano, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by djsmith85** 2022-03-01 22:07 UTC
