### ISSUE TITLE
View master password returns cursor to start of line.

### ISSUE THREAD

**Issue by xSepticSidx** [bitwarden/browser#2178] opened 2021-11-15 17:45 UTC
### Steps To Reproduce

When using the Chrome Browser extension on Win10 as you fill in the master password, if you select the eye (to show password) perhaps because you think you hit a wrong key etc.
The curser is sent to the start of the line and without noticing it you may be typing the wrong password in.
I.E. start typing "pass" hi "show password" continue typing "word" and then what you have is:
"wordpass" instead of password.

### Expected Result

I would expect the cursor to remain where it was before hitting the "show password" icon.

### Actual Result

The cursor goes to the start of the line

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Browser Version

Version 95.0.4638.69 (Official Build) (64-bit)

### Build Version

Version: 1.54.0

**Comment by chao813** [comment] 2021-11-18 08:51
Noticed this is an issue when using the web vault on Chrome as well, since it's using the same common jslib files. Should link this issue to the jslib repo

**Comment by jesseliu612** [comment] 2021-11-26 10:43
Perhaps this behavior is by design.
In https://github.com/bitwarden/browser/blob/d528d72b4d363c202d2a50d88d41b8ab0ba4542e/src/popup/accounts/login.component.html#L27-L29
The toggle visibility function works like this: when user click the toggle button, it changes `showPassword` to `true`, and the type of `input`, which is bound to that variable, changes then. And when `type` changes, the behavior of the browser is to re-render the `input` element and thus the cursor is moved to the start.
Fixing this issue may lead to a re-design of how we deal with this.

**Comment by chao813** [comment] 2021-11-26 11:05
@jesseliu612 It only behaves differently like this on chrome, every other browser it works as intended meaning this is a valid issue. Please try the togglePassword on any browser except for Chrome and then try on Chrome.

**Comment by jesseliu612** [comment] 2021-11-26 15:30
> @jesseliu612 It only behaves differently like this on chrome, every other browser it works as intended meaning this is a valid issue. Please try the togglePassword on any browser except for Chrome and then try on Chrome.

This is a Chromium issue.

You can test with other websites where you can also toggle the password visibility, such as: https://www.cssscript.com/demo/toggle-password-visibility/

All of them works great on Firefox and Safari, but all failed on Chrome.

**Comment by chao813** [comment] 2021-11-26 15:34
Yes it is a Chromium issue but there are ways to work around it so the behavior is the same on all browsers. Chrome has an odd quirk where the focus event fires before the cursor is moved into the field.

**Comment by jesseliu612** [comment] 2021-11-26 15:52
> Yes it is a Chromium issue but there are ways to work around it so the behavior is the same on all browsers. Chrome has an odd quirk where the focus event fires before the cursor is moved into the field.

I won't deny that there could be workaround but I do think this issue should be solved upstream. Otherwise, implementing a workaround could result in a huge amount of code to be modified.

**Comment by xSepticSidx** [comment] 2021-11-26 18:26
> 

I too tried this site, does the same on Edge as it does on Chrome.

**Comment by eliykat** [comment] 2021-11-28 21:32
Fixed in https://github.com/bitwarden/jslib/pull/561.

**Closed by eliykat** 2021-11-28 21:32 UTC
Labels: bug

**Comment by jesseliu612** [comment] 2021-11-30 14:56
have submitted this issue to chromium.
track it here:
https://bugs.chromium.org/p/chromium/issues/detail?id=1274477
@xSepticSidx @chao813

**Comment by eliykat** [comment] 2021-11-30 22:33
Thanks @jesseliu612, I've subscribed to that bug report and will revert these workarounds if/when the upstream issue is fixed.
