### ISSUE TITLE
Firefox extension not working on FF <= 77

### ISSUE THREAD

**Issue by shlomster** [bitwarden/browser#1931] opened 2021-07-04 17:24 UTC
Hello,

The firefox extension / sidebar are not working for me (perpetual loading).

I previously had this same issue. See:
https://github.com/bitwarden/browser/issues/1699

It was fixed in Version 1.49.1 as: * Resolve FF < 77 not working (#1706)

Firefox 72.0.1
MacOS Mojave 10.14.6
Bitwarden 1.51.0

**Comment by eliykat** [comment] 2021-07-04 23:51
I've been able to reproduce this. This is caused by use of a unicode property escape here: https://github.com/bitwarden/jslib/blob/d10d40697cd22a63b221356fb61cf492eede188a/angular/src/pipes/color-password.pipe.ts#L14

This is not supported in FF <= 77: https://caniuse.com/mdn-javascript_builtins_regexp_property_escapes

Will discuss with the team.

**Comment by shlomster** [comment] 2021-07-07 04:36
Thank you for looking. Will I need to update FF?

**Comment by eliykat** [comment] 2021-07-07 06:48
Ideally you should be using the latest version of Firefox, or at least a current Long Term Support (LTS) version. If you upgrade FF, the Bitwarden extension will work immediately. However, we're also releasing a patch this week that should fix backwards compatibility and make it work on FF 72. You'll just need to keep an eye out and upgrade the Bitwarden extension when a new one becomes available.

**Comment by shlomster** [comment] 2021-07-07 13:00
Thanks!

**Comment by shlomster** [comment] 2021-07-30 19:13
@eliykat Will this patch go out soon?

**Comment by eliykat** [comment] 2021-08-02 01:20
@shlomster It went out in version 1.51.1, which was released on 9 July (a few days after our messages above). Please make sure you're using the latest version. If you're still experiencing this issue on 1.51.1, let me know and I'll revisit it.

**Comment by shlomster** [comment] 2021-08-02 01:54
@eliykat I seem to have auto updated so yes I do have 1.51.1 with the same problem. Removed and redownloaded to be sure.

**Comment by eliykat** [comment] 2021-08-06 01:58
I'm unable to reproduce on macOS Big Sur 11.5.1:

![Screen Shot 2021-08-06 at 11 46 59 am](https://user-images.githubusercontent.com/31796059/128443566-e0432e58-115e-4d44-9f9c-75652322303b.png)

Unfortunately extensions can be difficult to debug on Firefox. If you're comfortable with the process, you could download the latest release [here](https://github.com/bitwarden/browser/releases/tag/v1.51.1), load it as a temporary add-on ([instructions](https://developer.mozilla.org/en-US/docs/Tools/about:debugging#extensions)), then use Dev Tools to inspect the console for error messages ([instructions](https://discourse.mozilla.org/t/how-can-i-inspect-the-popup-of-an-addon/34134)). That would give me a better idea of what the problem is.

**Comment by eliykat** [comment] 2021-08-23 20:32
Hi @shlomster, it appears we've not heard from you about this issue in some time, so I'll close this issue. If you are still dealing with this issue, please contact our customer success team so that they can help you troubleshoot it further: bitwarden.com/contact/

**Closed by eliykat** 2021-08-23 20:32 UTC
