### ISSUE TITLE
Safari crashing with certain SSL certificates when Bitwarden is enabled

### ISSUE THREAD

**Issue by cjfaquino** [bitwarden/browser#1694] opened 2021-03-13 05:52 UTC
## Describe the Bug

Safari crashes when viewing products page on Amazon.com

## Steps To Reproduce

1. Go to 'Amazon.com'
2. Click on any link to a product page

## Expected Result

Finish loading product page

## Actual Result

Crashes right before page completes

## Environment

- Operating system: [m1 Mac OS 11.2.3]
- Browser: Safari 14.0.3
- Build Version (go to "Settings" → "About" in the app): [1.49.0]

**Comment by CunninghamPaul** [comment] 2021-03-13 09:17
Same on https://skysports.com as soon as the tab starts to load Safari crashes out completely and get a report the error to Apple prompt. Go to Safari preferences and untick the Bitwarden extension then the page loads without issue.

Mac OS 11.2.3
Safari Version 14.0.3 (16610.4.3.1.7)
Bitwarden Version 1.25.0 (516)

**Comment by l0rda** [comment] 2021-03-13 11:02
Same for me, on every site

Version:               14.0.3 (16610.4.3.1.4)
Build Info:            WebBrowser-7610004003001004~1
Code Type:             ARM-64 (Native)
OS Version:            macOS 11.2.2 (20D80)
Enabled Web Extensions:
com.bitwarden.desktop.safari (LTZ2PFU5D6) (Version: 1.49.0 - Display Version: 1.49.0) Bitwarden - Free Password Manager
 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '<cert(0x1446543f0) s: CN_DNSBL i: CN_DNSBL> does not conform to NSSecureCoding'
terminating with uncaught exception of type NSException
abort() called

**Comment by kennymc-c** [comment] 2021-03-13 13:05
I can't reproduce this with my Intel MacBook Air 2018 and the same browser and extension version.
Maybe this is related to the ARM architecture of the M1?

**Comment by CunninghamPaul** [comment] 2021-03-13 13:21
@kennymc-c you may be correct, the problem for me is only on my M1 Macbook Air. I just tested on my 2019 Intel iMac and a 2012 Intel Macbook Pro and everything is working fine, no crashes in Safari

**Comment by dmcfaddengalway** [comment] 2021-03-13 13:22
@l0rda as you are on v 1.49.0 has the Safari extension been shortened in length for you too? I am trying to make it longer in length but no luck. 

I am having this issue as well on Amazon.

**Comment by kennymc-c** [comment] 2021-03-13 13:24
@dmcfaddengalway Already created an issue for this with other problems on Safari: #1692

**Comment by l0rda** [comment] 2021-03-13 20:41
> I can't reproduce this with my Intel MacBook Air 2018 and the same browser and extension version.
> Maybe this is related to the ARM architecture of the M1?

@kennymc-c  yes, maybe. 

By the way, i found it is crashing, if i allow bitwarden extension on all sites and open youtube, for example.
If i allow extension only on youtube, and open youtube page - it is not crashing.

**Comment by cjfaquino** [comment] 2021-03-13 22:03
> Same on https://skysports.com as soon as the tab starts to load Safari crashes out completely and get a report the error to Apple prompt. Go to Safari preferences and untick the Bitwarden extension then the page loads without issue.
> 
> Mac OS 11.2.3
> Safari Version 14.0.3 (16610.4.3.1.7)
> Bitwarden Version 1.25.0 (516)

skysports.com works for me with extension ver 1.49.0. 

I haven't found any other site it does this on

**Comment by darrylhodgins** [comment] 2021-03-14 04:04
I was having this problem on amazon.ca product pages as well, but it seems that I can work around it by selecting "Always Allow" for individual websites.

- MacOS 11.2.3 (20D91)
- Safari Version 14.0.3 (16610.4.3.1.7)
- Bitwarden Extension Version: 1.49.0
- MacBook Air (M1, 2020)

As for the workaround:

![Screen Shot 2021-03-13 at 19 58 11 ](https://user-images.githubusercontent.com/5093765/111056790-c3064300-8436-11eb-92f1-f2e5ec6fab6c.png)

**Comment by lbroto** [comment] 2021-03-14 09:44
Same for me. Crash on Amazon when clicking on an item.

Environment: MacOS Big Sure 11.2.3, Safari 14.0.3, architecture: Silicon M1, Bitwarden extension release: 1.49.0.

**Comment by dprandzioch** [comment] 2021-03-14 18:54
Having that as well, on an M1 MBP with the newest BW update. It's not Amazon only btw - renders Safari completely useless.

**Comment by ne0-ai** [comment] 2021-03-15 03:58
Experiencing the same issue. It crashes while clicking on any link on amazon. Disabling it for now.

**Comment by Hinton** [comment] 2021-03-15 17:07
I'm currently looking into this issue, however since the issue is isolated to M1 Macs it would be helpful to collect the crash reports, as well as the logs of Safari shortly before and after the crash.

If anyone would be willing to assist and post their Crash Reports and logs it would be highly appreciated. I suspect the easiest way is to use the report feature of the built in console application in MacOS, https://support.apple.com/guide/console/reports-cnsl664be99a/mac

**Comment by CunninghamPaul** [comment] 2021-03-15 17:56
@Hinton I just did some testing and found the following. 

I use PFSense with a package called PFBlockerNG as my router. This PFBlocker package is a DNS filter that uses lists to block ads and trackers which are redirected to a block page in the router.
On looking at my crash report in Console I see:-
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '<cert(0x15f91ba00) s: router-pfBNG-DNSBL-5ff6e7190576a i: router-pfBNG-DNSBL-5ff6e7190576a> does not conform to NSSecureCoding'
terminating with uncaught exception of type NSException
abort() called

I have just tried tethering my macbook to my phones data service instead of my router and it did not crash so I disabled PFBlocker on the router and retried, again it did not crash.

It's strange though that if in the extension settings I set Bitwarden to Ask for each site it does not crash even if I grant access to problem sites, it only seems to crash if I set permissions to always allow and browse via my router with the blocker enabled.

**Comment by dprandzioch** [comment] 2021-03-15 17:59
I also use a DNS-based ad blocker (pihole) if this is anyhow interesting.

**Comment by CunninghamPaul** [comment] 2021-03-15 18:15
I think this is being caused by self signed SSL certificates, after my earlier post re PFBlockerNG I thought to try accessing my Synology NAS which also has a self signed cert, same result crashes Safari immediately. This is on a local LAN not going through the router/blocker.

Attached crash report from this test.
[crashreport.txt](https://github.com/bitwarden/browser/files/6143577/crashreport.txt)

**Comment by Hinton** [comment] 2021-03-15 21:41
@CunninghamPaul Thank you for the crash report.

I'm quite puzzled by it though since there doesn't seem to be anything in the stack trace related to the Bitwarden extension. I managed to get an almost identical stack trace on my Intel MacBook by visiting a self-signed certificate (with and without the extension activated) although Safari did not crash.

![safari-stacktrace](https://user-images.githubusercontent.com/137855/111224400-b45a9000-85de-11eb-8e18-441fdb3dde15.png)

I will continue debugging this and trying to find the root cause behind the crash.

In the meantime additional crash reports, as well as information as to usage of dns blockers, self-signed certificates would be appreciated.

Until then a work-around which will get the old extension running on safari would be to download the previous release of the desktop application https://github.com/bitwarden/desktop/releases/tag/v1.24.6

**Comment by CunninghamPaul** [comment] 2021-03-15 22:23
@Hinton Thanks for looking into this. 

I am an infrastructure guy so limited in my coding knowledge but I am beginning to wonder if this a bug in the Apple API on M1 rather than in the extension.

It would seem that it is related to untrusted certificates. I just disabled Bitwarden extension and opened my NAS web management which has a self signed SSL then added it as a trusted certificate. I then re-enabled Bitwarden and relaunched Safari, I was able to browse the NAS pages without error.
Next I closed the browser went into Keychain and deleted the certificate trust. As soon as I tried to browse the NAS page after removing the certificate trust from the Keychain, Safari would crash immediately on opening the page.

If I disable the Bitwarden extension I can browse to the NAS page without a trusted certificate but with it enabled it crashes. So it would seem if you are using a DNS filter such as PFBlockerNG or PiHole that uses self signed certificates you will see this issue.,

As you say I too have no issues browsing sites with untrusted SSL certificates on my Intel Macs it does only affect my M1 Mac.

Attached crash report, this is without a certificate trust in Keychain and Bitwarden extension enabled on a M1 MacBook Air.
[crashreport2.txt](https://github.com/bitwarden/browser/files/6144843/crashreport2.txt)

**Comment by gleydsonsoares** [comment] 2021-03-16 01:15
> Until then a work-around which will get the old extension running on safari would be to download the previous release of the desktop application https://github.com/bitwarden/desktop/releases/tag/v1.24.6

I think you will need to rollback the safari changes from 1.24.6 and bump a new release into Apple Store until a valid fix comes up.

Accordingly to https://bitwarden.com/help/article/install-safari-app-extension/

Due to changes by Apple, Safari limits Web Extension use to only those obtained through Mac App Store downloads. As of the 2021-03-11 Release, users will not be able to use a Bitwarden Safari Extension obtained through a .dmg installation from bitwarden.com/download or any other non-App Store source.

**Comment by ne0-ai** [comment] 2021-03-16 14:27
> > Until then a work-around which will get the old extension running on safari would be to download the previous release of the desktop application https://github.com/bitwarden/desktop/releases/tag/v1.24.6
> 
> @Hinton I think it will need to rollback the safari changes from 1.24.6 and bump a new release into Mac App Store until a valid fix comes up.
> 
> Accordingly to https://bitwarden.com/help/article/install-safari-app-extension/
> Due to changes by Apple, Safari limits Web Extension use to only those obtained through Mac App Store downloads. As of the 2021-03-11 Release, users will not be able to use a Bitwarden Safari Extension obtained through a .dmg installation from bitwarden.com/download or any other non-App Store source.
> 
> For now, I have just disabled the Safari web extension.

I agree, extension cannot be used if its not from App Store. So for now I have disabled the extension too which is very inconvenient. I hope this gets fixed soon.

**Comment by IAkumaI** [comment] 2021-03-16 19:20
Confirm. Same safari crashed. Example: https://osxdaily.com/2014/01/08/move-windows-apps-desktops-between-displays-mac-os-x/

**Comment by l0rda** [comment] 2021-03-16 20:42
> @Hinton I just did some testing and found the following.
> 
> I use PFSense with a package called PFBlockerNG as my router. This PFBlocker package is a DNS filter that uses lists to block ads and trackers which are redirected to a block page in the router.
> On looking at my crash report in Console I see:-
> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '<cert(0x15f91ba00) s: router-pfBNG-DNSBL-5ff6e7190576a i: router-pfBNG-DNSBL-5ff6e7190576a> does not conform to NSSecureCoding'
> terminating with uncaught exception of type NSException
> abort() called
> 
> I have just tried tethering my macbook to my phones data service instead of my router and it did not crash so I disabled PFBlocker on the router and retried, again it did not crash.
> 
> It's strange though that if in the extension settings I set Bitwarden to Ask for each site it does not crash even if I grant access to problem sites, it only seems to crash if I set permissions to always allow and browse via my router with the blocker enabled.
> 
> Edited to add: the block page redirect uses a self signed certificate so it would not have a valid root CA chain for verification which I would think may be a problem.

I’m using pfBlocker too

**Comment by gacevedo** [comment] 2021-03-17 03:56
> I'm currently looking into this issue, however since the issue is isolated to M1 Macs it would be helpful to collect the crash reports, as well as the logs of Safari shortly before and after the crash.
> 
> If anyone would be willing to assist and post their Crash Reports and logs it would be highly appreciated. I suspect the easiest way is to use the report feature of the built in console application in MacOS, https://support.apple.com/guide/console/reports-cnsl664be99a/mac

Attaching a report. No ad blockers or any other extension active at the time of the crash (the only other extension installed at the moment is LastPass, but it's not active). I visited https://www.amazon.com/Nikon-SB-5000-AF-Speedlight-Black/dp/B01A7Q0N9Y/. If I disable the Bitwarden extension Safari does not crash.

Details below. Happy to attempt to reproduce other scenarios, try workarounds, enable debug mode, etc. Just let me know.

Safari 14.0.3 (16610.4.3.1.4)
Bitwarden 1.49.0
macOS Big Sur 11.2.3 (20D91)
Mac mini (M1, 2020)

[bitwarden_amazon_crash_report.txt](https://github.com/bitwarden/browser/files/6153644/bitwarden_amazon_crash_report.txt)

**Comment by cscharf** [comment] 2021-03-18 13:15
Hi All,

Quick update, we've been in contact with Apple Developer Support who has referred the issue to the Safari engineering team directly. We have a Feedback Assistant issue open, FB9047055. We're waiting to hear back to get next steps. Thank you for your patience while we work through this. We'll definitely be adding more regression test cases with M1 hardware going forward as well.

Thanks!

**Comment by lbroto** [comment] 2021-03-22 20:09
Hello, 1.49.1 changes nothing, still crashes with self signed certificate.

**Comment by cumanzor** [comment] 2021-03-23 04:32
Definitely related to self signed certs. I use mkcert (https://github.com/FiloSottile/mkcert) for development and some sites, particularly Amazon, crash Safari if the Bitwarden Extension is enabled. 

What I don't get however, if why it's crashing. There should be 0 interaction between safari and any site that is not using your self-managed ssl cert right?

**Comment by jesseliu612** [comment] 2021-03-23 04:43
The extension crashes on a famous Chinese site www.sohu.com too. Same report.

**Comment by Tinrobotguy** [comment] 2021-03-23 23:45
Installed 1.25.1 and it still crashes Safari.

**Comment by nicx** [comment] 2021-03-25 13:15
+1

**Comment by dprandzioch** [comment] 2021-03-29 18:37
Is there any workaround? Allowing access to all pages (like mentioned above) does not work. Hate being stuck with Chrome for now :/

**Comment by Hinton** [comment] 2021-03-31 14:33
As a temporary workaround we have released a frozen version of the desktop application https://github.com/bitwarden/desktop/releases/tag/v1.24.7 with auto update disabled. This version contains the previous App Extension version of the browser extension which should not crash.

**Comment by gleydsonsoares** [comment] 2021-03-31 16:10
> As a temporary workaround we have released a frozen version of the desktop application https://github.com/bitwarden/desktop/releases/tag/v1.24.7 with auto update disabled. This version contains the previous App Extension version of the browser extension which should not crash.

@Hinton is it available though App Store? Otherwise, we can use safari extension....

**Comment by dprandzioch** [comment] 2021-03-31 16:19
@gleydsonsoares This is why I wanted to verify the extension version number. I removed my MAS Bitwarden installation and installed the one provided from GitHub - I see an Safari extension and was able to activate and use it. But I'm not sure if it's really the version provided from the dmg or still the MAS version.

**Comment by cumanzor** [comment] 2021-03-31 16:23
@dprandzioch I uninstalled the MAS version and then installed 1.24.7 from the releases link. My current extension version is 1.49.1. It's working fine so far, and the issue with the height is not present in this version so it looks like it's not the MAS extension. I was under the impression you needed the MAS version to install the extension too, but maybe this is not the case?

**Comment by Tinrobotguy** [comment] 2021-03-31 16:29
I have the frozen version on my M1 Mac and it still takes 3-5 seconds to load after inputting password.

**Comment by dprandzioch** [comment] 2021-03-31 18:16
Mine's at 1.48.1, but it's working so far - let's see. Not sure why it works even if it's not loaded from MAS - what I understood is that it shouldn't.

**Comment by nicx** [comment] 2021-04-01 06:08
I can confirm with fixed version installed and using version 1.48.1 of the safari extension instead of 1.49.1 the crash is no more happening! thanks a lot for this workaround, hopefully we get a fix to the new versions, too :)

**Comment by lbroto** [comment] 2021-04-01 13:13
It works: no delay to open the window, no crash and no square window. Thank you !

**Comment by dotsam** [comment] 2021-04-01 20:46
Testing using https://badssl.com, at least the self-signed certificate and probably others can replicate this on an M1 Mac running 11.2.3 and Safari 14.0.3

But on the same machine, testing with Safari Technology Preview Release 123, I can't replicate the crash. So hopefully this is a Safari bug that will be fixed in the next release. Has anyone tried this under the 11.3 beta?

**Comment by cscharf** [comment] 2021-04-01 21:08
> But on the same machine, testing with Safari Technology Preview Release 123, I can't replicate the crash. So hopefully this is a Safari bug that will be fixed in the next release. Has anyone tried this under the 11.3 beta?

Thanks for the additional info, I've added that as additional context to our report with Apple.

**Comment by yaleman** [comment] 2021-04-05 21:24
Safari: Version 14.0.3 (16610.4.3.1.7)
Bitwarden: Version 1.25.1 (518)
Bitwarden extension: 1.49.1
M1 Macbook pro

Reproducible by going to badssl.com and clicking on any of the "red" links with the Safari extension enabled. Same with self-signed certs or any other cert with a validation failure that'd typically pop a warning message.

**Comment by kiltum** [comment] 2021-04-25 12:57
This hit me too. But only with self-signed cert. Also only on M1

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '<cert(0x12d715930) s: localhost.localdomain i: VMware Installer> does not conform to NSSecureCoding'
terminating with uncaught exception of type NSException

**Comment by dotsam** [comment] 2021-04-26 19:58
I can confirm that this issue seems to be solved with Safari 14.1 on macOS 11.3 (20E232) with the current App Store release of BitWarden, version 1.25.1 (518) with extension version 1.49.1.

**Comment by Hinton** [comment] 2021-04-27 19:11
I checked with our internal QA team and they also confirmed it's working on their M1 macbooks running 11.3. I would appreciate knowing if anyone still has issues with crashes on 11.3, but since it seems to be resolved, I will close the issue in the meanwhile. Please feel free to re-open it should anyone encounter the issue again after upgrading to 11.3.

**Closed by Hinton** 2021-04-27 19:11 UTC
Labels: bug
