### ISSUE TITLE
Bitwarden UI vanishes if trying to enter password in Firefox 61.01

### ISSUE THREAD

**Issue by 1989gironimo** [bitwarden/browser#720] opened 2018-09-07 09:08 UTC
It tries to display the UI to enter the master password, but vanishes instantly.
I've disabled every other extension already and restarted Firefox but the behavior stays the same.
Firefox 61.01 x64 on Ubuntu 17.04

**Comment by Crocmagnon** [comment] 2018-09-07 09:33
Duplicate of #580

**Closed** 2018-09-07 11:08 UTC
