### ISSUE TITLE
Notes not visible while on matched entry sites

### ISSUE THREAD

**Issue by msoose** [bitwarden/browser#1319] opened 2020-07-03 02:05 UTC
## Describe the Bug

When on a site that is recognized by domain/url for autofill, the _View_ button turns in to _Launch_, this means that **Notes** section is not available during/after use of autofill. A user might store information in the **Notes** section for logging in to a service. So now the user must manually search for the entry or in order to _View_ the section for **Notes**.

## Steps To Reproduce

1). Visit page that can be autofilled.
2). Select Bitwarden extension shortcut or autofill the credentials. 

## Expected Result

I expect the matching entries to show the option to _View_

## Actual Result

The matching entries show the option to _Launch_

## Environment

- Operating system: Fedora 31
- Browser: Firefox 77.0.1
- Build Version: e.g. 1.45.0

**Comment by kspearrin** [comment] 2020-07-04 02:44
There is a view button shown as an icon on the "Tab" autofill page.

**Comment by msoose** [comment] 2020-07-04 19:37
The View button on the "Tab" autofill page still does not show all contents of the entry. Not sure what I'm doing wrong? Visit a page, CTRL+SHIFT+L to autofill. Open the entry from the extension icon.

Custom field and Notes are not visible:
![1](https://user-images.githubusercontent.com/30473690/86519708-c999e080-bdfa-11ea-902f-62ac6ab646e9.png)

Run a search and I get the full contents of the matched entry.

Custom fields and Notes are visible:
![2](https://user-images.githubusercontent.com/30473690/86519712-cc94d100-bdfa-11ea-8213-f02800034b13.png)

**Comment by MattTheDev** [comment] 2020-07-14 19:20
Hi there @msoose - I am working on resolving your issue. Running on MacOS and Windows, I am unable to reproduce the same issue you are having. For example, when I go to a saved entry I have .. and I click the extension I see:

![image](https://user-images.githubusercontent.com/7233525/87467072-fad59600-c5dc-11ea-8b39-8dcdea20d063.png)

When I click the icon I am *kind of* pointing at in the screenshot above, I see:

![image](https://user-images.githubusercontent.com/7233525/87467157-1b055500-c5dd-11ea-84b7-ad2b1a3eb729.png)

I am working on building out a Fedora instance so that I can test in your OS to see if there is an operating system factoring into things so I can get you taken care of.

**Comment by msoose** [comment] 2020-07-21 23:06
So I've also been testing this, and thus far it seems to only be repeatable for me on one site, specifically after following the "Sign In" @ https://www.rbcroyalbank.com/ways-to-bank/online-banking/index.html

**Closed** 2021-11-15 21:02 UTC
