### ISSUE TITLE
"Host" match now needs schema

### ISSUE THREAD

**Issue by Sincasios** [bitwarden/browser#1341] opened 2020-07-26 16:50 UTC
## Describe the Bug
I have some domains added as "host*" match that match;
subdomain.domain.com:port

It worked for months but now it doesn't match in Chrome for windows extension. BitWarden extension says 0 passwords to current page and if I want to store the password if I login.

I modified the server entry to add the schema (https://subdomain.domain.com:port) and now it matches again. Of course, I can use this, but if I want to configure this I can use (I supose) "starts-with".

## Steps To Reproduce
Store some password with host method. I have something like this: service.user.duckdns.org:51424

I don't add https:// or http:// at the start. I expect that "host" matches "service.user.duckdns.org:51424" (https://bitwarden.com/help/article/uri-match-detection/) and is that worked until now.

## Expected Result
When I enter in "https://service.user.duckdns.org:51424/something" extension will recognize that it should match service.user.duckdns.org:51424 password

## Actual Result
It doesn't match. I need to modify my host match to https://service.user.duckdns.org:51424 that is almost a "starts" match.

## Environment

- Windows 10
- Updated chrome version
- Build Version: 1.45.0

**Comment by MGibson1** [comment] 2020-11-19 13:56
@Sincasios I am unable to reproduce this in the latest Browser version, 1.47.0, or the last, 1.46.2. Can you please confirm?

I'm going to close this issue as fixed until you can confirm the behavior is still occurring.

Thanks!

**Closed by MGibson1** 2020-11-19 13:56 UTC
