### ISSUE TITLE
Unable to unlock with biometrics on Safari MacOs M1

### ISSUE THREAD

**Issue by lcoiffard** [bitwarden/browser#1555] opened 2021-01-23 23:24 UTC
On Safari MacOs M1, when I check "Unlock with biometrics", a message "Awaiting confirmation from desktop" display, but when I open the desktop app, nothing append.

## Steps To Reproduce

1. Open Safari
2. Click on Bitwarden extension
3. Click on Unlock with biometrics

## Expected Result

I would like that I can use biometrics to unlock Bitwarden extension

## Actual Result

A window "Awaiting confirmation from desktop" is displayed.

## Screenshots or Videos

<img width="397" alt="image" src="https://user-images.githubusercontent.com/1681596/105616879-e3574100-5da7-11eb-804e-0a03ff91f5f4.png">
<img width="388" alt="image" src="https://user-images.githubusercontent.com/1681596/105616886-f36f2080-5da7-11eb-9494-da894b5ee8e9.png">
<img width="743" alt="image" src="https://user-images.githubusercontent.com/1681596/105636101-95d4e580-5e34-11eb-9bc6-92d3b6dca01f.png">

## Environment

- Operating system: MacOs 11.1 on M1
- Browser: Safari 14.0.2
- Build Version Desktop 1.24.1, extension 1.48.0

**Comment by yureiita** [comment] 2021-01-24 02:36
I'm also unable to unlock with biometrics on both Firefox and Safari MacOS Intel. I have reinstalled both the browser extensions and the desktop app. I have restarted the computer. "Enable browser integration" is checked on the desktop app.

This is my settings on desktop app:
<img width="497" alt="Screenshot 2021-01-24 at 10 23 48" src="https://user-images.githubusercontent.com/26035759/105619622-5f489c00-5e2f-11eb-949e-9b945b7d4ca0.png">

This is the screenshot on firefox:
<img width="547" alt="Screenshot 2021-01-24 at 10 24 39" src="https://user-images.githubusercontent.com/26035759/105619591-185aa680-5e2f-11eb-9cf2-a98c70d7bf80.png">

- Operating system: MacOS 11.1 on Intel
- Browser: Firefox 84.0.2 and Safari 14.0.2
- Build Version Desktop 1.24.1, Browser 1.48.0

**Comment by jo-0** [comment] 2021-01-24 07:36
I've the same [issue](https://community.bitwarden.com/t/new-browser-extension-not-working-with-biometric-login/16902)

**Comment by gastlchhh** [comment] 2021-01-24 10:33
i have this same issue too

**Comment by Crocmagnon** [comment] 2021-01-24 11:24
I can reproduce the behavior on Firefox too.

**Comment by Vinz87** [comment] 2021-01-24 12:27
I experience the same issue

**Comment by camsloanftc** [comment] 2021-01-24 15:17
Checking in for chrome as well on mac. I cannot enable the biometrics in the browser. Also tried firefox with no luck.

![image](https://user-images.githubusercontent.com/16295659/105634667-37f0cf80-5e2d-11eb-9ca0-77786664705c.png)


![image](https://user-images.githubusercontent.com/16295659/105634678-49d27280-5e2d-11eb-9bd0-37030cdbf060.png)

Very excited for once this works though!!

**Comment by emx0r** [comment] 2021-01-24 17:46
same problem BigSur + Safari

**Comment by saegl5** [comment] 2021-01-24 20:14
@emx0r me too
although, I am aware that [Biometric Unlock is supported for Firefox and Chromium-based (i.e. Chrome, Edge) Bitwarden Browser Extensions...](https://bitwarden.com/help/article/biometrics/), not for Safari extensions, at least yet
however, safari support would be nice

**Comment by codeHatcher** [comment] 2021-01-29 00:52
Same here with Chrome, MacOS version downloaded from the app store, browser integration checking in desktop, and trying to check in chrome extension, m1 mac 

![image](https://user-images.githubusercontent.com/5360982/106217024-5abf1300-61a2-11eb-94f2-8a1a84d0e365.png)

![image](https://user-images.githubusercontent.com/5360982/106217047-627eb780-61a2-11eb-88c4-aef33886ecc2.png)

**Comment by sidarth164** [comment] 2021-02-17 08:22
I have the same issue, on macos catalina intel chip

**Comment by tgreer-bw** [comment] 2021-02-17 13:38
Make sure this is enabled in the extension settings under "manage extensions" in the browser.

![Screen Shot 2021-02-17 at 8 37 51 AM](https://user-images.githubusercontent.com/61418192/108212073-765f6e80-70fb-11eb-8e5f-43430d36ac88.png)

**Comment by sidarth164** [comment] 2021-02-17 13:41
@tgreer-bw Thanks that worked :)

**Comment by tgreer-bw** [comment] 2021-02-17 13:42
🥳  Awesome!

**Comment by cscharf** [comment] 2021-02-17 15:30
Closing this issue, please feel free to re-open @lcoiffard if this doesn't resolve the issue for you.

**Closed by cscharf** 2021-02-17 15:30 UTC

**Comment by aiotter** [comment] 2021-02-17 17:45
I cannot make it work on Chromium-based Brave browser 1.20.103 (Chromium: 88.0.4324.152) on Intel macOS Catalina, while it works on Chrome 88.0.4324.182.
Is this a problem with the browser side? I don't have any other plugin which is not operational only on Brave. I know @saegl5 made it work on Brave, so I wonder why it doesn't on my computer. I have allowed access to file URLs on both Brave and Chrome.

**Comment by Vinz87** [comment] 2021-02-21 18:33
> Make sure this is enabled in the extension settings under "manage extensions" in the browser.
> 
> ![Screen Shot 2021-02-17 at 8 37 51 AM](https://user-images.githubusercontent.com/61418192/108212073-765f6e80-70fb-11eb-8e5f-43430d36ac88.png)

I don't understand where this option is.
Are you talking about Safari or Chrome?

This issue is about Safari, and I still can't login with TouchID on a Macbook Pro M1. Which is the solution to the issue?

**Comment by tgreer-bw** [comment] 2021-02-22 13:38
That was for Chrome @Vinz87, I know not related to the title but @codeHatcher asked about it 👍

**Comment by Vinz87** [comment] 2021-02-22 17:44
> That was for Chrome @Vinz87, I know not related to the title but @codeHatcher asked about it 👍 

Thank you @tgreer-bw, but I guess the issue has been closed because of that answer regarding Chrome, so the issue regarding Safari should still be open.

**Comment by tgreer-bw** [comment] 2021-02-22 17:47
Safar isn't supported at this time, but there is another ticket open for it, as it will be a part of the next release.

**Comment by Vinz87** [comment] 2021-02-24 21:14
> Safari isn't supported at this time, but there is another ticket open for it, as it will be a part of the next release.

oh ok, could you point me to that issue?
