### ISSUE TITLE
Data loss when popup loses focus

### ISSUE THREAD

**Issue by vsviridov** [bitwarden/browser#1798] opened 2021-04-22 18:12 UTC
## Describe the Bug

When adding credentials via the browser toolbar icon, losing focus causes the popup to close, which causes it to lose all information entered.
I've already lost passwords to three different systems this way.

## Steps To Reproduce

Open the popup
Press 'Create Login' or edit existing login
change data
click outside of the popup without saving

all the input is gone.

Sometimes I generate the password, copy it in the clipboard, go to "new login" paste it, then change windows to copy the user id, for instance, which clobbers the saved password. When opening popup again the input is lost, the password is lost, and generator tab shows brand new password. Because of this there were three separate instances when the password change was triggered, and then subsequently lost via clipboard clobbering.

## Expected Result

Do not destroy data without warning, open the editor in a persistent popup

## Environment

- Operating system: Windows 10
- Browser: Firefox 87
- Build Version Version: 1.49.1

**Comment by kapitainsky** [comment] 2021-04-22 19:46
Yes it is annoying in Firefox. Until BW guys fix it open extensions in your browser and set keyboard shortcut for "Open vault in sidebar" - when activated you will have it open all the time:

<img width="1212" alt="Screenshot 2021-04-22 at 20 44 17" src="https://user-images.githubusercontent.com/15635386/115776202-c5e84200-a3ab-11eb-94fd-eb20be3ddc41.png">

**Comment by kapitainsky** [comment] 2021-04-22 19:56
Until this behaviour changes I just set extension keyboard shortcut for "Open vault in sidebar" and when activated it will stay open all the time:

<img width="1212" alt="Screenshot 2021-04-22 at 20 44 17" src="https://user-images.githubusercontent.com/15635386/115777378-18762e00-a3ad-11eb-9661-e088ff9eb5d3.png">

<img width="1420" alt="Screenshot 2021-04-22 at 20 53 42" src="https://user-images.githubusercontent.com/15635386/115777404-23c95980-a3ad-11eb-994c-3d5ba3daa9ec.png">

**Comment by vsviridov** [comment] 2021-04-22 20:02
Sure, but usually for me the flow is to go to the toolbar, since that's the easiest place to auto-fill. Having to learn a different habit for a much rarer use-case (creating logins vs logging in) is likely going to fail.

**Comment by kapitainsky** [comment] 2021-04-22 20:05
Your flow will always fail as it is now. Hopefully BW guys will fix it one day but in the meantime you have to use workaround.

**Comment by jbis9051** [comment] 2021-04-26 12:37
The popup should be persistent in general for at least a minute. Same issue when creating large secure notes.

**Comment by ikwyl6** [comment] 2021-05-01 17:19
I feel your pain @vsviridov 
This has happened to me many times. If the extension loses focus, at least keep the info there when you re-click the app icon. Can be a frustrating time..

**Comment by eliykat** [comment] 2021-05-03 22:26
Hi all, this behaviour is controlled by the browser, I don't believe we have any control over whether the popup stays open when it loses focus. In this sense, it's an upstream issue. The intended workarounds are to use the sidebar in Firefox (as suggested) or to open the popup in a new window (using the pop-out button in the top-left). I understand if those are not as good as having a persistent popup, but we're working with what we can control.

Alternatively, there is a [feature request on our forums](https://community.bitwarden.com/t/browser-extension-remembers-where-i-was/1369/) to have the popup remember its state, so that you could reopen it without any data loss. You can vote or comment on that thread to bring visibility to the issue. Any similar suggestions for solving this problem would be considered feature requests, and should be directed to the [feature requests section of the forum](https://community.bitwarden.com/c/feature-requests/5). We only use Github to track bugs and development issues.

In the meantime, as this is the expected behaviour, I'm going to close this issue. Thanks everyone!

**Closed by eliykat** 2021-05-03 22:26 UTC

**Comment by dustingraham** [comment] 2021-05-23 22:15
I have closed my LastPass account already, but I don't recall this being an issue in lastpass. If it would help, I can create a new lastpass account and see how they are handling it. I don't recall if they keep it open, or if they simply recall the progress of adding a site. Let me know if that would be helpful.

**Comment by nebula-it** [comment] 2023-07-01 02:01
@djsmith85 Does something like [this](https://stackoverflow.com/questions/21509460/avoid-panel-to-autohide-in-firefox-extension) not work?

**Comment by vsviridov** [comment] 2023-07-01 02:07
I noticed recently that the pop-up stays put, at least in chrome

**Comment by FrankyBoy** [comment] 2024-08-06 10:52
Not sure why this issue is closed? At least in Firefox it's still an issue.
