### ISSUE TITLE
Version 1.56.0 not working on Chrome

### ISSUE THREAD

**Issue by wogong** [bitwarden/browser#2336] opened 2022-02-11 02:52 UTC
### Steps To Reproduce

1. Go to 'Chrome'
2. Click on 'Bitwarden' extension
3. Click tabs other than the default Tab

### Expected Result

The extension page should jump to the respected page.

### Actual Result

Nothing happens

### Additional Context

After upgrading to version 1.56.0, the browser and all extensions were very slow.
I found this extension consumes 100%+ CPU  in the Task Manager of Chrome.

Tried logout and login again, not work.

Uninstalling the Chome Web Store version of bitwarden 1.56.0 and installing version 1.55.0 on the release page solved my problem.

### Operating System

Linux

### Operating System Version

Ubuntu 18.04.6 LTS

### Web Browser

Chrome

### Browser Version

Version 98.0.4758.80 (Official Build) (64-bit)

### Build Version

version 1.56.0

**Comment by wogong** [comment] 2022-02-11 02:54
#2335 reports a similar problem.

**Comment by aaronransley** [comment] 2022-02-11 02:56
Also noting very slow performance on Chrome:
Version 98.0.4758.82 (Official Build) (64-bit)

**Comment by francoisauclair911** [comment] 2022-02-11 03:15
Same here
v1.56.0
Chrome Version 98.0.4758.82 (Official Build) (64-bit)

**Comment by fengkaijia** [comment] 2022-02-11 03:25
+1 for performance issue on Ubuntu 20.04 with Version 98.0.4758.80 (Official Build) (64-bit).

There are also plenty of people reporting the same issue on the forum: 

https://community.bitwarden.com/t/no-2-fa-slowness-on-new-bitwarden-chrome-extension-after-update/37837

**Comment by lazylizardv2** [comment] 2022-02-11 03:25
Wonder if this is a Chrome or Bitwarden bug, I'm not sure how close Vivaldi and Brave are to the original Chrome browser.

**Comment by andychongyz** [comment] 2022-02-11 04:25
Manually log in with the master password, lock it and the biometric auth works again. Pretty sure the 1.55 to 1.56 upgrade have something wrong.

**Comment by arinoki** [comment] 2022-02-11 05:22
Chromium 98.0.4758.82  - same high cpu usage problem, installed 1.55 for now. Maybe we have some miner now? Hope not.

**Comment by andychongyz** [comment] 2022-02-11 07:18
Manually log in with the master password, lock it and the biometric auth works again. But if I quit chrome and relaunch it, the same problem happen again.

**Comment by SchneiderSam** [comment] 2022-02-11 07:55
Same here.

**Comment by wogong** [comment] 2022-02-11 09:09
This problem still exists in [Version 1.56.2](https://github.com/bitwarden/browser/releases/tag/v1.56.2)

**Comment by rafiron** [comment] 2022-02-11 12:04
> Also seeing extremely slow performance on Mac OS Mojave with 1.56.0 extension and latest Brave ([Version 1.35.101 Chromium: 98.0.4758.87 (Official Build) (arm64)]).
> 
> Also, biometric unlock does not work - the desktop app (1.30.0 build 1935) opens and prompts for Touch ID but even after authenticating, the extension doesn't unlock.

I'm facing the same issue when trying to unlock using Touch ID, the extension just gets stuck at 'Awaiting confirmation from desktop'.

**Comment by alphasystems** [comment] 2022-02-11 12:55
We have the same issue as well. We tried on the following browsers: Brave & Vivaldi. Both have the same issue. We reinstalled the extension but we still experience the same issue. For now we downloaded the Windows Client and we use it for the time being but obviously that's not ideal.

**Comment by Diego-Schmidt** [comment] 2022-02-11 13:30
Bitwarden not working on chrome, it shows a padlock on the app icon... what is happening?

**Comment by cscharf** [comment] 2022-02-11 13:55
Thank you for the report, this has been fixed and will be released shortly v1.56.3, closing this as a duplicate of #2335

**Closed by cscharf** 2022-02-11 13:55 UTC
Labels: bug, duplicate

**Comment by Bark33p3r** [comment] 2022-02-11 15:18
every record is shown as "[error: cannot decrypt]"
As soon I klick on one it shows the values

**Comment by arinoki** [comment] 2022-02-11 19:54
> Thank you for the report, this has been fixed and will be released shortly v1.56.3, closing this as a duplicate of #2335

Thanks. Actually fixed in 1.56.3. Seems need time to be updated on chrome store? (and maybe others, didnt check)
