### ISSUE TITLE
BitWarden v1.25 crashes Safari on M1 Mac

### ISSUE THREAD

**Issue by Tinrobotguy** [bitwarden/browser#1724] opened 2021-03-19 20:29 UTC
## Steps To Reproduce

4. Click on '...'

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina] Big Sur on M1 Mac
- Browser: [e.g. Firefox 73.0.1]
- Build Version (go to "Settings" → "About" in the app): [e.g. 1.42.2]

**Comment by rjosborne** [comment] 2021-03-21 11:08
To help add a little more context here:

www.currys.co.uk crashes safari every time for me

MacBook Air M1, 512GB, 16GB
macOS Big Sur 11.2.3
Safari 14.0.3
BitWarden 1.25.0

Disabling the browser extension stops the crashes from occurring.

**Comment by fbuchner** [comment] 2021-03-22 09:58
Same here. Adding some additional details:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '<cert(0x162692b10) s: *.wesco.de i: Encryption Everywhere DV TLS CA - G1> does not conform to NSSecureCoding'
terminating with uncaught exception of type NSException
abort() called

No other extensions were enabled in Safari, device and versions are the same as with @rjosborne

**Comment by dotsam** [comment] 2021-03-22 22:08
This looks to be a duplicate of the poorly titled #1694

**Comment by cscharf** [comment] 2021-03-23 21:13
> This looks to be a duplicate of the poorly titled #1694

Indeed it is. Closing this as a duplicate for now, please follow the thread over there for updates. Thanks!

**Closed by cscharf** 2021-03-23 21:13 UTC
Labels: duplicate
