### ISSUE TITLE
Slow performance in Chrome - extension not displaying text as I type

### ISSUE THREAD

**Issue by adamjstewart** [bitwarden/browser#1854] opened 2021-05-19 03:39 UTC
## Describe the Bug

When I click on the Chrome extension, whether I'm typing in my email/password or searching the vault, I usually can't see any of the text that I'm typing. Similarly, trying to check or uncheck boxes won't display any change unless I come back to that menu option again. Overall, the extension appears to be slow and unresponsive.

## Steps To Reproduce

1. Click on the Chrome extension
2. Type in the search bar

## Expected Result

I would expect the extension to run smoothly without any lag and display the text I type.

## Actual Result

The extension is laggy and doesn't show text as I type or takes a few seconds to display text.

## Screenshots or Videos

Let me know if you want screenshots/videos to debug the problem.

## Environment

- Operating system: macOS Catalina 10.15.7
- Browser: Chrome 90.0.4430.212
- Build Version: 1.50.0

## Additional Context

I actually just switched to Bitwarden from LastPass and I was seeing a very similar bug with the LastPass extension. This leads me to believe that there may be something wrong with my setup, such as a different Chrome extension that interferes with both. The following user reported the exact same issue as me: https://www.reddit.com/r/Bitwarden/comments/eedrk8/chrome_extension_not_displaying_text_as_i_type/

**Comment by anders-f** [comment] 2021-05-21 12:37
Have the same issue. The plugin is totally unusable. Worked fine before.

**Comment by eliykat** [comment] 2021-06-10 21:51
Related to #1209.

**Comment by slores** [comment] 2021-06-11 01:14
I have similar issue.  This happens on my Mac M1 - running 11.5 using Chrome - Version 91.0.4472.77 (Official Build) (arm64) or Chrome-Beta Version 92.0.4515.39 (Official Build)(arm64) or Brave or Safari.
There is a lag when I try to edit an item's notes or try to see a hidden field using the extension.

**Comment by slores** [comment] 2021-06-12 00:43
Update:
When I use the pop out to new window from the extension, the issue goes away.

**Comment by luis-valerio** [comment] 2021-06-15 19:13
This is also happening for me, it doesn't happen on other browsers like Firefox or Brave, but it does happen on Chrome (running latest version as of this writing). The lag is most noticeable when typing the body of a "secure note", the lag is quite severe, which has lead me to stop using it on Chrome altogether (at least until this issue is fixed).

**Comment by jmeridth** [comment] 2021-06-28 21:54
@eliykat please note the original ticket #1209 was from 4/16/2020, so closing it, we shouldn't hide how old this bug is.  All good this ticket has "more info" but can y'all prioritize this bug?  Or is it "pull requests are welcome" kind of situation?

**Comment by eliykat** [comment] 2021-06-28 22:59
This is a tricky one because there are no clear steps to reproduce and it's unclear what hardware/software/whatever combination is causing it. No-one on the team has experienced this issue which makes it difficult to debug.

The fact that the slowdown occurs when editing a field makes me think that it's to do with Angular change detection. However I don't know why that would be different in the popup vs. popout window.

A few thoughts / questions if you or anyone else wants to help dig into it further:
* does this affect all text fields, or only some? If so, which?
* are you running an M1 or Intel Mac?
* do you experience this behaviour across the major browsers?
* does disabling other extensions help?
* does toggling hardware acceleration in the browser make any difference?
* are there any error messages printed to the console? (Chrome is the easiest to right-click the popup and click inspect)
* can you reproduce the issue while running Safari Timeline (make sure to disable "stop recording once page loads"), then provide a copy of its output?

**Comment by jmeridth** [comment] 2021-06-29 02:55
@eliykat 
- yes, this affects multiple fields (TOTP, Notes, URI) - aka all text fields but username and password
    - please note that Notes will start working if you scroll down to view it, but not on initial load of the plugin.
- Intel Mac
```
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,2
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	2 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	512 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	1554.120.19.0.0 (iBridge: 18.16.14663.0.0,0)
```
- Only Chrome (Firefox, Brave, Safari all work fine)
`Chrome: Version 91.0.4472.114 (Official Build) (x86_64)`
- I've uninstalled every other extension and it still occurs
- No, toggling hardware acceleration makes no difference
- No messages in dev console
- Again, this does not occur in Safari for me.  I could not reproduce while using Timeline.

Hope this helps

**Comment by LucasMolander** [comment] 2021-06-29 17:56
I have the same issue - Chrome extension on Mac feels like it either hangs up or simply doesn't update displayed text while editing Notes.

It *does* know what the updated text is because when I drag the thing in the bottom right, it immediately and reliably updates the text of the note to what I typed.

### Chrome
`Version 91.0.4472.114 (Official Build) (x86_64)`

### Mac
```
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	6-Core Intel Core i9
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Hyper-Threading Technology:	Enabled
  Memory:	32 GB
  System Firmware Version:	1554.120.19.0.0 (iBridge: 18.16.14663.0.0,0)
  Serial Number (system):	C02XF5UXJGH5
  Hardware UUID:	85FEEB28-5542-55E7-BE63-C3929C69B52F
  Provisioning UDID:	85FEEB28-5542-55E7-BE63-C3929C69B52F
  Activation Lock Status:	Disabled
```

**Comment by slores** [comment] 2021-06-29 18:40
If you use the "Popup to New Window" on top left of the extension window, everything works much better.  I guess this can be a temp fix until someone fixes the ext.

**Comment by jmeridth** [comment] 2021-06-29 19:02
@slores thanks for the tip.  I just mouse out of the field like @LucasMolander currently and the field does populate.

**Comment by slores** [comment] 2021-07-01 17:35
@jmeridth, Thanks! yeah that seems to work with a little delay for me.  I will probably stick to the popup method though.  Hopefully BW will fix this soon

**Comment by eliykat** [comment] 2021-07-01 20:40
@slores, you mentioned above that you're able to recreate this on Safari. Could you use the [Timeline feature](https://support.apple.com/en-au/guide/safari-developer/dev59adba03f/mac) to record some performance information and then share it here? (Provided it doesn't accidentally capture any private info)

**Comment by slores** [comment] 2021-07-01 21:15
@eliykat - I just installed Mac OS Monterey beta.  It seems to be working now but the ext window is smaller which makes the user having to scroll to see the details.  And I can't seem to make it larger/longer.

**Comment by Krychaz** [comment] 2021-07-05 16:58
Performance issue with our extension window being very slow and unresponsive was pinpointed by one of our customer who found out that it is caused by using an external display over thunderbolt. Some solutions have been provided here: https://stackoverflow.com/questions/56500742/why-is-my-google-chrome-extensions-popup-ui-laggy-on-external-monitors-but-not

and it seems it is also an open issue over at: https://bugs.chromium.org/p/chromium/issues/detail?id=971701#c64

**Comment by adamjstewart** [comment] 2021-07-05 17:23
I can confirm that this issue only affects me when using an external display (over HDMI), the issue doesn't occur on my laptop.

**Comment by eliykat** [comment] 2021-07-05 20:22
Thanks @Krychaz for the find!

**Comment by slores** [comment] 2021-07-05 22:00
> I can confirm that this issue only affects me when using an external display (over HDMI), the issue doesn't occur on my laptop.
 Seems like it works on my laptop but not on ext monitor

**Comment by jmeridth** [comment] 2021-07-05 22:11
@Krychaz I can confirm also.  Works on laptop window.  Issue is on external monitors. Nice find and thank you for sharing.

**Comment by neomorina** [comment] 2021-07-06 08:28
Same Problem!
I am running it on Mac OS Big Sur.

**Comment by alphonseb** [comment] 2021-08-23 18:49
Same problem - Mac OS Big Sur - on external monitor via HDMI

**Comment by jikamens** [comment] 2021-10-08 16:04
Please be specific about the right way to side-load the fix into Chrome to test it. I don't want to mess around myself and potentially do it wrong.

**Comment by eliykat** [comment] 2021-11-24 04:31
Sorry for the late reply @jikamens. I appreciate your feedback, and based on that we've merged that PR. The fix will be in the upcoming release (currently scheduled for 7 December). I'm going to close this thread, however if you (or anyone else) still experiences this issue after upgrading to the December release, please ping me here and I'll reopen for further investigation.

**Closed by eliykat** 2021-11-24 04:31 UTC
