### ISSUE TITLE
No prompt (add login notification) offered to save the credentials for some sites

### ISSUE THREAD

**Issue by Moxville** [bitwarden/browser#320] opened 2017-10-21 08:54 UTC
Hi Kyle,

Today I tried adding credentials for some new sites via. extension. For some sites I got the prompt and for some sites I did not get the prompt
a) The prompt I get to save the credentials is not constant "Should bitwarden remember this password for you?". During site login time the prompt appears and disappears few times (not constant). Eventually I could click the button to save the credentials.
But i think the "prompt" should be constant until the user decides

b) For below mentioned sites I logged-in i did not see this prompt "Should bitwarden remember this password for you?" . I tried few times again but no prompt to save the credentials
https://www.isaca.org
https://forum.glasswire.com/
https://ebiz.licindia.in
http://www.m-hddl.com/
https://mega.nz/
https://www.overclock.net/login
https://freescan.qualys.com/freescan-front/
https://www.scribd.com/
https://www.snapdeal.com/
https://home.sophos.com/
http://www.timesjobs.com
http://www.vn-zoom.com/
https://www.sevenforums.com/
http://forum.pdf.wondershare.com/

Browser I use Vivaldi 1.12.955.38 (Stable channel) (32-bit)
Bitwarden extension v1.19.1 (installed)

**Comment by kspearrin** [comment] 2017-10-21 18:38
a) This is because the website is likely loading a new page. We cannot show the prompt until the page has been loaded again.

b) These are all caused by websites that are creating login forms in some exceptional way. I have gone through them all and have added fixes for the following cases.

http://www.m-hddl.com/
https://home.sophos.com/
https://www.sevenforums.com/
https://freescan.qualys.com/freescan-front/
https://www.scribd.com/
http://www.timesjobs.com
http://www.vn-zoom.com/
http://forum.pdf.wondershare.com/

As for the others, I have no fix at this time. Thanks for all the examples though.

**Comment by Moxville** [comment] 2017-10-22 04:01
Thank You for the fixes. If I come across such similar sites (if any) will post it

**Comment by snhv** [comment] 2017-11-22 04:49
I concur this issue, even with google.com!
With Chorme, no prompt at all with google.com or github.com
With Firefox, prompt appears but credentials are not saved in vault.
I'm new to bitwarden so I haven't tried many sites.

**Comment by kspearrin** [comment] 2017-11-22 04:51
@snhv I just tested github.com and it works just fine.. Is your vault unlocked?

**Comment by snhv** [comment] 2017-11-22 05:04
Hi Kyle, that's fast!

Ok i tested again with vault unlocked. It works in both Chrome and Firefox. Tho I remember when I did that like 8 hrs ago, vault unlocked, it didn't work, but nevermind. Thanks.

However, should bitwarden recognizes and conveniently prompts us for unlocking vault?

Some other suggestions (sorry for duplicate if any):
- auto focus to password field when clicking on toolbar icon during locked;
- auto refresh site icon (bitwarden is using gmail icon instead of a more appropriate google icon because I logged in google through gmail first).

Thank you.

**Comment by autokiller677** [comment] 2018-06-04 10:10
I just experienced the same behaviour on community.bitwarden.com.
I created a new account and did not get a prompt to save the credentials.

**Comment by moham96** [comment] 2018-06-15 11:21
same problem on https://discourse.coreelec.org/ I think the problem is in any site that uses [discourse](https://discourse.org) like https://community.bitwarden.com
@kspearrin any updates on these sites ?

**Comment by garaboncias** [comment] 2018-11-08 12:32
same for https://protonvpn.com

**Comment by Cereal-Killa** [comment] 2018-12-12 19:16
Same here on many different websites. I'm a long time robotform user and their extension does an amazing job on this criteria.

**Comment by kspearrin** [comment] 2018-12-12 19:20
@moham96 The discourse cases should now be fixed.

**Comment by jswinner** [comment] 2019-02-03 17:19
No add login prompt for community.bitwarden.com using FF 65 Ubuntu snap edition.

**Comment by now-im** [comment] 2019-02-14 10:45
not working on bdjobs.com

**Comment by jdgregson** [comment] 2019-07-09 21:13
I haven't actually seen the "Add Login" prompt at all, on any website, which is very disconcerting. This worked flawlessly with LastPass.

**Comment by xeor** [comment] 2019-07-10 22:15
Same here.. Currently evaluating bitwarden, but still havent seen the "save password" prompt (after 5+ different pages)

**Comment by jdgregson** [comment] 2019-07-11 16:41
@xeor It's possible that you're just not noticing it. Unlike the LastPass prompt, which is a box that slides in from the right, the Bitwarden prompt is a top bar like Chrome messages which spans the top of the site. I found that it is already there when the page loads, with no movement or visual indication that something needs your attention, so it's really easy to miss, or mistake for part of the site. I'd prefer if the Bitwarden team revisits that prompt and makes it more distinct and attention grabbing.

**Comment by BlueGreenMagick** [comment] 2019-07-13 07:01
not working for streamable.com, and many other sites as well.

**Comment by Furax-31** [comment] 2019-07-14 10:19
I think there is a problem, Bitwarden no longer offers me to save my credentials and passwords.

**Comment by kspearrin** [comment] 2019-07-14 11:29
It would be helpful if you shared which browser you all are using.

**Comment by Furax-31** [comment] 2019-07-14 18:36
Same problem with Firefox 69 Beta. Windows 10 - 64 Bits

**Comment by BlueGreenMagick** [comment] 2019-07-14 22:20
I am using Firefox ver69.0b4 64-bit on windows 10

**Comment by kspearrin** [comment] 2019-07-14 23:01
Looks like there was a bug in latest Firefox release. Should be fixed in v1.40.1

**Comment by markandersonus** [comment] 2019-08-16 17:10
I have the same issue on Chrome on Win 10. I don't recall EVER being asked to add a new site. (I get prompts to update password). Trying to push it for our Enterprise, but hard work when CFO has to enter every single login to the vault manually

Trying to get him off RoboForms, which ALWAYS asks to add a new site, as did my LastPass

**Comment by silasdavis** [comment] 2019-08-23 09:35
Coming to this a Bitwarden user and developer of a login form. My login form is generate a prompt to save password but my sign up form is not. As far as I can tell all of my fields are semantically marked up with, for example `autocomplete=new-password`. It's obviously a far superior experience if bitwarden will remember (ideally generate) password on first entry.

What heuristics do you use for this?

The site is a single-page-app so there is no true reload and the forms have no action or method attributes. I wonder if that is a problem?

**Comment by funnell** [comment] 2019-10-14 16:38
At some point I stopped being able to automatically add passwords, although I can't remember when this happened. Sometimes I see the Bitwarden bar at the top of the page but I only see the logo on the left and an x on the right. I'm using Safari 12.1.2.

**Comment by postigny** [comment] 2020-01-29 18:01
Same problem here with Chrome 79 on Windows. Sometime it works, sometime not

**Comment by bauerp** [comment] 2020-03-10 14:44
Often doesn't prompt using Macos Safari 13.0.5. 

Example: https://www.bebe.com

**Comment by palytoxin** [comment] 2020-05-22 00:52
It seems like a common problem.
same problem in https://crowdin.com/

**Comment by onderbagci** [comment] 2020-07-07 07:29
I have this issue on Twitter web and some other sites I didn't care at the time.
Windows 10 / Chrome 83.0.4103.116

**Comment by aelsharawi** [comment] 2020-08-04 19:51
me too

**Comment by aelsharawi** [comment] 2020-08-04 19:52
no solution after 3 years?

**Comment by cscharf** [comment] 2020-08-04 22:27
> no solution after 3 years?
This, unfortunately has been an evolving problem (fixed quite a few times) and will always exist to a degree. Anyone who can jump in to offer help (added the `help wanted` label) is more than welcome to take a look at the auto-fill matching and logic. A fair degree of the sites experiencing issues will be 1-off fixes that are necessary although some of the general auto-fill issues described in this thread are likely interlinked with a similar or same root cause.

This is on our radar to start looking at but we do welcome anyone willing to jump in ahead of time.

Thanks for your patience and support of Bitwarden!

**Comment by PrinceMerluza** [comment] 2020-08-12 02:35
I'm glad I'm not the only one having this issue. I'm new to using Bitwarden and I forgot to save the generated password as I was expecting it to prompt me to save the newly registered credentials (it didn't) and I copied something else to the clipboard already. Anyway, I guess it'll just be manual saving for such sites.

**Comment by jdgregson** [comment] 2020-08-12 21:45
I've already developed the habit of creating the entry in BitWarden before signing up for an account after going through that too many times.

**Comment by KaiDevrim** [comment] 2020-11-30 18:42
I have never gotten a prompt in any website and I am using Edge (Chromium) Dev latest.

**Comment by stonelazy** [comment] 2020-12-11 03:26
I just recently migrated from LastPass, i have never had this problem. But in Bitwarden it is a consistent issue of not offering to save password in so many websites. One website that i recently faced issue with is https://leetcode.com

**Comment by Talk2Giuseppe** [comment] 2021-01-14 15:13
Adding to the list that the issue is random and intermittent.  Kinda annoying on the reliability side.  Would be a nice piece of software if reliable and stable.  At the moment, I can't suggest it to anybody.  Seems weird that browsers can consistently offer to save PWs, but not BitWarden.

**Comment by dave-castle** [comment] 2021-01-20 20:06
Migrated from 1password due to selfhosting feature, but got also no prompt for pw saving, so I am thinking to move back 😔

**Comment by jdgregson** [comment] 2021-01-20 20:15
It's also important to note that when I do see the "Save Password" prompt, it flashes every second as if it is being removed from the DOM and re-added. I have seen this on several browsers and affecting several users on different computers.

**Comment by Tursko** [comment] 2021-01-25 16:20
I've faced this issue for 6 months or so. It's one of the only things stopping me from switching family members over to the service. I encounter it somewhat randomly on even common sites. Last night my brand new gmail login did not prompt to 'save on Bitwarden'.

**Comment by ztlevi** [comment] 2021-02-02 07:38
same on www.ticktick.com

**Comment by soberhofer** [comment] 2021-02-06 11:51
I have setup BitWarden and am Using it on macOS. I've installed the Desktop Application and the Safari Extension, via the App Store. I've tried logging in to existing accounts as well as creating new ones in Safari on various Sites. Bitwarden never prompted me to save the credentials. Using Safari 14 on macOS Big Sur. 
seeing as the issue is over 3 years old it doesn't look like it's going to get fixed, or looked at, is it?

**Comment by denzilc** [comment] 2021-02-16 23:33
What makes this behavior possible on LastPass but not on Bitwarden? 

In addition, assuming this doesn't work - what's the recommended workaround or solution?

**Comment by cscharf** [comment] 2021-02-17 01:02
We are currently looking at a more holistic approach to these issues and have someone actively looking into it now.

**Comment by eliykat** [comment] 2021-02-17 02:09
@denzilc It's a tricky problem to solve, as there are many ways of designing login and password change forms, and our script has to capture as many as possible.

As a workaround in the meantime, you can create the login in the Bitwarden browser extension first, and then autofill it into the registration form.

**Comment by 5abred** [comment] 2021-02-18 12:16
I've seen this issue on some websites like raidforums, mangadex, ..etc, but never on other websites and I've read that its fix is pending so I'm trying to set the login before but it's really annoying, hoping for a solution but seeing that this is a 3 years old issue I'm skeptical.

**Comment by xeor** [comment] 2021-02-18 12:20
Anyone with insights on what's needed to get sites supported as default? Maybe we, the people in this issue can also contact a bunch of those sites that are not working. But then we need something to tell them, what to change so they will work

**Comment by 5abred** [comment] 2021-02-18 13:46
> Anyone with insights on what's needed to get sites supported as default? Maybe we, the people in this issue can also contact a bunch of those sites that are not working. But then we need something to tell them, what to change so they will work

I don't it's something wrong with the website itself rather with the logic of the software for example Lastpass works well with Raidforums but bitwarden won't.

**Comment by xeor** [comment] 2021-02-18 14:09
> > Anyone with insights on what's needed to get sites supported as default? Maybe we, the people in this issue can also contact a bunch of those sites that are not working. But then we need something to tell them, what to change so they will work
> 
> I don't it's something wrong with the website itself rather with the logic of the software for example Lastpass works well with Raidforums but bitwarden won't.

That might also be because lastpass is a much bigger company and can use a lot more resources on one-off fixes for specific pages. In bitwardens case, those resources might very well be the community

**Comment by bd-g** [comment] 2021-02-18 15:53
I haven't actually seen the "Add Login" prompt at all, on any website. I have tried a variety of common websites too, with vault unlocked.

**Comment by eliykat** [comment] 2021-02-18 20:24
@xeor I appreciate the offer, but for now I think it's on us to improve the detection algorithm for the save prompt. The `help wanted` tag still applies if anyone has the skills & time to dive into the code.

**Comment by xeor** [comment] 2021-02-18 20:37
> @xeor I appreciate the offer, but for now I think it's on us to improve the detection algorithm for the save prompt. The `help wanted` tag still applies if anyone has the skills & time to dive into the code (but we're working on it at our end either way).

This issue is old, and it might be time to attack the problem from multiple angles?

Community can help with pushing on the site-owners, what about making a procedure for how we can complain to them, and what we can ask them? I bet a lot of pages want to support password-safes, but they are not aware how to..

We can help with specific sites, making regex, xpath or javascript queries for detecting forms on specific sites. But where can we give those specific back to you, the app-makers? What about making an issue-template for that with some info? At least a label?

For the users that sees these problems.. What about a function in the app to report a broken page?


There are more and more clipboard managers lurking around as well, so not having a stronger focus on this problem will only push our passwords into the clipboard-managers history, which is a bad thing...

Please, some urgency!

**Comment by cscharf** [comment] 2021-02-18 21:48
> We can help with specific sites, making regex, xpath or javascript queries for detecting forms on specific sites. But where can we give those specific back to you, the app-makers? What about making an issue-template for that with some info? At least a label?

For submitting issues on specific sites to us, please consider visiting this issue which has a link to a form for reporting these: https://github.com/bitwarden/browser/issues/1620

> For the users that sees these problems.. What about a function in the app to report a broken page?

Will have to give this some thought, but not a bad idea either.

Overall this has been an intermittent issues with several sites working then not working, then working, our team not being able to reproduce failures, etc. We are now starting to dedicate resources to tackling it and hope to start making marked improvements soon. Thanks!

**Comment by eliykat** [comment] 2021-02-18 22:27
Thanks everyone for your feedback in this thread. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1620. Please also direct any discussion or questions to that issue. This issue will now be closed.

**Closed by eliykat** 2021-02-18 22:27 UTC
Labels: help wanted

**Comment by kevinjmcmahonjr** [comment] 2021-03-29 22:33
I just tested this out on Yahoo and Protonmail and whether creating a new account or updating an existing account I got no prompt... This now requires me to set the clear clipboard setting to much longer than the 20 or 30 seconds I was planning on setting it to. In both test cases I didn't have enough time to save the password that was generated and copied to the clip board and then trying to change the password on a newly created account was not a fun time. I'm going to set it to 5 minutes for now I suppose.

I'm coming from LastPass and I already paid for their service so I'm not one of the many flocking to BitWarden because LastPass has changed their free service. I've been paying for it for 5 or more years. I'm just evaluating for myself to make recommendations to others and to see if Bit Warden works better for me as there are plenty of things LastPass annoys me with.

This is a huge issue and makes it hard to recommend to less tech savvy people. Yes, this issue exists with all password managers but I'm truly disappointed to see how poorly it is working with Bit Warden, this is my only major complaint so far. I'm going to continue to use it for myself to see what else bothers me, but I just know for a fact this is a deal breaker to too many other people especially when LastPass just works 90% of the time. LastPass is also significantly better at auto-filling user name and passwords.

I submitted both sites to the Google Form.

I hope this gets further improvement, I know how difficult it is to make this work on all sites, but other password managers have done better with it. If I knew how to fix it I'd contribute, but that's for people smarter than me to figure out.

**Comment by akasnilhaq77** [comment] 2021-12-08 13:37
> same for https://protonvpn.com

same problem faced for [applybdjob.com](https://applybdjob.com/)
Should i use protonvpn.com ?

**Comment by akasnilhaq77** [comment] 2021-12-08 13:38
Chrome Isn’t Asking To Save Passwords – How To Fix?

**Comment by djsmith85** [comment] 2021-12-08 17:43
Hi @akasnilhaq77 this issue was closed to combine the reports into https://github.com/bitwarden/browser/issues/1620. This makes it easier to track these kind of things. Please have a look there and add all details to the report, if this is still an issue. 

A hint for now, if the extension is locked then no save prompt appears. This was fixed and will be available in the next release which will be rolled out in the next couple of days.

**Comment by deshdunianews24** [comment] 2021-12-13 18:06
same problem faced for  [BD jobs today ](https://bdjobtoday.xyz).  How to solve?
