### ISSUE TITLE
[Chrome] Bitwarden extension slows down file upload selection

### ISSUE THREAD

**Issue by kalpik** [bitwarden/browser#848] opened 2019-01-29 15:14 UTC
Hello,

I've been noticing this forever, but only today took the effort of disabling individual extensions, and found that Bitwarden was the culprit.

If Bitwarden extension is enabled, whenever there is a browse button on a site, and you chose a file to upload, after selecting a file, there is a gap of about 1-2 seconds in which any other buttons/fields on the form become unresponsive.

Steps to reproduce:

1. Go to https://cgi-lib.berkeley.edu/ex/fup.html (Sample site)
2. Click on 'Choose File'
3. Select a file and click 'Open'. At this point, the file selection dialog box will close.
4. Immediately try entering anything in 'Notes about the file' text field, you will notice you cannot do that for a second or so.

If you repeat the steps with Bitwarden extension disabled, the lag will not be present.

Please let me know if more information is needed, and I'll be happy to help.

Thanks!

**Comment by kspearrin** [comment] 2019-02-02 17:12
Unfortunately I am not able to reproduce with Chrome on Windows 10. Can you try creating a new user profile and see if the issue persists there too?

**Comment by eliykat** [comment] 2021-02-17 01:46
Hi @kalpik, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by eliykat** 2021-02-17 01:46 UTC
