### ISSUE TITLE
Clicking the launch button auto-fills the first matching item instead of the clicked item

### ISSUE THREAD

**Issue by anne17** [bitwarden/browser#869] opened 2019-02-14 15:11 UTC
With auto-fill activated, when searching for an item/login and clicking the launch button I expect that the item I clicked on will be auto-filled. This works as long as the item I click on is the first item to match the launched URL. But when several logins are saved under the same URL, Bitwarden will auto-fill with the data of the first matching item.

I am using version 1.38.0 in Chrome (v 72.0.3626.81).

**Comment by TargetCrafter** [comment] 2020-04-30 09:06
I'd like to bring atention to this issue again. We would like to switch to Bitwarden at our company, and this is a feature we use very often in 1password. 
The way it works now is very counter-intuitive as you are clicking on the launch icon next to a specific login, not just an uri..

**Comment by CDeLeon94** [comment] 2020-08-10 23:13
Same issue

**Comment by TargetCrafter** [comment] 2021-01-26 08:25
I'd like to bump this issue again, as itstill exists in version 1.48.0 of the Google Chrome plugin.

**Comment by cscharf** [comment] 2021-01-26 21:24
I honestly thought we had fixed this. Will re-surface this with the team to have someone take a look. You should see the credential you "launched" as sorted to the top of the list on that page in the "Tab" tab of the extension, this is the same sorting that's used to autofill so if that's not working (one way or the other) we'll take a look.

Thanks!

**Comment by cscharf** [comment] 2021-01-26 21:29
Ah, never-mind, sorry, I knew this seemed/sounded very familiar, but please see discussion here: https://github.com/bitwarden/browser/issues/1391

Closing this as a duplicate of that and please feel free to follow up and up-vote from the community forums for this particular enhancement.

**Comment by cscharf** [comment] 2021-01-26 22:12
I am usually not this dense, sorry @anne17 et. all., @eliykat , perhaps something you can look at, @addisonbeck resolved this with https://github.com/bitwarden/browser/issues/1391 and it may have been a regression but just need to be sure.

**Closed** 2021-01-28 20:35 UTC

**Comment by mackaaij** [comment] 2024-10-12 15:10
Still/again an issue in Google Chrome's Bitwarden 2024.10.0. If you search your vault for a website that has multiple login items in Bitwarden and specifically choose one to launch, Bitwarden has a preference for the one to prefill (maybe alphabetically). Expected behavior is to fill the item for which the launch icon was selected.

Seems to be a regression every now and then, see #869, #1391, #1428, #1576, #1958
