### ISSUE TITLE
Pop Out window prevents timed auto lock of vault

### ISSUE THREAD

**Issue by bung69** [bitwarden/browser#1221] opened 2020-05-05 13:38 UTC
Version: 1.43.4

when using the Bitwarden chrome browser extension,  with "pop out to a new window" the vault does not automatically lock after the time out set in Settings > Security > lock options.

The pop out window could easily end up hidden behind another window and be unlocked indefinitely.  seems like an oversite.  

thanks

**Comment by kspearrin** [comment] 2020-05-05 13:41
The timeout timer only starts if the popup window is closed, including if it is popped out. This is the expected behavior.

**Comment by Jacalz** [comment] 2020-10-15 10:45
I think this perhaps should be changed. Popping out the extension is a great way to have it open like an external application without having to have the browser open at all times for grabbing passwords and other stuff.

**Comment by JonathanLindsey** [comment] 2021-03-22 01:15
It looks like this is a duplicate of #1334. And there is more discussion over there.

**Comment by eliykat** [comment] 2021-03-22 03:24
Closed as a duplicate of #1334, thanks @JonathanLindsey

**Closed by eliykat** 2021-03-22 03:24 UTC
