### ISSUE TITLE
[Bug] IMPORTANT Extension really long to open in safari

### ISSUE THREAD

**Issue by hexicans** [bitwarden/browser#1732] opened 2021-03-23 09:13 UTC
## Describe the Bug

Since the last update 15 days ago, when you click on the Safari extension in the browser on mac, the extension takes a long time to open. Today's update did not fix the problem and it annoys many users, me the first! We have the impression that Bitwarden does not hear this bug which is very disturbing!

## Steps To Reproduce

https://user-images.githubusercontent.com/13521851/112122011-22dfb500-8bc0-11eb-9867-896897fa9ec1.mov

## Actual Result

When we click, we must wait 2 seconds and Bitwarden open

## Screenshots or Videos

Already sent 

## Environment

- Operating system: Mac OS Big Sur  - MacBook Pro 2019 (bug is present on last m1 MacBook too)
- Browser: [e.g. Firefox 73.0.1] SAFARI 14
- Build Version (go to "Settings" → "About" in the app): 1.49.1

**Comment by zgafford** [comment] 2021-03-27 18:25
I'm seeing the same issue in the latest App Store update (1.49.1). M1 Mac Mini

**Comment by hexicans** [comment] 2021-03-30 11:26
Any news about the issue ?

**Comment by Tinrobotguy** [comment] 2021-03-30 13:47
I'm seeing the same problem, but not exclusively in Safari.  Anytime I open Bitwarden, even the desktop app, it is slow to load and takes up to 5 seconds on both M1 Mac and older iMac.

**Comment by hexicans** [comment] 2021-04-15 21:06
Please ...

**Comment by cscharf** [comment] 2021-04-15 21:15
Hi @hexicans , thanks for the report, however we've not been able to reproduce this issue per-se. I know @eliykat was looking at several performance issues, but not with Safari specifically (rather very large vaults).

Can you perhaps trace through the timing using your browser's dev tools to get a gauge on which aspect of the load/open routine is taking the longest?

I know we will be releasing a universal build for M1 native here shortly, however until then we're also relying on Rosetta2 which is pretty cumbersome for our macOS app and may impact Safari in this context as well. We've found other issues with Safari's new Web Extensions which we're patiently waiting on the latest Safari tech preview fixes to drop to the main release to resolve.

Any additional information you can provide on tracing, dev tools breakdowns, etc. I believe would really help determine if this is the decryption, context loading, rendering, asset loading, etc. or underlying internals (Safari) that's causing the issue(s).

**Comment by Tinrobotguy** [comment] 2021-04-15 21:45
To be clear, this issue persists on both my M1 MacBook air and my iMac, which is running Catalina, so not limited to the M1 or Big Sur.

**Comment by shasycouk** [comment] 2021-04-16 19:48
I'm having the same problem too. I moved to right-clicking and accessing BitWarden from there. A lot faster to fill than having to rely on clicking the extension button.

Now if only Touch ID unlock would work in the Safari extension..

**Comment by hexicans** [comment] 2021-04-17 08:47
> Hi @hexicans , thanks for the report, however we've not been able to reproduce this issue per-se. I know @eliykat was looking at several performance issues, but not with Safari specifically (rather very large vaults).
> 
> Can you perhaps trace through the timing using your browser's dev tools to get a gauge on which aspect of the load/open routine is taking the longest?
> 
> I know we will be releasing a universal build for M1 native here shortly, however until then we're also relying on Rosetta2 which is pretty cumbersome for our macOS app and may impact Safari in this context as well. We've found other issues with Safari's new Web Extensions which we're patiently waiting on the latest Safari tech preview fixes to drop to the main release to resolve.
> 
> Any additional information you can provide on tracing, dev tools breakdowns, etc. I believe would really help determine if this is the decryption, context loading, rendering, asset loading, etc. or underlying internals (Safari) that's causing the issue(s).

Hello

Thanks for your reply, but I don't know how to control the extension loading time. I know how to do this for web pages, with examined the element then Network ...

If you have the procedure, I am the taker. I can also make you an Anydesk whenever you want so that you find the problem live.

Everyone around me, with macbooks from different years, has this problem.

I have about 300 passwords in my bitwarden @cscharf

**Comment by alexyangjie** [comment] 2021-04-18 09:36
Have the exact same issue on my M1 mac mini. The extension is so slow on Safari that I have to switch to use Firefox. It all started when Bitwarden switched to use web extension. The fact that it still runs in Rosetta 2 after 5 months of M1 macs production release also adds to the sluggish performance.

**Comment by eliykat** [comment] 2021-04-19 04:09
@cscharf I agree that this seems different to the performance issues I've been looking at - 300 items shouldn't break a sweat. I had seen this bug report but I assumed it was related to the Web Extension upgrade, so maybe @Hinton would have some insight here?

**Comment by alexyangjie** [comment] 2021-04-19 04:38
> Hi @hexicans , thanks for the report, however we've not been able to reproduce this issue per-se. I know @eliykat was looking at several performance issues, but not with Safari specifically (rather very large vaults).
> 
> Can you perhaps trace through the timing using your browser's dev tools to get a gauge on which aspect of the load/open routine is taking the longest?
> 
> I know we will be releasing a universal build for M1 native here shortly, however until then we're also relying on Rosetta2 which is pretty cumbersome for our macOS app and may impact Safari in this context as well. We've found other issues with Safari's new Web Extensions which we're patiently waiting on the latest Safari tech preview fixes to drop to the main release to resolve.
> 
> Any additional information you can provide on tracing, dev tools breakdowns, etc. I believe would really help determine if this is the decryption, context loading, rendering, asset loading, etc. or underlying internals (Safari) that's causing the issue(s).

I have recorded a Safari timeline for your reference. See if it helps. 

[https://send.bitwarden.com/#AXl05yAfqUafo60PAEtFug/zDg99GtxnWJpRXtVXEZ-nw](https://send.bitwarden.com/#AXl05yAfqUafo60PAEtFug/zDg99GtxnWJpRXtVXEZ-nw)

**Comment by cscharf** [comment] 2021-04-19 18:28
@alexyangjie , on that timeline, it looks like there was some interaction recorded, it's hard to tell when the initial open pop-up event occurred, but it looks like it completed at ~1.6s.... So if I'm evaluating this correctly, it would appear:

1. Over 1.2 seconds just for Safari to initiate/paint the web extension popup
2. ~200ms load time to fetch index.html
3. Near instant loading of other assets and stylesheets (webpack) (cached)
4. After 1.6 seconds mostly painted/rendered

This leaves ~1.2s of who-knows-what-Safari-is-doing time, and around 0.4s (~400ms) of loading time to optimize or play with which doesn't seem like there's a whole lot we can do there; even GC is taking ~5ms or less. If I'm understanding the sequence wrong, or this entire sequence is purely just to initially render the pop-up, please let me know?

I have an Intel MacBook Pro, and the extension loads for me near-instantaneously in Safari; I'm not sure if that's due to my hardware, but I'm running BigSur 11.2.3 with 6-core i9, 32GB RAM and a 4GB Radeon Pro; so that may have some measurable impact where we're not able to reproduce the performance issues. But I see the Safari recorded timeline and it definitely appears to take around 2 seconds to load/render, which is what this issue is describing; and appears to be predominantly CPU and paint bound (vs. I/O or memory-bound).

@Hinton or @eliykat , do you gents have any ideas or thoughts?

**Comment by shasycouk** [comment] 2021-04-19 18:54
I highly doubt this is a hardware problem. This has not occurred up until a few weeks back, also not on M1 Airs/Pros. Thanks a lot for looking into this!

**Comment by Tinrobotguy** [comment] 2021-04-19 19:20
The load problem is across different Macs, not just M1. Here is a video to show it taking about 5 seconds to load on my 2013 iMac with 32gb ram and SD drive. It's an older Mac, but no slouch and it is running Catalina.  Same thing on my new M1 MacBook Air.  Loads in 1 second, if that, in Chrome.

https://user-images.githubusercontent.com/33265927/115291419-97e3d300-a109-11eb-8aa0-d04c8932406a.mov

**Comment by edoniti** [comment] 2021-04-19 19:31
Same problem here as well, using Safari 14.0.3 on MacBook Air M1 (16 GB RAM) with macOS 11.2.3, it is really annoying a 2 seconds delay each time you try to open the Bitwarden popup.

**Comment by cscharf** [comment] 2021-04-19 19:37
Oscar was able to find this (and I piled this issue on there as well): https://developer.apple.com/forums/thread/669033, he's continuing to look into this as apparently he is able to recreate it on his machine, but we're not sure there's much we can do from our end.

**Comment by hexicans** [comment] 2021-04-19 19:38
@cscharf  If needed, i'have available for an any desk. Contact me axel at Dyjix dot eu

**Comment by Tinrobotguy** [comment] 2021-04-19 19:45
Sorry for sounding dumb, but can I'm unclear about this. Is the idea that it cannot be replicated, so it will not be fixed, or it will be fixed?  "but we're not sure there's much we can do from our end." sounds like it will not be fixed.

**Comment by Tinrobotguy** [comment] 2021-04-19 20:10
Thanks for explaining. I can imagine this is very frustrating for you.

**Comment by cscharf** [comment] 2021-04-19 20:20
> On the other hand, I would like to point out that I had the problem just after updating the bitwarden update. I had not updated my mac and safari.

Yes, that's expected because the update before Send was released, we had migrated to Web Extensions from App Extensions and this slowness had not appeared during any of our testing. The issue appears to be directly related to Safari's implementation of Web Extensions.

**Comment by cloudslash7** [comment] 2021-04-19 22:06
The problem persists on the latest Safari Technology Preview as well, unfortunately (Release 123). On browser startup, the first click has no delay, but subsequent clicks have that 3-4 second delay. The memory usage also steadily climbs when opening and closing the extension, and after roughly thirty seconds of doing so I got to usage of around half a gigabyte. Guess we'll have to wait until Uncle Apple fixes their implementation of Web Extensions!

https://user-images.githubusercontent.com/62630455/115308940-cb822580-a128-11eb-93f4-64864689d019.mov

<img width="672" alt="Screen Shot 2021-04-19 at 4 01 17 PM" src="https://user-images.githubusercontent.com/62630455/115308943-ccb35280-a128-11eb-97a9-d690a34262fb.png">

**Comment by alexyangjie** [comment] 2021-04-21 23:57
If there is no workaround and the issue is outside of the scope of this product, can we temporarily bring back the old app extension approach until the issue with the Safari platform is fixed? This new web extension is really really affect user experience and the whole browsing experience. It is virtually unusable on the Safari right now. The old approach at least works without major issues, and we can always switch back to the web extension whenever the Safari has fixed it.

**Comment by hexicans** [comment] 2021-04-22 05:34
Yes, please.

**Comment by vquelque** [comment] 2021-04-22 15:33
On my side, in addition to all previously stated issues, Bitwarden is making my Safari crash very often. I get the message "this webpage is using too much memory" and safari crashes. If i disable the Bitwarden extension, then no more crashes. I only noticed this issue recently. It wasn't the case with previous versions of Safari/Bitwarden extension. I love Bitwarden but this makes it a pain to use. Hope there will be a fix soon.

**Comment by Tinrobotguy** [comment] 2021-04-24 01:45
I just got my notice to renew my subscription to 1Password. My plan was to drop 1Password and go with BitWarden, but I'm afraid I have to say that there are too many fundamental issues with Bitwarden to allow me to move over. Not bells and whistles, but fundamentals, like automatically offering to save a password, the load time every time I unlock the extension, no popup offering to update a password when I change it and of course, crashing.  

I will check in again later and maybe move over in a year if these problems are addressed, but for now, sorry to say I have to move on.  Thanks to all for the dialogue here.

**Comment by hexicans** [comment] 2021-05-16 20:32
Hello
any chance to get news or we will have error in lifetime ?

**Comment by cscharf** [comment] 2021-05-17 19:30
> If there is no workaround and the issue is outside of the scope of this product, can we temporarily bring back the old app extension approach until the issue with the Safari platform is fixed? 

The legacy extension is available if you install [Bitwarden Desktop v1.24.7](https://github.com/bitwarden/desktop/releases/tag/v1.24.7), but that is an unsupported version that has stopped getting updates/fixes/new functionality.

>Hello
>any chance to get news or we will have error in lifetime ?

Our DevOps team is working through several topics, and one of those is a native macOS M1 build (which has us playing some waiting games for electron and electron-updater) and our hopes will be better performance of the packaged extension there... however at the moment most of the issue seems to be Safari itself, which we don't have control over. At this time we don't have any updates and have not gotten any responses from Apple on our open issues with them regarding this problem. I wish I had a better update 🙁

**Comment by hexicans** [comment] 2021-05-17 19:43
Hi @cscharf 

Thanks, worked perfectly for ME !! YESSSSS !!!!!!! 😇😇😇😇😇🚀💪

Also, I have no more bug linked to Send function (design bug in Desktop app)

**Comment by hexicans** [comment] 2021-05-17 19:46
https://user-images.githubusercontent.com/13521851/118547144-4014a800-b759-11eb-8ee5-467cc33a5b60.mov
😍😍😍😍

**Comment by renzodamgo** [comment] 2021-05-31 21:02
It appears to be solved with the latest Safari Technology Preview. 🚀
I'm using the Bitwarden Extension from the App Store.
## Using Bitwarden with Safari Technology Preview ⚡️
![safari fast](https://user-images.githubusercontent.com/23220342/120241720-021f8580-c229-11eb-95dc-06a16d48db22.gif)
## Using Bitwarden with the latest Safari version 🐢
![safarislowk](https://user-images.githubusercontent.com/23220342/120241993-840fae80-c229-11eb-9aea-b009afa30f0d.gif)

I guess this one was on the Apple side.  👀

**Comment by ncodee** [comment] 2021-06-03 19:06
It's not just Safari, Bitwarden has severe performance issues throughout all their browser extensions, including their Android app which keeps crashing, and stops auto filling. As for the web vault, it takes 10 seconds to edit/delete a single entry. I think Bitwarden needs a complete rewrite, as this has been going on for years. and still hasn't been addressed.

**Comment by mariodian** [comment] 2021-07-05 09:15
The extension is slow on Safari 14.1.1 (I only have under 300 passwords saved), but works just fine on Safari Technology Preview (release 127). 

MBP 15" 2018, Mac OS 11.4

**Comment by piejanssens** [comment] 2021-09-20 19:47
Safari 15.0 got released to the public (Big Sur + Catalina) and this solves it for me.

**Comment by Hinton** [comment] 2021-09-21 08:02
This seems to be resolved on my machine using Safari 15.0. Going to close this issue for now but if anyone still encounters it feel free to re-open it.

Unfortunately there doesn't seem to be anything we can do on our end to solve it for previous Safari versions.

**Closed by Hinton** 2021-09-21 08:02 UTC

**Comment by jtmkrueger** [comment] 2021-09-21 20:17
I've noticed a _drastic_ speed increase with regards to open time in safari 15.
