### ISSUE TITLE
Unable to export vault on Vivaldi extension

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/browser#1885] opened 2021-06-07 07:21 UTC
## Steps:

1. Export your vault from Vivaldi extension

## Expected Result

Being asked where to save the file

## Actual Result

Nothing happened. Extension is back to Settings page.

When you pop out the extension, it works.
 
## Environment

- Operating system: Win 10
- Browser: Vivaldi 3.8.2259.37 
- Build Version (go to "Settings" → "About" in the app): 1.50.0

**Comment by Greenderella** [comment] 2021-06-07 09:42
Yes, this bug has been reported to the Vivaldi team in 2019, but it appears to still be present nowadays.

You have to first open up the extension in a new window by clicking the "Pop out" icon on the top left. After opening in a new window the export works as expected and the browser prompts to store the file.

![image](https://user-images.githubusercontent.com/5418577/120994896-3b09ae00-c785-11eb-9637-0948d11e9a58.png)

Please make sure no extension it's blocking the pop window:

![image](https://user-images.githubusercontent.com/5418577/120994962-46f57000-c785-11eb-956d-929558f6949f.png)

Let us know if there is anything else we can do for you.

**Comment by eliykat** [comment] 2021-06-08 00:12
Closing as a duplicate of #966. Thanks @Greenderella for the workaround!

**Closed by eliykat** 2021-06-08 00:12 UTC

**Comment by luckydonald** [comment] 2024-01-05 01:20
_Just_ blaming Vivaldi is not an ideal solution.
Currently the user experience is: Nothing happens.

I think the minimum would be to have a check for vivaldi which then shows a text telling one to do the stuff displayed above.

A second way would be to offer a copy-to-clipboard button. That would work from there as well, and in the end the important part is being able to get the data somehow.
