### ISSUE TITLE
Auto-Fill completes with first item in list instead of last used

### ISSUE THREAD

**Issue by clayadams5226** [bitwarden/browser#1420] opened 2020-10-06 03:59 UTC
## Describe the Bug

If a user has multiple logins for the same URI the browser should select the last one used. After the last update it started using the first one in alphabetical order.

## Steps To Reproduce

1. Go to a website where you have multiple login credentials saved (such as Google)
2. Log into the website using the 2nd item alphabetically from the list.
3. Log out and log back in using Ctrl +shift + 'L' shortcut

## Expected Result

The user is logged in with the second item from your list.

## Actual Result

User is logged in with the first item from your list.

## Environment

- Operating system: Tested on Chrome, Edge, and Firefox
- Browser: [e.g. Firefox 73.0.1]
- Build Version 1.46.2

**Comment by temesinko** [comment] 2020-10-06 08:14
Seems to be related to [this comment](https://github.com/bitwarden/browser/issues/1392#issuecomment-694402888).

**Comment by alangrainger** [comment] 2020-10-06 23:02
This also happens on a browser close, as well as as log out and back in.

**Comment by MGibson1** [comment] 2020-11-17 21:52
@clayadams5226 I can't reproduce this. Can you please confirm it's still happening?

Also, for reproduction step 3, can you please confirm you're referring to loging in/out of the website (Google in your example)?

Have you tried this for other websites or is Google the only offender for some reason?

**Comment by clayadams5226** [comment] 2020-11-18 07:05
@MGibson1 this looks to be resolved with the latest 1.47.0 release.

**Comment by MGibson1** [comment] 2020-11-18 12:49
That's great! In that case I'm going to close this issue.

**Closed by MGibson1** 2020-11-18 12:49 UTC

**Comment by alangrainger** [comment] 2020-11-23 09:50
Appears to be resolved - many thanks!
