### ISSUE TITLE
Extension Locks even if other settings selected

### ISSUE THREAD

**Issue by StevenLi-DS** [bitwarden/browser#1623] opened 2021-02-20 15:26 UTC
## Describe the Bug

The extension locks me out if I closed all my Chrome tabs and asks me to type Master Password regardless my settings. 
## Steps To Reproduce

1. Go to 'Settings'
2. Under 'Vault Timeout', select 'On System Lock'
3. Under 'Vault Timeout Action', select  'Lock'
4. Check 'Unlock with PIN'

## Expected Result

The extension will lock me out *only* when I lock my computer (Wins + L) and will let me use my PIN to unlock

## Actual Result

If I lock my computer, the extension behaves as expected. However, if I close all my tabs and restart Chrome, It will also lock me out and ask me for the Master Password to unlock not PIN.

## Environment

- Operating system: Windows 10
- Browser: Chrome
- Build Version: 88.0.4324.182 (Official Build) (64-bit)

**Comment by Greenderella** [comment] 2021-02-20 18:21
Hi there,

This is the expected behaviour. Once you restart your browser, regardless of your Vault Timeout Action, you would need to unlock your vault. More on this here: https://bitwarden.com/help/article/vault-timeout/

I hope this clarifies everything up for you. Please let me know if you have any further questions.

**Comment by StevenLi-DS** [comment] 2021-02-20 21:21
Hi @Greenderella 

Thanks for the clarification, but I didn't find the so-called 'Lock with master password' checkbox.

> If you’re using a Browser Extension, you can bypass this by enabling the Unlock with PIN option and unchecking the Lock with master password on browser restart checkbox.

Am I missing something?

**Comment by 12people** [comment] 2021-06-08 23:17
@Greenderella If I'm understanding the OP correctly, that's not the problem here. It's absolutely normal to get locked out on browser restart. However, when a PIN is set, it should be possible to unlock using the PIN rather than the master password.

That's how the extension used to work until relatively recently.

Just came here to report the same issue, except for me it seems to have started around the time I upgraded to Firefox 89.0 (on macOS Big Sur). (Not sure if it was with the upgrade or just around the same time. I initially thought I was just logged out automatically for some reason.)

**Comment by Greenderella** [comment] 2021-06-10 07:58
This is the checkbox I'm referring:
![image](https://user-images.githubusercontent.com/5418577/121487485-6af9c100-c9d2-11eb-8959-53a5b648b202.png)

**Comment by djsmith85** [comment] 2021-12-17 18:21
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2021-12-17 18:21 UTC
