### ISSUE TITLE
Firefox extension ask for password saving even if not logged in

### ISSUE THREAD

**Issue by iadegesso** [bitwarden/browser#2287] opened 2022-01-23 13:38 UTC
### Steps To Reproduce

1. Open Firefox
2. Avoid do log in Bitwarden extension
3. Log in to a website...
4. You will been asket to save the password in Bitwarden even if it's not logged in...

### Expected Result

Bitwarden should ask for saving passwords if and only if the user already performed login to Bitwarden with his master password.

### Actual Result

Bitwarden asks for saving passwords even if the user already performed login to Bitwarden with his master password.

### Operating System

Linux

### Operating System Version

Gentoo, kernel 5.15, GONME 41 (on X11),

### Web Browser

Firefox

### Browser Version

95.0.1

### Build Version

1.55.0

**Comment by Hinton** [comment] 2022-01-24 10:03
Closed as a duplicate of https://github.com/bitwarden/browser/issues/2242

**Closed by Hinton** 2022-01-24 10:03 UTC
Labels: bug
