### ISSUE TITLE
Vault is empty in Firefox extension

### ISSUE THREAD

**Issue by sarod** [bitwarden/browser#1544] opened 2021-01-21 16:34 UTC
## Describe the Bug

Bitwarden for FF was working fine for months. 
But when I opened firefox a week ago bitwarden extension was logged out.
I logged back in but now my vault appears empty in firefox.

Thankfully the logins & other vault data is still here when I go to vault.bitwarden.com or when using the chrome extension with the same login.

## Steps To Reproduce

1. login
2. Click on 'My Vault'

## Expected Result

It should display my logins and other items

## Actual Result

It displays "There are no items to list".
When starting the debugging tool (https://extensionworkshop.com/documentation/develop/debugging/)
The console logs many many errors like this:
```
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. 2 ExtensionStorageIDB.jsm:831
    normalizeStorageError ExtensionStorageIDB.jsm:831
    method ext-storage.js:273
    AsyncFunctionThrow self-hosted:678
    enter event-loop.js:79
    enter self-hosted:1161
    _pushThreadPause thread.js:310
    _pauseAndRespond thread.js:923
    hit breakpoint.js:204
    get browserStorage.service.ts:26
    apply self-hosted:2644
    applySafeWithoutClone ExtensionCommon.jsm:616
    wrapPromise ExtensionCommon.jsm:845
    withLastError ExtensionCommon.jsm:764
    wrapPromise ExtensionCommon.jsm:833
````
And this
```
Unchecked lastError value: Error: An unexpected error occurred 2 background.js:22667
    get browserStorage.service.ts:25
```

## Environment
- Operating system:  Windows 10
- Browser: Firefox 84.0.2
- Build Version: 1.47.1

## Additional Context
I tried reinstalling the extension without any benefit.

**Comment by sarod** [comment] 2021-01-21 22:13
The issue seems to be on firefox or windows side.
My firefox profile local storage was corrupted.
The origin of the corruption was a file with an "invalid" name that I could not delete or move inside one of the folders inside AppData/Roaming/Firefox/Profiles/xxx.default/storage/default.
To fix this I:
* copied my whole profile to a new folder except the corrupted file
* changed the profile in AppData/Roaming/Firefox/profiles.ini to point to the new folder

And everything now works as expected...

**Comment by clayadams5226** [comment] 2021-01-22 04:20
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by clayadams5226** 2021-01-22 04:20 UTC
