### ISSUE TITLE
Issue #136 is not solved (extension still doesn't load in Firefox private mode)

### ISSUE THREAD

**Issue by citydelver** [bitwarden/browser#1444] opened 2020-11-01 15:33 UTC
## Describe the Bug

Issue #136 is not solved. The Bitwarden extension still doesn't load in Firefox private mode, while many other extensions do perfectly fine, including all other password managers that I am aware of.

## Steps To Reproduce

1. Open a private window in Firefox.
2. Click the extension.

## Expected Result

The extension should work as usual.

## Actual Result

The pop-up is blank, with a warning and this link: https://bitwarden.com/help/article/extension-wont-load-in-private-mode/

## Additional Context

Since extensions of any type work just fine in Firefox private windows, including other password managers, we can discard the hypothesis that the issue is caused by Firefox. If it was, all other extensions would be facing the same issue. That's not the case, so **Bitwarden _can_ do something that others have done in order to achieve the same result**.

This is not say that we do not value the team's work and efforts. We do.

**Comment by devurandom** [comment] 2020-12-02 08:35
This seems to be a duplicate of #911 and #1050.

**Comment by cscharf** [comment] 2020-12-28 21:00
This is a duplicate of #136

**Closed by cscharf** 2020-12-28 21:00 UTC
Labels: duplicate
