### ISSUE TITLE
Safari extension can not be installed, as Bitwarden from the App Store does not open

### ISSUE THREAD

**Issue by jslawler** [bitwarden/browser#1753] opened 2021-04-01 02:45 UTC
Unable to launch Bitwarden after installing from macOS App Store. Safari extension does not work either, as this is an extension to Bitwarden on the App Store.
[Bitwarden.com states that Bitwarden will work on macOS X Yosemite and later, which it does not.](https://bitwarden.com/download/)

See attached for app crash logs.

macOS High Sierra Version 10.13.6 (17G14033)
App Store Version 2.4 (658.2)
Bitwarden Version 1.25.1

[Archive.zip](https://github.com/bitwarden/desktop/files/6240576/Archive.zip)

_Originally posted by @jslawler in https://github.com/bitwarden/desktop/issues/675#issuecomment-811595087_

**Comment by cho-m** [comment] 2021-04-03 18:10
One thing to note is that latest Bitwarden 1.25.1 (i.e. version on App Store) will only work with Safari 14 as mentioned here: https://bitwarden.com/help/article/install-safari-app-extension/

macOS High Sierra can only run Safari 13, so you may want to try older DMG: https://github.com/bitwarden/desktop/releases/tag/v1.24.7

**Comment by cscharf** [comment] 2021-04-07 18:37
Hi @jslawler , please use v1.24.7. Also, closing as a duplicate of https://github.com/bitwarden/desktop/issues/675

**Closed by cscharf** 2021-04-07 18:37 UTC
Labels: duplicate
