### ISSUE TITLE
Bitwarden freezes WordPress admin page

### ISSUE THREAD

**Issue by ivandotv** [bitwarden/browser#274] opened 2017-10-03 13:16 UTC
This happens on "Appearance"->"Menus" (admin page where front end menus are created)
I'm guessing this is because there are a lot of `input` fields on that page.
Tested in latest stable Google Chrome - Linux

**Comment by kspearrin** [comment] 2017-10-03 13:55
How many inputs are on the page?

**Comment by ivandotv** [comment] 2017-10-03 18:30
Over 100

**Comment by kspearrin** [comment] 2017-10-03 18:31
Is there a demo admin panel I can use to see what’s going on?

**Comment by ivandotv** [comment] 2017-10-03 18:37
There are some online demos of WordPress admin maybe try find those,  and check out "Appearance"->"Menus"
Basically every menu item has options in the backend, and there are four options for every item, plugins and themes could add their own options so in can be even more.

**Comment by kspearrin** [comment] 2017-10-03 18:43
Here's what I see.

![image](https://user-images.githubusercontent.com/1190944/31142724-1f0bcc24-a849-11e7-833d-1ba1b9a087c5.png)

Not very many inputs on this page.

https://demos1.softaculous.com/WordPress/

**Comment by ivandotv** [comment] 2017-10-03 18:45
Because there are no menus on that page.
You need to create menus.
Go to "create new menu" and then start adding menu items.

**Comment by kspearrin** [comment] 2017-10-03 18:48
I created 3 menus. Looks like you only select one at a time from the dropdown next to "create new menu" ...?

**Comment by ivandotv** [comment] 2017-10-03 18:52
Yeah, WordPress menu logic can be confusing sometimes.
This is how you create menus
https://www.youtube.com/watch?v=g_3H2tJRPpM

**Comment by ivandotv** [comment] 2017-10-03 18:58
When on menu pages, try running `jQuery('input[type=text]').length` in console.

**Comment by kspearrin** [comment] 2017-10-03 19:01
I only get 4. Feel free to log into this demo admin and set it up in a way that causes the issue:

https://demos1.softaculous.com/WordPress/wp-admin/

admin/pass

**Comment by ivandotv** [comment] 2017-10-03 19:04
I have added 5 menu items , there are 28 input fields of type text

**Comment by kspearrin** [comment] 2017-10-03 19:11
I created a menu with like 25 items which results in over 100 inputs. I'm not noticing a slowdown or freeze. Are you? https://demos1.softaculous.com/WordPress/wp-admin/nav-menus.php

**Comment by ivandotv** [comment] 2017-10-03 19:15
No, but like I said those are the default menu options. Plugins and themes can add their own options (inputs) and that adds up quickly.
What I have forgot to say about the original post is that the freeze effect lasts for a few seconds, and then everything works.
Machine: 
6GB Ram
Quad Core CPU
Ubuntu 16.04

**Comment by kspearrin** [comment] 2017-10-03 19:16
I am only seeing 5ms of processing time from bitwarden's autofill.js content script:

![image](https://user-images.githubusercontent.com/1190944/31144150-cbcc259a-a84d-11e7-9e18-b1666c68e0bb.png)

Can you see what yours is showing with a profile session?

**Comment by ivandotv** [comment] 2017-10-03 19:25
![image](https://user-images.githubusercontent.com/390700/31144514-4a0e0184-a881-11e7-902f-b8ad93d2eeb0.png)

**Comment by ivandotv** [comment] 2017-10-03 19:28
`extensions::messaging` is the bottleneck
When I disable bitwarden page doesn't freeze

**Comment by kspearrin** [comment] 2017-10-03 19:34
Not really sure what that is at the moment. Will need to investigate more.

**Comment by kspearrin** [comment] 2017-10-03 19:56
Is there any way you can create a reproducible example that I can access? Or else this is going to be next to impossible to debug.

**Comment by ivandotv** [comment] 2017-10-03 19:57
Not right now, let's but this on hold for now.

**Comment by kspearrin** [comment] 2017-10-05 01:50
v1.18.0 just landed with some possible fixes. Give it a try.

**Comment by kspearrin** [comment] 2017-10-11 16:37
I added another possible fix in v1.19.0. Please update and try.

**Closed** 2017-12-05 18:32 UTC
