### ISSUE TITLE
Frequent console error output in firefox

### ISSUE THREAD

**Issue by aminomancer** [bitwarden/browser#1507] opened 2020-12-23 04:24 UTC
- Windows 10
- Firefox 86.0a1 (but I've been noticing this since like 72)
- Build 1.47.1

I keep getting this error alert in the browser toolbox:
`Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.`
from background.js:1738

I don't think something is seriously wrong or anything, I just wanted to suggest adding some kind of log-free handling so the javascript console doesn't get so cluttered. I'm often trying to debug other stuff and don't want to hide error logs, but then this constant alert pushes up the stuff I'm trying to read. There are plenty of other try catch statements in that same script. If the alerts are important somehow, maybe you could add a setting to the popup and make the content of the catch statement some variable that's modulated by the setting. Thanks😊

**Comment by grantwest** [comment] 2020-12-23 17:44
I have noticed the same issue. This is how it shows up in the Browser Console:
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/4594800/103023671-66bd1280-451c-11eb-9ca0-f88a45a1c064.png">
It is a distraction when debugging other issues because it is hard to tell what is happening. It takes a while to figure out that this is Bitwarden and that it isn't a problem.

**Comment by eliykat** [comment] 2021-11-24 01:30
Closing as a duplicate of #1208. Please refer to that Issue for any updates or further discussion.

**Closed by eliykat** 2021-11-24 01:30 UTC

**Comment by aminomancer** [comment] 2021-11-24 10:55
Thanks, didn't realize I posted this twice. whoops.
