### ISSUE TITLE
Unchecked lastError value: Why don't you fix this problem???

### ISSUE THREAD

**Issue by qinxs** [bitwarden/browser#2182] opened 2021-11-16 09:38 UTC
### Steps To Reproduce

1. Go to 'about:debugging#/runtime/this-firefox'
2. Scroll down to 'Bitwarden ...'
3. Click on 'inspect'
4. Switch to the console panel

### Expected Result

A clean console

### Actual Result

A lot of error prompts from Bitwarden

### Screenshots or Videos

![Unchecked lastError value](https://user-images.githubusercontent.com/13647698/141959775-f8af8ba2-972a-431d-8b37-de9c9f18e705.png)

![2](https://user-images.githubusercontent.com/13647698/141959794-8b28cdfa-d597-412b-9111-20616d0a6041.png)

### Additional Context

browser firefox！！！
> Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.

For this question, users have already mentioned more than ten Issue. 
#1791, #1536, #1208...
[ related issues ](/bitwarden/browser/search?q=Unchecked+lastError+value&type=issues)

On `Stackoverflow`, there are also solutions.
[ how-to-fix-unchecked-runtime-lasterror-could-not-establish-connection ](https://stackoverflow.com/a/69587523/5865973)

### Operating System

Windows

### Web Browser

Firefox

### Build Version

78.15.0esr (x64)

**Comment by eliykat** [comment] 2021-11-24 01:38
Please do not create duplicate issues. I'm closing this as a duplicate of #1208, and I've also consolidated the other reports you linked into that issue. Please refer to that Issue for any updates or further discussion.

I understand that this bug is annoying, however we only have so much time in our days, and we have to prioritise what bugs we fix first and how we balance those with other priorities. That said, this error does get in the way of debugging other issues, and it does have a number of duplicate reports, so I'd like to see it fixed and I've made an internal note that it needs some attention.

**Closed by eliykat** 2021-11-24 01:38 UTC
Labels: bug
