### ISSUE TITLE
The Verification Code (TOTP) 'Copy' button is not working

### ISSUE THREAD

**Issue by pssm** [bitwarden/browser#596] opened 2018-04-19 06:44 UTC
The latest extension update (Version: 1.26.0), rendered the 'Copy' TOTP code button useless. 

Tested in Firefox 60.0b10 / macOS 10.12.6

**Comment by jonleighton** [comment] 2018-04-19 10:14
I cannot use the "copy username" or "copy password" buttons with the latest update. I suspect it is the same issue as this. (Also [continuing to have trouble with autofill](https://github.com/bitwarden/browser/issues/576) so it's pretty hard to get at my passwords at all.)

**Comment by ChexWarrior** [comment] 2018-04-19 11:49
I also cannot seem to copy my passwords anymore using Firefox Developer Edition with Ubuntu 16.04.

**Comment by kspearrin** [comment] 2018-04-19 11:50
Seems to be a non-windows issue. I can reproduce it on macOS

**Comment by kspearrin** [comment] 2018-04-19 12:24
Fixed in next version that will go out today.

**Closed by kspearrin** 2018-04-19 12:24 UTC

**Comment by kspearrin** [comment] 2018-04-19 13:47
1.26.1 is now live on Firefox
