### ISSUE TITLE
Prompted to save information when locked, even if information is saved

### ISSUE THREAD

**Issue by WillFP** [bitwarden/browser#2313] opened 2022-02-04 14:16 UTC
### Steps To Reproduce

1. Have bitwarden vault be locked on a browser (eg chrome)
2. Log into a website
3. Bitwarden will prompt to save credentials, even though the credentials are already saved

### Expected Result

This may actually be intended behaviour, and obviously bitwarden can't check what websites you have accounts for while locked, but ideally it shouldn't prompt to save while locked.

### Actual Result

Prompted to save while locked, it might be an idea to add an opt-in ability to save the domains that you have credentials saved for, and then not prompt for those while locked

### Operating System

Windows, macOS

### Operating System Version

macOS Monterey, Windows 11

### Web Browser

Brave

### Build Version

1.55.0

**Comment by djsmith85** [comment] 2022-02-04 14:28
Closed as a duplicate of https://github.com/bitwarden/browser/issues/2242

**Closed by djsmith85** 2022-02-04 14:28 UTC
Labels: bug
