### ISSUE TITLE
 Biometrics not working on Firefox 88.0.1 (64-bit) on Windows 10 

### ISSUE THREAD

**Issue by beeriz** [bitwarden/browser#1824] opened 2021-05-08 15:04 UTC
## Describe the Bug
 Biometrics not working on Firefox 88.0.1 (64-bit) on Windows 10 . 
When clicking on login with biometrics on Firefox, the plugins keeps waiting (loader).

## Steps To Reproduce
Install bitwarden Dekstop
Install the bitwarden extension on Firefox
Setup with windows hello
Enable browser integration on destop version
Try to login using biometrics on Firefox

## Expected Result
Login directly without requesting PIN code.

## Actual Result
Infinite loading time waiting for a reply from Dekstop app.

## Environment

- Operating system: Widows 10
- Browser: Firefox 88.0.1 (64-bit)
- Build Version : 1.49.1

## Additional Context
The same integration works without issue using Chrome. Every time it connect instantly. But with firefox, it worked once and then stopped.

**Comment by SergeantConfused** [comment] 2021-05-09 10:57
Hi there,

I just tested this using Firefox 88.0.1, Windows 10 20H2, Bitwarden extension 1.49.1, and Bitwarden desktop 1.25.1, and I was able to successfully unlock my Bitwarden extension inside Firefox using my fingerprint through Windows Hello.
Please uninstall all your Bitwarden clients, clear all leftover data from these locations: https://bitwarden.com/help/article/data-storage/ and then reboot and reinstall them, and let me know if that changes anything.

I thank you in advance for your understanding and cooperation,

**Comment by kendratodd** [comment] 2021-06-08 21:49
Hi @beeriz, it looks like there is a viable workaround or resolution for the issue you're experiencing. Please let us know if this resolves the originally posted issue.

**Comment by kendratodd** [comment] 2021-06-23 19:04
For now, I'm going to close this issue, as it appears the originally posted problem has a viable resolution/workaround. If this happens again or continues to be an issue @beeriz, please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis. Thank you!

**Closed by kendratodd** 2021-06-23 19:04 UTC
