### ISSUE TITLE
After the update the extension doesn't detect premium membership

### ISSUE THREAD

**Issue by extesy** [bitwarden/browser#2344] opened 2022-02-11 06:15 UTC
### Steps To Reproduce

1. Click on the extension icon.
2. Choose Premium Membership from settings.
3. Observe that the membership is inactive.

### Expected Result

Active premium membership account is detected.

### Actual Result

Active premium membership account is NOT detected.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/65872/153545340-6b7e530b-f686-41b1-8542-bdf7e6c29c75.png)

### Additional Context

An attempt to refresh the membership doesn't change anything. It says "membership refreshed" but keeps it inactive.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

97

### Build Version

1.56.0

**Comment by DesignatedJM02** [comment] 2022-02-11 06:49
Solution: Log out and log back in. That will fix the issue of the extension not detecting you being Premium.

**Comment by cscharf** [comment] 2022-02-11 07:17
Thank you for the report @extesy , this is a duplicate of https://github.com/bitwarden/browser/issues/2335 and we do anticipate a fix here shortly.

**Closed by cscharf** 2022-02-11 07:17 UTC
Labels: bug
