### ISSUE TITLE
Failed to install addon on Firefox Mobile (Android)

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/browser#1575] opened 2021-01-27 00:42 UTC
## Describe the Bug

"Failed to install Bitwarden - Free Password Manager" when tried to install on Firefox Mobile

## Steps To Reproduce

Install Bitwarden addons on Firefox Mobile on Android

## Expected Result

Bitwarden installed without issue.

## Actual Result

Error message "Failed to install Bitwarden - Free Password Manager"

## Environment

- Device is a Google Pixel 3
- Android 11
- Browser:  Firefox 84.1.4
- Build Version 1.48.0

**Comment by forumer** [comment] 2021-01-28 15:55
I was able to consistently reproduce this install failure even with a clean install (device app storage cleared, uninstall app, reinstall app from Google Play Store) of Firefox Daylight (Android) version 84.1.4 and the Bitwarden add-on (browser extension) version 1.48.0, dated Jan 22, 2021, from the Mozilla add-on store. However, with the appearance of version 1.48.1, dated Jan 26, 2021, it now installs properly on the same setup.

I do not know if there is another bug report to link to where this issue was explicitly addressed in a code change for 1.48.1. If there is it should be noted here so this bug can be marked as a duplicate or some other such accounting for reference purposes.

**Comment by douglasparker** [comment] 2021-01-30 18:26
I was having this issue too, but updating to Firefox v85.1.1 seems to have fixed it.

Try and update Firefox and let us know if it's still an issue for you.

**Comment by forumer** [comment] 2021-01-30 18:47
> I was having this issue too, but updating to Firefox v85.1.1 seems to have fixed it.
> 
> Try and update Firefox and let us know if it's still an issue for you.
> 
> EDIT: Either the new version of Firefox fixed it for me, or an updated version of the extension. I'm not entirely sure.

Per my previous message, it was only the updated BW extension (going from 1.48.0 to 1.48.1 from the Mozilla add-on store) that changed in my setup and caused the issue to be resolved. **All other versions (OS, browser) remained the same**.

**Comment by djsmith85** [comment] 2022-03-10 22:06
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2022-03-10 22:06 UTC
