### ISSUE TITLE
Import password lists creates duplicate folders

### ISSUE THREAD

**Issue by ni-ka** [bitwarden/browser#1181] opened 2020-03-23 09:53 UTC
Lastpass export generates some errors which must sometimes be fixed and thus requires a trial and error approach, breaking down long lists of accounts in multiple imports.

Currently the import creates new folders for every import, which ends up like below:
![bitwarden-folders](https://user-images.githubusercontent.com/1225776/77304216-04648680-6cec-11ea-8f70-d2a7c0406bdc.png)

I see a similar issue was brought up in #1151 but this is a bug report to prevent the issue from happening in the first place.

Thanks!

**Comment by tgreer-bw** [comment] 2020-03-23 12:12
Hi @ni-ka, 

I can definitely understand the request here, but it is still a 'feature' request and not a bug - the imports work as designed but cause duplicates on re-import. Just to make sure we can keep track of things that are truly broken via issues, please close this issue and raise it in the [community forums](https://community.bitwarden.com/c/feature-requests/5).

Thanks!

**Comment by kspearrin** [comment] 2020-03-23 12:50
This is behaving as intended. If you have issues with your import it is expected that you purge your vault (Under Settings > My Account) and try again.

**Closed by kspearrin** 2020-03-23 12:50 UTC

**Comment by mll0** [comment] 2022-06-08 19:00
> This is behaving as intended.
I don't understand.
If I clear all vault items, I see no mode folders.
And then when I do an import, I see dupe (triple / quadruple...) folders, with only one folder of each name containing data. Is that _really_ intended? I rather consider this a bug, which is appropriate to report here.
