### ISSUE TITLE
npm install fails to download node-sass binary

### ISSUE THREAD

**Issue by glitsj16** [bitwarden/browser#1524] opened 2021-01-07 22:22 UTC
## Describe the Bug

HTTP error 404 Not Found with node-sass 4.13.1

## Steps To Reproduce

$ npm install

## Expected Result

Succesful download of the node-sass binary.

## Actual Result

Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-83_binding.node":
HTTP error 404 Not Found

## Environment

- Operating system: Arch Linux
- Browser: Firefox 84.0.2
- Build Version (go to "Settings" → "About" in the app): 1.47.1

## Additional Context

[package.json](https://github.com/bitwarden/browser/blob/e23d96a35002099b25f8abf87aa97e3f1bbe55f8/package.json#L72) references node-sass version 4.13.1, which indeed is not available on https://github.com/sass/node-sass/releases. Here's a working patch for node-sass 4.14.1:

```
--- a/package.json
+++ b/package.json
@@ -69,7 +69,7 @@
     "karma-jasmine-html-reporter": "^1.4.0",
     "karma-typescript": "^4.0.0",
     "mini-css-extract-plugin": "^0.9.0",
-    "node-sass": "^4.13.1",
+    "node-sass": "^4.14.1",
     "sass-loader": "^7.1.0",
     "style-loader": "^0.23.0",
     "ts-loader": "^8.0.2",
```

**Comment by cscharf** [comment] 2021-01-12 17:32
@glitsj16 , I am unable to reproduce this, and our CI/CD pipelines, dev team, etc. frequently run clean `npm install` w/o issue. Looking at the repo for node-sass I also see [4.13.1](https://github.com/sass/node-sass/releases/tag/v4.13.1) available as expected as well. Is it that version is simply missing a node binding for your local environment?

**Comment by glitsj16** [comment] 2021-01-13 02:15
@cscharf Thanks for your response.

> Looking at the repo for node-sass I also see 4.13.1 available as expected as well.

Apologies for not being specific before. Upstream indeed has node-sass 4.13.1 available. But the latest available linux-x64 binding.node is [79](https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-79_binding.node) while the code requests [83](https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-83_binding.node). The link to linux-x64-83_binding.node is only available under v4.14.1, hence my patch.

To be clear, `npm install` does fall back to requesting a rebuild of node-sass after the 404 (see below) but that step takes extra time that can be avoided by the patch.

OS: Arch Linux - fully updated
```
$ pacman -Q node-gyp nodejs npm semver
node-gyp 7.1.1-1
nodejs 15.5.1-1
npm 6.14.11-1
semver 7.3.4-1
```

```
$ npm install

> node-sass@4.13.1 install /home/glitsj16/bitwarden.browser/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-83_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> ngx-infinite-scroll@7.0.1 postinstall /home/glitsj16/bitwarden.browser/node_modules/ngx-infinite-scroll
> opencollective postinstall


                            Thanks for installing ngx-infinite-scroll
                         Please consider donating to our open collective
                                to help us maintain this package.

                                    Number of contributors: 0
                                       Number of backers: 6
                                      Annual budget: 24 US$
                                     Current balance: 172 US$

               Donate: https://opencollective.com/ngx-infinite-scroll/donate


> node-sass@4.13.1 postinstall /home/glitsj16/bitwarden.browser/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /home/glitsj16/bitwarden.browser/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
[...]
```

> Is it that version is simply missing a node binding for your local environment?

I'm not sure what you mean. Not being familiar with the bitwarden browser code-base I can only guess that it might be caused by a recent upgrade of the Node.js related packages on Arch Linux. I've been succesfully building the extension from git for quite a while and I never stumbled on this specific issue before. Please feel free to close here if this doesn't make sense. I can deal with this locally. Just thought it might be worthwhile to inform the project on it.

**Comment by cscharf** [comment] 2021-01-13 13:33
Ah, thanks for clarifying, I'll add this card to the backlog as we look at package updates later this quarter, OR, please feel free to submit a PR with the patch, from what I see this impacts the following (and related package-lock.json files as well):

* https://github.com/bitwarden/browser/blob/master/package.json#L72
* https://github.com/bitwarden/web/blob/master/package.json#L54
* https://github.com/bitwarden/desktop/blob/master/package.json#L279
* https://github.com/bitwarden/directory-connector/blob/master/package.json#L178

**Comment by glitsj16** [comment] 2021-02-21 08:52
UPDATE:

Something changed. Now the build process from git master is expecting to find `linux-x64-88_binding.node` (instead of linux-x64-83_binding.node) which is [part](https://github.com/sass/node-sass/releases/download/v5.0.0/linux-x64-88_binding.node) of upstream v5.0.0. I've tried adapting the patch (that part works) but I'm reluctant due to v5.0.0 coming with breaking changes (see the [release](https://github.com/sass/node-sass/releases/download/v5.0.0/linux-x64-88_binding.node) page for detailed info). I'll be doing more extensive testing later and will report back here.

**Comment by djsmith85** [comment] 2021-08-07 13:31
Hi @glitsj16 thank you for your detailed report. We recently switched from `node-sass` to `sass`. `node-sass` relied on `node-gyp` which can bring a whole lot of issues with it. `sass` does not have a dependency on it and it now should just work fine. I'm closing the issue, but if you do experience any problems, please feel free to re-open.

**Closed by djsmith85** 2021-08-07 13:31 UTC
