### ISSUE TITLE
[bug] extension's popup is trimmed in FF

### ISSUE THREAD

**Issue by ZuBB** [bitwarden/browser#1270] opened 2020-05-31 18:16 UTC
Recently I started to observe next behaviour: after I click on bitwarden's icon in toolbar I see that extension tries to draw/show popup but only narrow strip (screen attached) is shown/visible below "arrow". my stats says it happens on random sites, so no any "rules" here. I recently switched from GC to FF + bitwarden so I cant tell for sure if this started to appear after some update or it used to be before my switch.

env: macos 10.15.4 + latest firefox (76.0.1) + latest bitwarden (1.44.2)

<img width="209" alt="Screenshot 2020-05-31 at 21 03 21" src="https://user-images.githubusercontent.com/597016/83359597-e8343400-a383-11ea-899c-bebfd3c44e30.png">

**Comment by kspearrin** [comment] 2020-05-31 18:18
Try restarting Firefox. Mine always does this after the extension updates until I restart.

**Comment by ZuBB** [comment] 2020-05-31 18:30
seems it does the trick. at least few tests I made passed successfully.

Although restarting browser after extension has been updated does not look as right solution to this issue. is this something that could be fixed in bitwarden sources or its a firefox thing?

**Comment by kspearrin** [comment] 2020-05-31 18:31
Seems to be a Firefox issue

**Comment by ZuBB** [comment] 2020-05-31 18:39
hey @kspearrin is it just a guess or you have ff's issue number in mind?

I have some doubts on it as I recall that popup is drown trimmed/cropped on every second time starting from 1st. I admit this is not 100% proof that ff does everything right on its side but I am inclined to think that issue comes from bitwarden's sources

**Comment by kspearrin** [comment] 2020-05-31 18:41
It’s just a guess

**Comment by ZuBB** [comment] 2020-05-31 19:12
Any idea how we can check if it is ff's or bitwarden's issue?

**Comment by ronaldscott** [comment] 2020-06-02 22:04
I'm getting this too.
1. open a new tab, wait for load
2. click bitwarden extension
3. see clipping problem
4. click bitwarden extension again
5. bitwarden works fine
6. reload tab
7. goto 2--condition resets

Started within the last week. Wouldn't shock me if it were a FF problem, they seem to be having some QA issues of late.

**Comment by ronaldscott** [comment] 2020-06-03 03:55
@kspearrin 

> Try restarting Firefox. Mine always does this after the extension updates until I restart.

I restarted Firefox and it did indeed stop doing it.

**Comment by 29988122** [comment] 2020-06-03 07:39
I can reproduce this. I can also confirm that revert to old version of Bitwarden solves this issue.

Seems memory related? Cause I can prevent this bug after restarting firefox, but it reappeared after a certain period (say 5 hours).

**Comment by MattTheDev** [comment] 2020-07-08 19:33
@29988122 Thanks so much for the follow up / confirmation of repro. I'm working on reproducing it myself so that I can resolve the issue - and I'm unable to do so. Could you confirm the issue persists - and if so, provide the version of your Browser and the confirmation that you're using the latest Bitwarden extension version .. and I can take it from there?

Thanks!

**Comment by MattTheDev** [comment] 2020-07-10 21:40
Closing - unable to repro, engaged Clayton, unable to repro as well. Please feel free to re-open and we can investigate further.

**Closed by MattTheDev** 2020-07-10 21:40 UTC

**Comment by ZuBB** [comment] 2020-07-11 07:22
@MattTheDev are you sure about not being able to reproduce through update of the add-on? Few clearly stated it reproduces got them
