### ISSUE TITLE
Firefox: Openning the bitwarden panel fails every other time

### ISSUE THREAD

**Issue by ewjoachim** [bitwarden/browser#1177] opened 2020-03-19 20:35 UTC
I've disabled every other extension. When it opens, it opens fine, but the next time, it doesn't open, on and off, and on and off.

![Enregistrement de l’écran 2020-03-19 à 21 20 54](https://user-images.githubusercontent.com/1457576/77112455-53c76000-6a29-11ea-9115-79000d918704.gif)

Firefox 73.0.1 
Any idea ?

**Comment by kevinrobinson** [comment] 2020-03-26 17:25
I see something similar on Firefox 74 on OSX:

<img width="137" alt="Screen Shot 2020-03-26 at 1 24 13 PM" src="https://user-images.githubusercontent.com/1056957/77676747-20269180-6f65-11ea-8e63-1ddda1cdc86d.png">

Clicking again, the window opens as expected for me just like the original post.

**Comment by ewjoachim** [comment] 2020-03-26 23:03
For me the problem mysteriously disappeared, though. It survived a browser restart and a full system reboot, and then it disappeared, just like that. No idea why.

**Comment by mceachen** [comment] 2020-03-31 00:50
Same issue on Ubuntu 19.10 on Firefox. Restarting Firefox seems to have fixed the issue.

**Comment by jimwins** [comment] 2020-07-12 20:29
This looks like a duplicate of #951

**Comment by djsmith85** [comment] 2022-03-01 22:07
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2022-03-01 22:07 UTC
